#############################################################################
# Makefile for building: DOSTEM
# Generated by qmake (1.07a) (Qt 3.3.6) on: Sun Sep 16 16:57:18 2012
# Project:  DOSTEM.pro
# Template: app
# Command: $(QMAKE) -o Makefile DOSTEM.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib64/qt-3.3/mkspecs/default -I. -I. -Isrc -Isrc/runmodes -Isrc/input -Isrc/run -Isrc/output -Inetcdf/includes -Isrc/util -Isrc/inc -Isrc/data -Isrc/atmosphere -Isrc/vegetation -Isrc/ground -Isrc/ground/layer -Isrc/disturb -Isrc/lookup -I$(QTDIR)/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -lqt-mt -lXext -lX11 -lm -Lnetcdf/libs -lnetcdf_c++ -lnetcdf
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = src/TEMMOD.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		netcdf/includes/netcdf.hh \
		netcdf/includes/netcdfcpp.h \
		src/atmosphere/Atmosphere.h \
		src/atmosphere/AtmosUtil.h \
		src/data/BgcData.h \
		src/data/CohortData.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/GridData.h \
		src/data/RegionData.h \
		src/data/RestartData.h \
		src/disturb/WildFire.h \
		src/ground/DoubleLinkedList.h \
		src/ground/Ground.h \
		src/ground/Mineral.h \
		src/ground/Moss.h \
		src/ground/Peat.h \
		src/ground/Richard.h \
		src/ground/Rock.h \
		src/ground/Snow_Env.h \
		src/ground/Soil_Bgc.h \
		src/ground/Soil_Env.h \
		src/ground/Stefan.h \
		src/inc/cohortconst.h \
		src/inc/cohortkey.h \
		src/inc/diagnostics.h \
		src/inc/ErrorCode.h \
		src/inc/fluxes.h \
		src/inc/layerconst.h \
		src/inc/parameters.h \
		src/inc/PhysicalConstants.h \
		src/inc/runmode.h \
		src/inc/states.h \
		src/inc/temconst.h \
		src/inc/timeconst.h \
		src/input/CohortInputer.h \
		src/input/GridInputer.h \
		src/input/RegionInputer.h \
		src/input/RestartInputer.h \
		src/input/SiteinInputer.h \
		src/input/SoilclmInputer.h \
		src/lookup/CCohortLookup.h \
		src/lookup/CohortLookup.h \
		src/lookup/SoilLookup.h \
		src/output/AtmosphereOutputer.h \
		src/output/CCohortdriver.h \
		src/output/RegnOutputer.h \
		src/output/RestartOutputer.h \
		src/output/SiteOutputer.h \
		src/output/SnowSoilOutputer.h \
		src/output/SoilclmOutputer.h \
		src/output/StatusOutputer.h \
		src/output/VegetationOutputer.h \
		src/run/AtmOutData.h \
		src/run/Cohort.h \
		src/run/Controller.h \
		src/run/Grid.h \
		src/run/ModelData.h \
		src/run/parallel.h \
		src/run/RegnOutData.h \
		src/run/SiteIn.h \
		src/run/SnowSoilOutData.h \
		src/run/SoilClm.h \
		src/run/Timer.h \
		src/run/VegOutData.h \
		src/runmodes/Regioner.h \
		src/runmodes/RunCohort.h \
		src/runmodes/Siter.h \
		src/util/CrankNicholson.h \
		src/util/Exception.h \
		src/util/FileChecking.h \
		src/util/Integrator.h \
		src/util/Interpolator.h \
		src/vegetation/Vegetation_Bgc.h \
		src/vegetation/Vegetation_Env.h \
		src/ground/layer/Front.h \
		src/ground/layer/Layer.h \
		src/ground/layer/MineralLayer.h \
		src/ground/layer/MossLayer.h \
		src/ground/layer/OutputDepth.h \
		src/ground/layer/PeatLayer.h \
		src/ground/layer/RockLayer.h \
		src/ground/layer/SnowLayer.h \
		src/ground/layer/SoilLayer.h
SOURCES = src/TEM.cpp \
		src/atmosphere/Atmosphere.cpp \
		src/atmosphere/AtmosUtil.cpp \
		src/data/BgcData.cpp \
		src/data/CohortData.cpp \
		src/data/EnvData.cpp \
		src/data/FirData.cpp \
		src/data/GridData.cpp \
		src/data/RegionData.cpp \
		src/data/RestartData.cpp \
		src/disturb/WildFire.cpp \
		src/ground/DoubleLinkedList.cpp \
		src/ground/Ground.cpp \
		src/ground/Mineral.cpp \
		src/ground/Moss.cpp \
		src/ground/Peat.cpp \
		src/ground/Richard.cpp \
		src/ground/Rock.cpp \
		src/ground/Snow_Env.cpp \
		src/ground/Soil_Bgc.cpp \
		src/ground/Soil_Env.cpp \
		src/ground/Stefan.cpp \
		src/input/CohortInputer.cpp \
		src/input/GridInputer.cpp \
		src/input/RegionInputer.cpp \
		src/input/RestartInputer.cpp \
		src/input/SiteinInputer.cpp \
		src/input/SoilclmInputer.cpp \
		src/lookup/CCohortLookup.cpp \
		src/lookup/CohortLookup.cpp \
		src/lookup/SoilLookup.cpp \
		src/output/AtmosphereOutputer.cpp \
		src/output/CCohortdriver.cpp \
		src/output/RegnOutputer.cpp \
		src/output/RestartOutputer.cpp \
		src/output/SiteOutputer.cpp \
		src/output/SnowSoilOutputer.cpp \
		src/output/SoilclmOutputer.cpp \
		src/output/StatusOutputer.cpp \
		src/output/VegetationOutputer.cpp \
		src/run/AtmOutData.cpp \
		src/run/Cohort.cpp \
		src/run/Controller.cpp \
		src/run/Grid.cpp \
		src/run/ModelData.cpp \
		src/run/RegnOutData.cpp \
		src/run/SiteIn.cpp \
		src/run/SnowSoilOutData.cpp \
		src/run/SoilClm.cpp \
		src/run/Timer.cpp \
		src/run/VegOutData.cpp \
		src/runmodes/Regioner.cpp \
		src/runmodes/RunCohort.cpp \
		src/runmodes/Siter.cpp \
		src/util/CrankNicholson.cpp \
		src/util/Exception.cpp \
		src/util/FileChecking.cpp \
		src/util/Integrator.cpp \
		src/util/Interpolator.cpp \
		src/vegetation/Vegetation_Bgc.cpp \
		src/vegetation/Vegetation_Env.cpp \
		src/ground/layer/Front.cpp \
		src/ground/layer/Layer.cpp \
		src/ground/layer/MineralLayer.cpp \
		src/ground/layer/MossLayer.cpp \
		src/ground/layer/OutputDepth.cpp \
		src/ground/layer/PeatLayer.cpp \
		src/ground/layer/RockLayer.cpp \
		src/ground/layer/SnowLayer.cpp \
		src/ground/layer/SoilLayer.cpp
OBJECTS = TEM.o \
		Atmosphere.o \
		AtmosUtil.o \
		BgcData.o \
		CohortData.o \
		EnvData.o \
		FirData.o \
		GridData.o \
		RegionData.o \
		RestartData.o \
		WildFire.o \
		DoubleLinkedList.o \
		Ground.o \
		Mineral.o \
		Moss.o \
		Peat.o \
		Richard.o \
		Rock.o \
		Snow_Env.o \
		Soil_Bgc.o \
		Soil_Env.o \
		Stefan.o \
		CohortInputer.o \
		GridInputer.o \
		RegionInputer.o \
		RestartInputer.o \
		SiteinInputer.o \
		SoilclmInputer.o \
		CCohortLookup.o \
		CohortLookup.o \
		SoilLookup.o \
		AtmosphereOutputer.o \
		CCohortdriver.o \
		RegnOutputer.o \
		RestartOutputer.o \
		SiteOutputer.o \
		SnowSoilOutputer.o \
		SoilclmOutputer.o \
		StatusOutputer.o \
		VegetationOutputer.o \
		AtmOutData.o \
		Cohort.o \
		Controller.o \
		Grid.o \
		ModelData.o \
		RegnOutData.o \
		SiteIn.o \
		SnowSoilOutData.o \
		SoilClm.o \
		Timer.o \
		VegOutData.o \
		Regioner.o \
		RunCohort.o \
		Siter.o \
		CrankNicholson.o \
		Exception.o \
		FileChecking.o \
		Integrator.o \
		Interpolator.o \
		Vegetation_Bgc.o \
		Vegetation_Env.o \
		Front.o \
		Layer.o \
		MineralLayer.o \
		MossLayer.o \
		OutputDepth.o \
		PeatLayer.o \
		RockLayer.o \
		SnowLayer.o \
		SoilLayer.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = 
OBJMOC = 
DIST	   = DOSTEM.pro
QMAKE_TARGET = DOSTEM
DESTDIR  = 
TARGET   = DOSTEM

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: DOSTEM.pro  /usr/lib64/qt-3.3/mkspecs/default/qmake.conf /usr/lib64/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile DOSTEM.pro
qmake: 
	@$(QMAKE) -o Makefile DOSTEM.pro

dist: 
	@mkdir -p .tmp/DOSTEM && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/DOSTEM/ && ( cd `dirname .tmp/DOSTEM` && $(TAR) DOSTEM.tar DOSTEM && $(GZIP) DOSTEM.tar ) && $(MOVE) `dirname .tmp/DOSTEM`/DOSTEM.tar.gz . && $(DEL_FILE) -r .tmp/DOSTEM

mocclean:

uiclean:

yaccclean:
lexclean:
clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

TEM.o: src/TEM.cpp src/TEMMOD.h \
		src/runmodes/Siter.h \
		src/runmodes/Regioner.h \
		src/runmodes/RunCohort.h \
		src/input/RegionInputer.h \
		src/run/Controller.h \
		src/input/GridInputer.h \
		src/input/CohortInputer.h \
		src/input/SiteinInputer.h \
		src/input/RestartInputer.h \
		src/output/SiteOutputer.h \
		src/output/AtmosphereOutputer.h \
		src/output/VegetationOutputer.h \
		src/output/SnowSoilOutputer.h \
		src/output/StatusOutputer.h \
		src/output/RestartOutputer.h \
		src/output/RegnOutputer.h \
		src/run/Cohort.h \
		netcdf/includes/netcdfcpp.h \
		src/util/Exception.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/inc/ErrorCode.h \
		src/data/GridData.h \
		src/run/ModelData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/run/SiteIn.h \
		src/run/AtmOutData.h \
		src/run/VegOutData.h \
		src/run/SnowSoilOutData.h \
		src/data/RestartData.h \
		src/run/RegnOutData.h \
		src/atmosphere/Atmosphere.h \
		src/vegetation/Vegetation_Env.h \
		src/vegetation/Vegetation_Bgc.h \
		src/ground/Ground.h \
		src/ground/Snow_Env.h \
		src/ground/Soil_Env.h \
		src/ground/Soil_Bgc.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SnowLayer.h \
		src/ground/layer/SoilLayer.h \
		src/ground/layer/PeatLayer.h \
		src/disturb/WildFire.h \
		src/data/EnvData.h \
		src/data/BgcData.h \
		src/data/FirData.h \
		src/data/RegionData.h \
		src/data/CohortData.h \
		src/lookup/CohortLookup.h \
		src/util/Integrator.h \
		src/inc/parameters.h \
		src/run/Timer.h \
		src/run/Grid.h \
		src/run/SoilClm.h \
		src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h \
		src/ground/layer/MossLayer.h \
		src/inc/PhysicalConstants.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/ground/DoubleLinkedList.h \
		src/ground/layer/MineralLayer.h \
		src/ground/layer/RockLayer.h \
		src/ground/Rock.h \
		src/ground/Stefan.h \
		src/ground/Richard.h \
		src/ground/Moss.h \
		src/ground/Peat.h \
		src/ground/Mineral.h \
		src/util/CrankNicholson.h \
		src/inc/temconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TEM.o src/TEM.cpp

Atmosphere.o: src/atmosphere/Atmosphere.cpp src/atmosphere/Atmosphere.h \
		src/inc/timeconst.h \
		src/atmosphere/AtmosUtil.h \
		src/data/EnvData.h \
		src/data/GridData.h \
		src/data/RegionData.h \
		src/util/Interpolator.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/layerconst.h \
		src/data/CohortData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Atmosphere.o src/atmosphere/Atmosphere.cpp

AtmosUtil.o: src/atmosphere/AtmosUtil.cpp src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AtmosUtil.o src/atmosphere/AtmosUtil.cpp

BgcData.o: src/data/BgcData.cpp src/data/BgcData.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/data/EnvData.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BgcData.o src/data/BgcData.cpp

CohortData.o: src/data/CohortData.cpp src/data/CohortData.h \
		src/inc/timeconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CohortData.o src/data/CohortData.cpp

EnvData.o: src/data/EnvData.cpp src/data/EnvData.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnvData.o src/data/EnvData.cpp

FirData.o: src/data/FirData.cpp src/data/FirData.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/timeconst.h \
		src/data/EnvData.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FirData.o src/data/FirData.cpp

GridData.o: src/data/GridData.cpp src/data/GridData.h \
		src/inc/timeconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GridData.o src/data/GridData.cpp

RegionData.o: src/data/RegionData.cpp src/data/RegionData.h \
		src/inc/timeconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RegionData.o src/data/RegionData.cpp

RestartData.o: src/data/RestartData.cpp src/data/RestartData.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RestartData.o src/data/RestartData.cpp

WildFire.o: src/disturb/WildFire.cpp src/disturb/WildFire.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/BgcData.h \
		src/data/RestartData.h \
		src/inc/timeconst.h \
		src/inc/parameters.h \
		src/util/Exception.h \
		src/lookup/CohortLookup.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/layerconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/inc/ErrorCode.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WildFire.o src/disturb/WildFire.cpp

DoubleLinkedList.o: src/ground/DoubleLinkedList.cpp src/ground/DoubleLinkedList.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SoilLayer.h \
		src/inc/PhysicalConstants.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/util/Exception.h \
		src/inc/ErrorCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DoubleLinkedList.o src/ground/DoubleLinkedList.cpp

Ground.o: src/ground/Ground.cpp src/ground/Ground.h \
		src/ground/DoubleLinkedList.h \
		src/ground/layer/Layer.h \
		src/ground/layer/MossLayer.h \
		src/ground/layer/SnowLayer.h \
		src/ground/layer/MineralLayer.h \
		src/ground/layer/PeatLayer.h \
		src/ground/layer/RockLayer.h \
		src/ground/Snow_Env.h \
		src/ground/Soil_Env.h \
		src/ground/Rock.h \
		src/util/Exception.h \
		src/lookup/SoilLookup.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/BgcData.h \
		src/data/RestartData.h \
		src/ground/layer/SoilLayer.h \
		src/inc/PhysicalConstants.h \
		src/ground/layer/Front.h \
		src/inc/ErrorCode.h \
		src/inc/parameters.h \
		src/lookup/CohortLookup.h \
		src/inc/layerconst.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/timeconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h \
		src/ground/Stefan.h \
		src/ground/Richard.h \
		src/ground/Moss.h \
		src/ground/Peat.h \
		src/ground/Mineral.h \
		src/util/CrankNicholson.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ground.o src/ground/Ground.cpp

Mineral.o: src/ground/Mineral.cpp src/ground/Mineral.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mineral.o src/ground/Mineral.cpp

Moss.o: src/ground/Moss.cpp src/ground/Moss.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Moss.o src/ground/Moss.cpp

Peat.o: src/ground/Peat.cpp src/ground/Peat.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Peat.o src/ground/Peat.cpp

Richard.o: src/ground/Richard.cpp src/ground/Richard.h \
		src/inc/layerconst.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SoilLayer.h \
		src/util/CrankNicholson.h \
		src/data/EnvData.h \
		src/util/Exception.h \
		src/inc/PhysicalConstants.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/inc/ErrorCode.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/timeconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Richard.o src/ground/Richard.cpp

Rock.o: src/ground/Rock.cpp src/ground/Rock.h \
		src/ground/layer/Layer.h \
		src/inc/layerconst.h \
		src/data/EnvData.h \
		src/data/RestartData.h \
		src/inc/PhysicalConstants.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/timeconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Rock.o src/ground/Rock.cpp

Snow_Env.o: src/ground/Snow_Env.cpp src/ground/Snow_Env.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/RestartData.h \
		src/inc/parameters.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SnowLayer.h \
		src/lookup/CohortLookup.h \
		src/inc/layerconst.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/timeconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/inc/PhysicalConstants.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Snow_Env.o src/ground/Snow_Env.cpp

Soil_Bgc.o: src/ground/Soil_Bgc.cpp src/ground/Soil_Bgc.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/BgcData.h \
		src/data/RestartData.h \
		src/lookup/CohortLookup.h \
		src/inc/states.h \
		src/inc/fluxes.h \
		src/inc/diagnostics.h \
		src/inc/parameters.h \
		src/inc/layerconst.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SoilLayer.h \
		src/ground/layer/MossLayer.h \
		src/ground/layer/PeatLayer.h \
		src/util/Exception.h \
		src/inc/timeconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h \
		src/inc/PhysicalConstants.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/inc/ErrorCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Soil_Bgc.o src/ground/Soil_Bgc.cpp

Soil_Env.o: src/ground/Soil_Env.cpp src/ground/Soil_Env.h \
		src/ground/Stefan.h \
		src/ground/Richard.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/RestartData.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SoilLayer.h \
		src/ground/layer/PeatLayer.h \
		src/inc/parameters.h \
		src/lookup/CohortLookup.h \
		src/inc/layerconst.h \
		src/ground/Moss.h \
		src/ground/Peat.h \
		src/ground/Mineral.h \
		src/inc/ErrorCode.h \
		src/util/Exception.h \
		src/ground/layer/SnowLayer.h \
		src/inc/PhysicalConstants.h \
		src/util/CrankNicholson.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/timeconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Soil_Env.o src/ground/Soil_Env.cpp

Stefan.o: src/ground/Stefan.cpp src/ground/Stefan.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SoilLayer.h \
		src/ground/layer/SnowLayer.h \
		src/inc/PhysicalConstants.h \
		src/util/CrankNicholson.h \
		src/util/Exception.h \
		src/inc/ErrorCode.h \
		src/inc/layerconst.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stefan.o src/ground/Stefan.cpp

CohortInputer.o: src/input/CohortInputer.cpp src/input/CohortInputer.h \
		netcdf/includes/netcdfcpp.h \
		src/run/ModelData.h \
		src/util/Exception.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/inc/ErrorCode.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CohortInputer.o src/input/CohortInputer.cpp

GridInputer.o: src/input/GridInputer.cpp src/input/GridInputer.h \
		netcdf/includes/netcdfcpp.h \
		src/util/Exception.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/inc/ErrorCode.h \
		src/data/GridData.h \
		src/run/ModelData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GridInputer.o src/input/GridInputer.cpp

RegionInputer.o: src/input/RegionInputer.cpp src/input/RegionInputer.h \
		netcdf/includes/netcdfcpp.h \
		src/data/RegionData.h \
		src/inc/ErrorCode.h \
		src/util/Exception.h \
		src/run/ModelData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/timeconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RegionInputer.o src/input/RegionInputer.cpp

RestartInputer.o: src/input/RestartInputer.cpp src/input/RestartInputer.h \
		netcdf/includes/netcdfcpp.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/inc/ErrorCode.h \
		src/util/Exception.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RestartInputer.o src/input/RestartInputer.cpp

SiteinInputer.o: src/input/SiteinInputer.cpp src/input/SiteinInputer.h \
		netcdf/includes/netcdfcpp.h \
		src/util/Exception.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/inc/ErrorCode.h \
		src/run/SiteIn.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SiteinInputer.o src/input/SiteinInputer.cpp

SoilclmInputer.o: src/input/SoilclmInputer.cpp src/input/SoilclmInputer.h \
		netcdf/includes/netcdfcpp.h \
		src/util/Exception.h \
		src/run/SoilClm.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/ErrorCode.h \
		src/inc/timeconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoilclmInputer.o src/input/SoilclmInputer.cpp

CCohortLookup.o: src/lookup/CCohortLookup.cpp src/lookup/CCohortLookup.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CCohortLookup.o src/lookup/CCohortLookup.cpp

CohortLookup.o: src/lookup/CohortLookup.cpp src/lookup/CohortLookup.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h \
		src/inc/timeconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CohortLookup.o src/lookup/CohortLookup.cpp

SoilLookup.o: src/lookup/SoilLookup.cpp src/lookup/SoilLookup.h \
		src/inc/PhysicalConstants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoilLookup.o src/lookup/SoilLookup.cpp

AtmosphereOutputer.o: src/output/AtmosphereOutputer.cpp src/output/AtmosphereOutputer.h \
		netcdf/includes/netcdfcpp.h \
		netcdf/includes/ncvalues.h \
		src/output/SiteOutputer.h \
		src/run/AtmOutData.h \
		src/inc/timeconst.h \
		netcdf/includes/netcdf.h \
		src/inc/layerconst.h \
		src/run/ModelData.h \
		src/TEMMOD.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AtmosphereOutputer.o src/output/AtmosphereOutputer.cpp

CCohortdriver.o: src/output/CCohortdriver.cpp src/output/CCohortdriver.h \
		netcdf/includes/netcdfcpp.h \
		netcdf/includes/ncvalues.h \
		src/util/Exception.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/run/Cohort.h \
		netcdf/includes/netcdf.h \
		src/inc/ErrorCode.h \
		src/atmosphere/Atmosphere.h \
		src/vegetation/Vegetation_Env.h \
		src/vegetation/Vegetation_Bgc.h \
		src/ground/Ground.h \
		src/ground/Snow_Env.h \
		src/ground/Soil_Env.h \
		src/ground/Soil_Bgc.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SnowLayer.h \
		src/ground/layer/SoilLayer.h \
		src/ground/layer/PeatLayer.h \
		src/disturb/WildFire.h \
		src/data/EnvData.h \
		src/data/BgcData.h \
		src/data/FirData.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/data/RestartData.h \
		src/lookup/CohortLookup.h \
		src/util/Integrator.h \
		src/inc/parameters.h \
		src/run/Timer.h \
		src/run/ModelData.h \
		src/run/Grid.h \
		src/run/SiteIn.h \
		src/run/SoilClm.h \
		src/run/AtmOutData.h \
		src/run/VegOutData.h \
		src/run/SnowSoilOutData.h \
		src/run/RegnOutData.h \
		src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h \
		src/ground/layer/MossLayer.h \
		src/inc/PhysicalConstants.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/ground/DoubleLinkedList.h \
		src/ground/layer/MineralLayer.h \
		src/ground/layer/RockLayer.h \
		src/ground/Rock.h \
		src/ground/Stefan.h \
		src/ground/Richard.h \
		src/ground/Moss.h \
		src/ground/Peat.h \
		src/ground/Mineral.h \
		src/util/CrankNicholson.h \
		src/inc/temconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CCohortdriver.o src/output/CCohortdriver.cpp

RegnOutputer.o: src/output/RegnOutputer.cpp src/output/RegnOutputer.h \
		netcdf/includes/netcdfcpp.h \
		netcdf/includes/ncvalues.h \
		src/run/RegnOutData.h \
		netcdf/includes/netcdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RegnOutputer.o src/output/RegnOutputer.cpp

RestartOutputer.o: src/output/RestartOutputer.cpp src/output/RestartOutputer.h \
		netcdf/includes/netcdfcpp.h \
		netcdf/includes/ncvalues.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/data/RestartData.h \
		netcdf/includes/netcdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RestartOutputer.o src/output/RestartOutputer.cpp

SiteOutputer.o: src/output/SiteOutputer.cpp src/output/SiteOutputer.h \
		netcdf/includes/netcdfcpp.h \
		netcdf/includes/ncvalues.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/run/ModelData.h \
		src/TEMMOD.h \
		netcdf/includes/netcdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SiteOutputer.o src/output/SiteOutputer.cpp

SnowSoilOutputer.o: src/output/SnowSoilOutputer.cpp src/output/SnowSoilOutputer.h \
		netcdf/includes/netcdfcpp.h \
		netcdf/includes/ncvalues.h \
		src/output/SiteOutputer.h \
		src/run/SnowSoilOutData.h \
		src/inc/timeconst.h \
		src/inc/layerconst.h \
		netcdf/includes/netcdf.h \
		src/run/ModelData.h \
		src/TEMMOD.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SnowSoilOutputer.o src/output/SnowSoilOutputer.cpp

SoilclmOutputer.o: src/output/SoilclmOutputer.cpp src/output/SoilclmOutputer.h \
		netcdf/includes/netcdfcpp.h \
		netcdf/includes/ncvalues.h \
		src/util/Exception.h \
		src/run/SoilClm.h \
		netcdf/includes/netcdf.h \
		src/inc/ErrorCode.h \
		src/inc/timeconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoilclmOutputer.o src/output/SoilclmOutputer.cpp

StatusOutputer.o: src/output/StatusOutputer.cpp src/output/StatusOutputer.h \
		netcdf/includes/netcdfcpp.h \
		netcdf/includes/ncvalues.h \
		src/inc/timeconst.h \
		netcdf/includes/netcdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StatusOutputer.o src/output/StatusOutputer.cpp

VegetationOutputer.o: src/output/VegetationOutputer.cpp src/output/VegetationOutputer.h \
		netcdf/includes/netcdfcpp.h \
		netcdf/includes/ncvalues.h \
		src/output/SiteOutputer.h \
		src/inc/timeconst.h \
		src/run/VegOutData.h \
		netcdf/includes/netcdf.h \
		src/inc/layerconst.h \
		src/run/ModelData.h \
		src/TEMMOD.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VegetationOutputer.o src/output/VegetationOutputer.cpp

AtmOutData.o: src/run/AtmOutData.cpp src/run/AtmOutData.h \
		src/inc/timeconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AtmOutData.o src/run/AtmOutData.cpp

Cohort.o: src/run/Cohort.cpp src/run/Cohort.h \
		src/atmosphere/Atmosphere.h \
		src/vegetation/Vegetation_Env.h \
		src/vegetation/Vegetation_Bgc.h \
		src/ground/Ground.h \
		src/ground/Snow_Env.h \
		src/ground/Soil_Env.h \
		src/ground/Soil_Bgc.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SnowLayer.h \
		src/ground/layer/SoilLayer.h \
		src/ground/layer/PeatLayer.h \
		src/disturb/WildFire.h \
		src/data/EnvData.h \
		src/data/BgcData.h \
		src/data/FirData.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/data/RestartData.h \
		src/lookup/CohortLookup.h \
		src/util/Integrator.h \
		src/inc/layerconst.h \
		src/inc/parameters.h \
		src/run/Timer.h \
		src/run/ModelData.h \
		src/run/Grid.h \
		src/run/SiteIn.h \
		src/run/SoilClm.h \
		src/run/AtmOutData.h \
		src/run/VegOutData.h \
		src/run/SnowSoilOutData.h \
		src/run/RegnOutData.h \
		src/inc/timeconst.h \
		src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h \
		src/ground/layer/MossLayer.h \
		src/util/Exception.h \
		src/inc/PhysicalConstants.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/inc/ErrorCode.h \
		src/ground/DoubleLinkedList.h \
		src/ground/layer/MineralLayer.h \
		src/ground/layer/RockLayer.h \
		src/ground/Rock.h \
		src/ground/Stefan.h \
		src/ground/Richard.h \
		src/ground/Moss.h \
		src/ground/Peat.h \
		src/ground/Mineral.h \
		src/util/CrankNicholson.h \
		src/inc/temconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cohort.o src/run/Cohort.cpp

Controller.o: src/run/Controller.cpp src/run/Controller.h \
		src/util/Exception.h \
		src/run/ModelData.h \
		src/inc/ErrorCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Controller.o src/run/Controller.cpp

Grid.o: src/run/Grid.cpp src/run/Grid.h \
		src/atmosphere/Atmosphere.h \
		src/data/EnvData.h \
		src/data/GridData.h \
		src/data/RegionData.h \
		src/util/Exception.h \
		src/inc/ErrorCode.h \
		src/inc/timeconst.h \
		src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/layerconst.h \
		src/data/CohortData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Grid.o src/run/Grid.cpp

ModelData.o: src/run/ModelData.cpp src/run/ModelData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ModelData.o src/run/ModelData.cpp

RegnOutData.o: src/run/RegnOutData.cpp src/run/RegnOutData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RegnOutData.o src/run/RegnOutData.cpp

SiteIn.o: src/run/SiteIn.cpp src/run/SiteIn.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SiteIn.o src/run/SiteIn.cpp

SnowSoilOutData.o: src/run/SnowSoilOutData.cpp src/run/SnowSoilOutData.h \
		src/inc/timeconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SnowSoilOutData.o src/run/SnowSoilOutData.cpp

SoilClm.o: src/run/SoilClm.cpp src/run/SoilClm.h \
		src/inc/timeconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoilClm.o src/run/SoilClm.cpp

Timer.o: src/run/Timer.cpp src/run/Timer.h \
		src/inc/timeconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Timer.o src/run/Timer.cpp

VegOutData.o: src/run/VegOutData.cpp src/run/VegOutData.h \
		src/inc/timeconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VegOutData.o src/run/VegOutData.cpp

Regioner.o: src/runmodes/Regioner.cpp src/runmodes/Regioner.h \
		src/input/RegionInputer.h \
		src/run/Controller.h \
		src/output/StatusOutputer.h \
		src/runmodes/RunCohort.h \
		netcdf/includes/netcdfcpp.h \
		src/data/RegionData.h \
		src/inc/ErrorCode.h \
		src/util/Exception.h \
		src/run/ModelData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/timeconst.h \
		src/TEMMOD.h \
		src/input/GridInputer.h \
		src/input/CohortInputer.h \
		src/input/SiteinInputer.h \
		src/input/RestartInputer.h \
		src/output/SiteOutputer.h \
		src/output/AtmosphereOutputer.h \
		src/output/VegetationOutputer.h \
		src/output/SnowSoilOutputer.h \
		src/output/RestartOutputer.h \
		src/output/RegnOutputer.h \
		src/run/Cohort.h \
		src/inc/layerconst.h \
		src/data/GridData.h \
		src/run/SiteIn.h \
		src/run/AtmOutData.h \
		src/run/VegOutData.h \
		src/run/SnowSoilOutData.h \
		src/data/RestartData.h \
		src/run/RegnOutData.h \
		src/atmosphere/Atmosphere.h \
		src/vegetation/Vegetation_Env.h \
		src/vegetation/Vegetation_Bgc.h \
		src/ground/Ground.h \
		src/ground/Snow_Env.h \
		src/ground/Soil_Env.h \
		src/ground/Soil_Bgc.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SnowLayer.h \
		src/ground/layer/SoilLayer.h \
		src/ground/layer/PeatLayer.h \
		src/disturb/WildFire.h \
		src/data/EnvData.h \
		src/data/BgcData.h \
		src/data/FirData.h \
		src/data/CohortData.h \
		src/lookup/CohortLookup.h \
		src/util/Integrator.h \
		src/inc/parameters.h \
		src/run/Timer.h \
		src/run/Grid.h \
		src/run/SoilClm.h \
		src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h \
		src/ground/layer/MossLayer.h \
		src/inc/PhysicalConstants.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/ground/DoubleLinkedList.h \
		src/ground/layer/MineralLayer.h \
		src/ground/layer/RockLayer.h \
		src/ground/Rock.h \
		src/ground/Stefan.h \
		src/ground/Richard.h \
		src/ground/Moss.h \
		src/ground/Peat.h \
		src/ground/Mineral.h \
		src/util/CrankNicholson.h \
		src/inc/temconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Regioner.o src/runmodes/Regioner.cpp

RunCohort.o: src/runmodes/RunCohort.cpp src/runmodes/RunCohort.h \
		src/TEMMOD.h \
		src/input/GridInputer.h \
		src/input/CohortInputer.h \
		src/input/SiteinInputer.h \
		src/input/RestartInputer.h \
		src/output/SiteOutputer.h \
		src/output/AtmosphereOutputer.h \
		src/output/VegetationOutputer.h \
		src/output/SnowSoilOutputer.h \
		src/output/StatusOutputer.h \
		src/output/RestartOutputer.h \
		src/output/RegnOutputer.h \
		src/run/Cohort.h \
		netcdf/includes/netcdfcpp.h \
		src/util/Exception.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/inc/ErrorCode.h \
		src/data/GridData.h \
		src/run/ModelData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/run/SiteIn.h \
		src/run/AtmOutData.h \
		src/run/VegOutData.h \
		src/run/SnowSoilOutData.h \
		src/data/RestartData.h \
		src/run/RegnOutData.h \
		src/atmosphere/Atmosphere.h \
		src/vegetation/Vegetation_Env.h \
		src/vegetation/Vegetation_Bgc.h \
		src/ground/Ground.h \
		src/ground/Snow_Env.h \
		src/ground/Soil_Env.h \
		src/ground/Soil_Bgc.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SnowLayer.h \
		src/ground/layer/SoilLayer.h \
		src/ground/layer/PeatLayer.h \
		src/disturb/WildFire.h \
		src/data/EnvData.h \
		src/data/BgcData.h \
		src/data/FirData.h \
		src/data/RegionData.h \
		src/data/CohortData.h \
		src/lookup/CohortLookup.h \
		src/util/Integrator.h \
		src/inc/parameters.h \
		src/run/Timer.h \
		src/run/Grid.h \
		src/run/SoilClm.h \
		src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h \
		src/ground/layer/MossLayer.h \
		src/inc/PhysicalConstants.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/ground/DoubleLinkedList.h \
		src/ground/layer/MineralLayer.h \
		src/ground/layer/RockLayer.h \
		src/ground/Rock.h \
		src/ground/Stefan.h \
		src/ground/Richard.h \
		src/ground/Moss.h \
		src/ground/Peat.h \
		src/ground/Mineral.h \
		src/util/CrankNicholson.h \
		src/inc/temconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RunCohort.o src/runmodes/RunCohort.cpp

Siter.o: src/runmodes/Siter.cpp src/runmodes/Siter.h \
		src/runmodes/RunCohort.h \
		src/input/RegionInputer.h \
		src/run/Controller.h \
		src/TEMMOD.h \
		src/input/GridInputer.h \
		src/input/CohortInputer.h \
		src/input/SiteinInputer.h \
		src/input/RestartInputer.h \
		src/output/SiteOutputer.h \
		src/output/AtmosphereOutputer.h \
		src/output/VegetationOutputer.h \
		src/output/SnowSoilOutputer.h \
		src/output/StatusOutputer.h \
		src/output/RestartOutputer.h \
		src/output/RegnOutputer.h \
		src/run/Cohort.h \
		netcdf/includes/netcdfcpp.h \
		src/util/Exception.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/inc/ErrorCode.h \
		src/data/GridData.h \
		src/run/ModelData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/run/SiteIn.h \
		src/run/AtmOutData.h \
		src/run/VegOutData.h \
		src/run/SnowSoilOutData.h \
		src/data/RestartData.h \
		src/run/RegnOutData.h \
		src/atmosphere/Atmosphere.h \
		src/vegetation/Vegetation_Env.h \
		src/vegetation/Vegetation_Bgc.h \
		src/ground/Ground.h \
		src/ground/Snow_Env.h \
		src/ground/Soil_Env.h \
		src/ground/Soil_Bgc.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SnowLayer.h \
		src/ground/layer/SoilLayer.h \
		src/ground/layer/PeatLayer.h \
		src/disturb/WildFire.h \
		src/data/EnvData.h \
		src/data/BgcData.h \
		src/data/FirData.h \
		src/data/RegionData.h \
		src/data/CohortData.h \
		src/lookup/CohortLookup.h \
		src/util/Integrator.h \
		src/inc/parameters.h \
		src/run/Timer.h \
		src/run/Grid.h \
		src/run/SoilClm.h \
		src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h \
		src/ground/layer/MossLayer.h \
		src/inc/PhysicalConstants.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/ground/DoubleLinkedList.h \
		src/ground/layer/MineralLayer.h \
		src/ground/layer/RockLayer.h \
		src/ground/Rock.h \
		src/ground/Stefan.h \
		src/ground/Richard.h \
		src/ground/Moss.h \
		src/ground/Peat.h \
		src/ground/Mineral.h \
		src/util/CrankNicholson.h \
		src/inc/temconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Siter.o src/runmodes/Siter.cpp

CrankNicholson.o: src/util/CrankNicholson.cpp src/util/CrankNicholson.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CrankNicholson.o src/util/CrankNicholson.cpp

Exception.o: src/util/Exception.cpp src/util/Exception.h \
		src/inc/ErrorCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Exception.o src/util/Exception.cpp

FileChecking.o: src/util/FileChecking.cpp src/util/FileChecking.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileChecking.o src/util/FileChecking.cpp

Integrator.o: src/util/Integrator.cpp src/util/Integrator.h \
		src/inc/temconst.h \
		src/ground/Soil_Bgc.h \
		src/vegetation/Vegetation_Bgc.h \
		src/data/BgcData.h \
		src/data/EnvData.h \
		src/inc/layerconst.h \
		src/data/FirData.h \
		src/data/RestartData.h \
		src/lookup/CohortLookup.h \
		src/inc/states.h \
		src/inc/fluxes.h \
		src/inc/diagnostics.h \
		src/inc/parameters.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SoilLayer.h \
		src/ground/layer/MossLayer.h \
		src/ground/layer/PeatLayer.h \
		src/util/Exception.h \
		src/inc/timeconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h \
		src/inc/PhysicalConstants.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/inc/ErrorCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Integrator.o src/util/Integrator.cpp

Interpolator.o: src/util/Interpolator.cpp src/util/Interpolator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Interpolator.o src/util/Interpolator.cpp

Vegetation_Bgc.o: src/vegetation/Vegetation_Bgc.cpp src/vegetation/Vegetation_Bgc.h \
		src/lookup/CohortLookup.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/BgcData.h \
		src/data/RestartData.h \
		src/inc/states.h \
		src/inc/fluxes.h \
		src/inc/diagnostics.h \
		src/inc/parameters.h \
		src/ground/Soil_Bgc.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h \
		src/inc/timeconst.h \
		src/inc/layerconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/ground/layer/Layer.h \
		src/ground/layer/SoilLayer.h \
		src/ground/layer/MossLayer.h \
		src/ground/layer/PeatLayer.h \
		src/util/Exception.h \
		src/inc/PhysicalConstants.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/inc/ErrorCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vegetation_Bgc.o src/vegetation/Vegetation_Bgc.cpp

Vegetation_Env.o: src/vegetation/Vegetation_Env.cpp src/vegetation/Vegetation_Env.h \
		src/lookup/CohortLookup.h \
		src/inc/states.h \
		src/inc/fluxes.h \
		src/inc/diagnostics.h \
		src/inc/parameters.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/RestartData.h \
		src/inc/cohortkey.h \
		src/inc/cohortconst.h \
		src/inc/timeconst.h \
		src/inc/layerconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vegetation_Env.o src/vegetation/Vegetation_Env.cpp

Front.o: src/ground/layer/Front.cpp src/ground/layer/Front.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Front.o src/ground/layer/Front.cpp

Layer.o: src/ground/layer/Layer.cpp src/ground/layer/Layer.h \
		src/inc/PhysicalConstants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Layer.o src/ground/layer/Layer.cpp

MineralLayer.o: src/ground/layer/MineralLayer.cpp src/ground/layer/MineralLayer.h \
		src/ground/layer/SoilLayer.h \
		src/inc/PhysicalConstants.h \
		src/ground/layer/Layer.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/util/Exception.h \
		src/inc/ErrorCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MineralLayer.o src/ground/layer/MineralLayer.cpp

MossLayer.o: src/ground/layer/MossLayer.cpp src/ground/layer/MossLayer.h \
		src/ground/layer/SoilLayer.h \
		src/inc/PhysicalConstants.h \
		src/ground/layer/Layer.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/util/Exception.h \
		src/inc/ErrorCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MossLayer.o src/ground/layer/MossLayer.cpp

OutputDepth.o: src/ground/layer/OutputDepth.cpp src/ground/layer/OutputDepth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OutputDepth.o src/ground/layer/OutputDepth.cpp

PeatLayer.o: src/ground/layer/PeatLayer.cpp src/ground/layer/PeatLayer.h \
		src/ground/layer/SoilLayer.h \
		src/inc/PhysicalConstants.h \
		src/ground/layer/Layer.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/util/Exception.h \
		src/inc/ErrorCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PeatLayer.o src/ground/layer/PeatLayer.cpp

RockLayer.o: src/ground/layer/RockLayer.cpp src/ground/layer/RockLayer.h \
		src/ground/layer/Layer.h \
		src/inc/PhysicalConstants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RockLayer.o src/ground/layer/RockLayer.cpp

SnowLayer.o: src/ground/layer/SnowLayer.cpp src/ground/layer/SnowLayer.h \
		src/ground/layer/Layer.h \
		src/inc/PhysicalConstants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SnowLayer.o src/ground/layer/SnowLayer.cpp

SoilLayer.o: src/ground/layer/SoilLayer.cpp src/ground/layer/SoilLayer.h \
		src/ground/layer/Layer.h \
		src/inc/PhysicalConstants.h \
		src/lookup/SoilLookup.h \
		src/ground/layer/Front.h \
		src/util/Exception.h \
		src/inc/ErrorCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoilLayer.o src/ground/layer/SoilLayer.cpp

####### Install

install:  

uninstall:  

