/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class atm2veg_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected atm2veg_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(atm2veg_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_atm2veg_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRnfl(double value) {
    temcoreJNI.atm2veg_env_rnfl_set(swigCPtr, this, value);
  }

  public double getRnfl() {
    return temcoreJNI.atm2veg_env_rnfl_get(swigCPtr, this);
  }

  public void setSnfl(double value) {
    temcoreJNI.atm2veg_env_snfl_set(swigCPtr, this, value);
  }

  public double getSnfl() {
    return temcoreJNI.atm2veg_env_snfl_get(swigCPtr, this);
  }

  public atm2veg_env() {
    this(temcoreJNI.new_atm2veg_env(), true);
  }

}
