/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class atm2soi_bgc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected atm2soi_bgc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(atm2soi_bgc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_atm2soi_bgc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNinput(double value) {
    temcoreJNI.atm2soi_bgc_ninput_set(swigCPtr, this, value);
  }

  public double getNinput() {
    return temcoreJNI.atm2soi_bgc_ninput_get(swigCPtr, this);
  }

  public atm2soi_bgc() {
    this(temcoreJNI.new_atm2soi_bgc(), true);
  }

}
