/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class atmdiag_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected atmdiag_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(atmdiag_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_atmdiag_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRhoa(double value) {
    temcoreJNI.atmdiag_env_rhoa_set(swigCPtr, this, value);
  }

  public double getRhoa() {
    return temcoreJNI.atmdiag_env_rhoa_get(swigCPtr, this);
  }

  public void setVpd(double value) {
    temcoreJNI.atmdiag_env_vpd_set(swigCPtr, this, value);
  }

  public double getVpd() {
    return temcoreJNI.atmdiag_env_vpd_get(swigCPtr, this);
  }

  public void setAbshd(double value) {
    temcoreJNI.atmdiag_env_abshd_set(swigCPtr, this, value);
  }

  public double getAbshd() {
    return temcoreJNI.atmdiag_env_abshd_get(swigCPtr, this);
  }

  public void setDersvp(double value) {
    temcoreJNI.atmdiag_env_dersvp_set(swigCPtr, this, value);
  }

  public double getDersvp() {
    return temcoreJNI.atmdiag_env_dersvp_get(swigCPtr, this);
  }

  public void setVp(double value) {
    temcoreJNI.atmdiag_env_vp_set(swigCPtr, this, value);
  }

  public double getVp() {
    return temcoreJNI.atmdiag_env_vp_get(swigCPtr, this);
  }

  public void setSvp(double value) {
    temcoreJNI.atmdiag_env_svp_set(swigCPtr, this, value);
  }

  public double getSvp() {
    return temcoreJNI.atmdiag_env_svp_get(swigCPtr, this);
  }

  public atmdiag_env() {
    this(temcoreJNI.new_atmdiag_env(), true);
  }

}
