/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class AtmOutData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AtmOutData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AtmOutData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_AtmOutData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AtmOutData() {
    this(temcoreJNI.new_AtmOutData(), true);
  }

  public void setTdrvd(float[] value) {
    temcoreJNI.AtmOutData_tdrvd_set(swigCPtr, this, value);
  }

  public float[] getTdrvd() {
    return temcoreJNI.AtmOutData_tdrvd_get(swigCPtr, this);
  }

  public void setRaind(float[] value) {
    temcoreJNI.AtmOutData_raind_set(swigCPtr, this, value);
  }

  public float[] getRaind() {
    return temcoreJNI.AtmOutData_raind_get(swigCPtr, this);
  }

  public void setSnowd(float[] value) {
    temcoreJNI.AtmOutData_snowd_set(swigCPtr, this, value);
  }

  public float[] getSnowd() {
    return temcoreJNI.AtmOutData_snowd_get(swigCPtr, this);
  }

  public void setSvpd(float[] value) {
    temcoreJNI.AtmOutData_svpd_set(swigCPtr, this, value);
  }

  public float[] getSvpd() {
    return temcoreJNI.AtmOutData_svpd_get(swigCPtr, this);
  }

  public void setDersvpd(float[] value) {
    temcoreJNI.AtmOutData_dersvpd_set(swigCPtr, this, value);
  }

  public float[] getDersvpd() {
    return temcoreJNI.AtmOutData_dersvpd_get(swigCPtr, this);
  }

  public void setRhoad(float[] value) {
    temcoreJNI.AtmOutData_rhoad_set(swigCPtr, this, value);
  }

  public float[] getRhoad() {
    return temcoreJNI.AtmOutData_rhoad_get(swigCPtr, this);
  }

  public void setAbshdd(float[] value) {
    temcoreJNI.AtmOutData_abshdd_set(swigCPtr, this, value);
  }

  public float[] getAbshdd() {
    return temcoreJNI.AtmOutData_abshdd_get(swigCPtr, this);
  }

  public void setDsrd(float[] value) {
    temcoreJNI.AtmOutData_dsrd_set(swigCPtr, this, value);
  }

  public float[] getDsrd() {
    return temcoreJNI.AtmOutData_dsrd_get(swigCPtr, this);
  }

  public void setTa(float[] value) {
    temcoreJNI.AtmOutData_ta_set(swigCPtr, this, value);
  }

  public float[] getTa() {
    return temcoreJNI.AtmOutData_ta_get(swigCPtr, this);
  }

  public void setClds(float[] value) {
    temcoreJNI.AtmOutData_clds_set(swigCPtr, this, value);
  }

  public float[] getClds() {
    return temcoreJNI.AtmOutData_clds_get(swigCPtr, this);
  }

  public void setCo2(float[] value) {
    temcoreJNI.AtmOutData_co2_set(swigCPtr, this, value);
  }

  public float[] getCo2() {
    return temcoreJNI.AtmOutData_co2_get(swigCPtr, this);
  }

  public void setEet(float[] value) {
    temcoreJNI.AtmOutData_eet_set(swigCPtr, this, value);
  }

  public float[] getEet() {
    return temcoreJNI.AtmOutData_eet_get(swigCPtr, this);
  }

  public void setPet(float[] value) {
    temcoreJNI.AtmOutData_pet_set(swigCPtr, this, value);
  }

  public float[] getPet() {
    return temcoreJNI.AtmOutData_pet_get(swigCPtr, this);
  }

  public void setRnfl(float[] value) {
    temcoreJNI.AtmOutData_rnfl_set(swigCPtr, this, value);
  }

  public float[] getRnfl() {
    return temcoreJNI.AtmOutData_rnfl_get(swigCPtr, this);
  }

  public void setSnfl(float[] value) {
    temcoreJNI.AtmOutData_snfl_set(swigCPtr, this, value);
  }

  public float[] getSnfl() {
    return temcoreJNI.AtmOutData_snfl_get(swigCPtr, this);
  }

  public void setGirr(float[] value) {
    temcoreJNI.AtmOutData_girr_set(swigCPtr, this, value);
  }

  public float[] getGirr() {
    return temcoreJNI.AtmOutData_girr_get(swigCPtr, this);
  }

  public void setNirr(float[] value) {
    temcoreJNI.AtmOutData_nirr_set(swigCPtr, this, value);
  }

  public float[] getNirr() {
    return temcoreJNI.AtmOutData_nirr_get(swigCPtr, this);
  }

  public void setPar(float[] value) {
    temcoreJNI.AtmOutData_par_set(swigCPtr, this, value);
  }

  public float[] getPar() {
    return temcoreJNI.AtmOutData_par_get(swigCPtr, this);
  }

  public void setYrrnfl(float value) {
    temcoreJNI.AtmOutData_yrrnfl_set(swigCPtr, this, value);
  }

  public float getYrrnfl() {
    return temcoreJNI.AtmOutData_yrrnfl_get(swigCPtr, this);
  }

  public void setYrsnfl(float value) {
    temcoreJNI.AtmOutData_yrsnfl_set(swigCPtr, this, value);
  }

  public float getYrsnfl() {
    return temcoreJNI.AtmOutData_yrsnfl_get(swigCPtr, this);
  }

  public void setYrta(float value) {
    temcoreJNI.AtmOutData_yrta_set(swigCPtr, this, value);
  }

  public float getYrta() {
    return temcoreJNI.AtmOutData_yrta_get(swigCPtr, this);
  }

}
