/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class atmstate_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected atmstate_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(atmstate_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_atmstate_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTa(double value) {
    temcoreJNI.atmstate_env_ta_set(swigCPtr, this, value);
  }

  public double getTa() {
    return temcoreJNI.atmstate_env_ta_get(swigCPtr, this);
  }

  public void setClds(double value) {
    temcoreJNI.atmstate_env_clds_set(swigCPtr, this, value);
  }

  public double getClds() {
    return temcoreJNI.atmstate_env_clds_get(swigCPtr, this);
  }

  public void setCo2(double value) {
    temcoreJNI.atmstate_env_co2_set(swigCPtr, this, value);
  }

  public double getCo2() {
    return temcoreJNI.atmstate_env_co2_get(swigCPtr, this);
  }

  public void setDsr(int value) {
    temcoreJNI.atmstate_env_dsr_set(swigCPtr, this, value);
  }

  public int getDsr() {
    return temcoreJNI.atmstate_env_dsr_get(swigCPtr, this);
  }

  public atmstate_env() {
    this(temcoreJNI.new_atmstate_env(), true);
  }

}
