/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class BgcData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BgcData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BgcData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_BgcData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BgcData() {
    this(temcoreJNI.new_BgcData(), true);
  }

  public void setM_vegs(vegstate_bgc value) {
    temcoreJNI.BgcData_m_vegs_set(swigCPtr, this, vegstate_bgc.getCPtr(value), value);
  }

  public vegstate_bgc getM_vegs() {
    long cPtr = temcoreJNI.BgcData_m_vegs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegstate_bgc(cPtr, false);
  }

  public void setM_sois(soistate_bgc value) {
    temcoreJNI.BgcData_m_sois_set(swigCPtr, this, soistate_bgc.getCPtr(value), value);
  }

  public soistate_bgc getM_sois() {
    long cPtr = temcoreJNI.BgcData_m_sois_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soistate_bgc(cPtr, false);
  }

  public void setM_vegd(vegdiag_bgc value) {
    temcoreJNI.BgcData_m_vegd_set(swigCPtr, this, vegdiag_bgc.getCPtr(value), value);
  }

  public vegdiag_bgc getM_vegd() {
    long cPtr = temcoreJNI.BgcData_m_vegd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegdiag_bgc(cPtr, false);
  }

  public void setM_soid(soidiag_bgc value) {
    temcoreJNI.BgcData_m_soid_set(swigCPtr, this, soidiag_bgc.getCPtr(value), value);
  }

  public soidiag_bgc getM_soid() {
    long cPtr = temcoreJNI.BgcData_m_soid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soidiag_bgc(cPtr, false);
  }

  public void setM_l2a(lnd2atm_bgc value) {
    temcoreJNI.BgcData_m_l2a_set(swigCPtr, this, lnd2atm_bgc.getCPtr(value), value);
  }

  public lnd2atm_bgc getM_l2a() {
    long cPtr = temcoreJNI.BgcData_m_l2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new lnd2atm_bgc(cPtr, false);
  }

  public void setM_a2v(atm2veg_bgc value) {
    temcoreJNI.BgcData_m_a2v_set(swigCPtr, this, atm2veg_bgc.getCPtr(value), value);
  }

  public atm2veg_bgc getM_a2v() {
    long cPtr = temcoreJNI.BgcData_m_a2v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2veg_bgc(cPtr, false);
  }

  public void setM_v2a(veg2atm_bgc value) {
    temcoreJNI.BgcData_m_v2a_set(swigCPtr, this, veg2atm_bgc.getCPtr(value), value);
  }

  public veg2atm_bgc getM_v2a() {
    long cPtr = temcoreJNI.BgcData_m_v2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2atm_bgc(cPtr, false);
  }

  public void setM_v2soi(veg2soi_bgc value) {
    temcoreJNI.BgcData_m_v2soi_set(swigCPtr, this, veg2soi_bgc.getCPtr(value), value);
  }

  public veg2soi_bgc getM_v2soi() {
    long cPtr = temcoreJNI.BgcData_m_v2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2soi_bgc(cPtr, false);
  }

  public void setM_soi2v(soi2veg_bgc value) {
    temcoreJNI.BgcData_m_soi2v_set(swigCPtr, this, soi2veg_bgc.getCPtr(value), value);
  }

  public soi2veg_bgc getM_soi2v() {
    long cPtr = temcoreJNI.BgcData_m_soi2v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2veg_bgc(cPtr, false);
  }

  public void setM_v2v(veg2veg_bgc value) {
    temcoreJNI.BgcData_m_v2v_set(swigCPtr, this, veg2veg_bgc.getCPtr(value), value);
  }

  public veg2veg_bgc getM_v2v() {
    long cPtr = temcoreJNI.BgcData_m_v2v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2veg_bgc(cPtr, false);
  }

  public void setM_soi2l(soi2lnd_bgc value) {
    temcoreJNI.BgcData_m_soi2l_set(swigCPtr, this, soi2lnd_bgc.getCPtr(value), value);
  }

  public soi2lnd_bgc getM_soi2l() {
    long cPtr = temcoreJNI.BgcData_m_soi2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2lnd_bgc(cPtr, false);
  }

  public void setM_soi2a(soi2atm_bgc value) {
    temcoreJNI.BgcData_m_soi2a_set(swigCPtr, this, soi2atm_bgc.getCPtr(value), value);
  }

  public soi2atm_bgc getM_soi2a() {
    long cPtr = temcoreJNI.BgcData_m_soi2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2atm_bgc(cPtr, false);
  }

  public void setM_a2soi(atm2soi_bgc value) {
    temcoreJNI.BgcData_m_a2soi_set(swigCPtr, this, atm2soi_bgc.getCPtr(value), value);
  }

  public atm2soi_bgc getM_a2soi() {
    long cPtr = temcoreJNI.BgcData_m_a2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2soi_bgc(cPtr, false);
  }

  public void setM_soi2soi(soi2soi_bgc value) {
    temcoreJNI.BgcData_m_soi2soi_set(swigCPtr, this, soi2soi_bgc.getCPtr(value), value);
  }

  public soi2soi_bgc getM_soi2soi() {
    long cPtr = temcoreJNI.BgcData_m_soi2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2soi_bgc(cPtr, false);
  }

  public void setY_vegs(vegstate_bgc value) {
    temcoreJNI.BgcData_y_vegs_set(swigCPtr, this, vegstate_bgc.getCPtr(value), value);
  }

  public vegstate_bgc getY_vegs() {
    long cPtr = temcoreJNI.BgcData_y_vegs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegstate_bgc(cPtr, false);
  }

  public void setY_sois(soistate_bgc value) {
    temcoreJNI.BgcData_y_sois_set(swigCPtr, this, soistate_bgc.getCPtr(value), value);
  }

  public soistate_bgc getY_sois() {
    long cPtr = temcoreJNI.BgcData_y_sois_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soistate_bgc(cPtr, false);
  }

  public void setY_vegd(vegdiag_bgc value) {
    temcoreJNI.BgcData_y_vegd_set(swigCPtr, this, vegdiag_bgc.getCPtr(value), value);
  }

  public vegdiag_bgc getY_vegd() {
    long cPtr = temcoreJNI.BgcData_y_vegd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegdiag_bgc(cPtr, false);
  }

  public void setY_soid(soidiag_bgc value) {
    temcoreJNI.BgcData_y_soid_set(swigCPtr, this, soidiag_bgc.getCPtr(value), value);
  }

  public soidiag_bgc getY_soid() {
    long cPtr = temcoreJNI.BgcData_y_soid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soidiag_bgc(cPtr, false);
  }

  public void setY_l2a(lnd2atm_bgc value) {
    temcoreJNI.BgcData_y_l2a_set(swigCPtr, this, lnd2atm_bgc.getCPtr(value), value);
  }

  public lnd2atm_bgc getY_l2a() {
    long cPtr = temcoreJNI.BgcData_y_l2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new lnd2atm_bgc(cPtr, false);
  }

  public void setY_a2v(atm2veg_bgc value) {
    temcoreJNI.BgcData_y_a2v_set(swigCPtr, this, atm2veg_bgc.getCPtr(value), value);
  }

  public atm2veg_bgc getY_a2v() {
    long cPtr = temcoreJNI.BgcData_y_a2v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2veg_bgc(cPtr, false);
  }

  public void setY_v2a(veg2atm_bgc value) {
    temcoreJNI.BgcData_y_v2a_set(swigCPtr, this, veg2atm_bgc.getCPtr(value), value);
  }

  public veg2atm_bgc getY_v2a() {
    long cPtr = temcoreJNI.BgcData_y_v2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2atm_bgc(cPtr, false);
  }

  public void setY_v2soi(veg2soi_bgc value) {
    temcoreJNI.BgcData_y_v2soi_set(swigCPtr, this, veg2soi_bgc.getCPtr(value), value);
  }

  public veg2soi_bgc getY_v2soi() {
    long cPtr = temcoreJNI.BgcData_y_v2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2soi_bgc(cPtr, false);
  }

  public void setY_soi2v(soi2veg_bgc value) {
    temcoreJNI.BgcData_y_soi2v_set(swigCPtr, this, soi2veg_bgc.getCPtr(value), value);
  }

  public soi2veg_bgc getY_soi2v() {
    long cPtr = temcoreJNI.BgcData_y_soi2v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2veg_bgc(cPtr, false);
  }

  public void setY_v2v(veg2veg_bgc value) {
    temcoreJNI.BgcData_y_v2v_set(swigCPtr, this, veg2veg_bgc.getCPtr(value), value);
  }

  public veg2veg_bgc getY_v2v() {
    long cPtr = temcoreJNI.BgcData_y_v2v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2veg_bgc(cPtr, false);
  }

  public void setY_soi2l(soi2lnd_bgc value) {
    temcoreJNI.BgcData_y_soi2l_set(swigCPtr, this, soi2lnd_bgc.getCPtr(value), value);
  }

  public soi2lnd_bgc getY_soi2l() {
    long cPtr = temcoreJNI.BgcData_y_soi2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2lnd_bgc(cPtr, false);
  }

  public void setY_soi2a(soi2atm_bgc value) {
    temcoreJNI.BgcData_y_soi2a_set(swigCPtr, this, soi2atm_bgc.getCPtr(value), value);
  }

  public soi2atm_bgc getY_soi2a() {
    long cPtr = temcoreJNI.BgcData_y_soi2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2atm_bgc(cPtr, false);
  }

  public void setY_a2soi(atm2soi_bgc value) {
    temcoreJNI.BgcData_y_a2soi_set(swigCPtr, this, atm2soi_bgc.getCPtr(value), value);
  }

  public atm2soi_bgc getY_a2soi() {
    long cPtr = temcoreJNI.BgcData_y_a2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2soi_bgc(cPtr, false);
  }

  public void setY_soi2soi(soi2soi_bgc value) {
    temcoreJNI.BgcData_y_soi2soi_set(swigCPtr, this, soi2soi_bgc.getCPtr(value), value);
  }

  public soi2soi_bgc getY_soi2soi() {
    long cPtr = temcoreJNI.BgcData_y_soi2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2soi_bgc(cPtr, false);
  }

  public void setToptque(SWIGTYPE_p_dequeT_double_t value) {
    temcoreJNI.BgcData_toptque_set(swigCPtr, this, SWIGTYPE_p_dequeT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_dequeT_double_t getToptque() {
    return new SWIGTYPE_p_dequeT_double_t(temcoreJNI.BgcData_toptque_get(swigCPtr, this), true);
  }

  public void setUnleafmxque(SWIGTYPE_p_dequeT_double_t value) {
    temcoreJNI.BgcData_unleafmxque_set(swigCPtr, this, SWIGTYPE_p_dequeT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_dequeT_double_t getUnleafmxque() {
    return new SWIGTYPE_p_dequeT_double_t(temcoreJNI.BgcData_unleafmxque_get(swigCPtr, this), true);
  }

  public void setFoliagemx(double value) {
    temcoreJNI.BgcData_foliagemx_set(swigCPtr, this, value);
  }

  public double getFoliagemx() {
    return temcoreJNI.BgcData_foliagemx_get(swigCPtr, this);
  }

  public void setTopt(double value) {
    temcoreJNI.BgcData_topt_set(swigCPtr, this, value);
  }

  public double getTopt() {
    return temcoreJNI.BgcData_topt_get(swigCPtr, this);
  }

  public void setUnleafmx(double value) {
    temcoreJNI.BgcData_unleafmx_set(swigCPtr, this, value);
  }

  public double getUnleafmx() {
    return temcoreJNI.BgcData_unleafmx_get(swigCPtr, this);
  }

  public void setPrvunleafmx(double value) {
    temcoreJNI.BgcData_prvunleafmx_set(swigCPtr, this, value);
  }

  public double getPrvunleafmx() {
    return temcoreJNI.BgcData_prvunleafmx_get(swigCPtr, this);
  }

  public void setPrvtopt(double value) {
    temcoreJNI.BgcData_prvtopt_set(swigCPtr, this, value);
  }

  public double getPrvtopt() {
    return temcoreJNI.BgcData_prvtopt_get(swigCPtr, this);
  }

  public void setC2n(double value) {
    temcoreJNI.BgcData_c2n_set(swigCPtr, this, value);
  }

  public double getC2n() {
    return temcoreJNI.BgcData_c2n_get(swigCPtr, this);
  }

  public void setKdfib(double value) {
    temcoreJNI.BgcData_kdfib_set(swigCPtr, this, value);
  }

  public double getKdfib() {
    return temcoreJNI.BgcData_kdfib_get(swigCPtr, this);
  }

  public void setKdhum(double value) {
    temcoreJNI.BgcData_kdhum_set(swigCPtr, this, value);
  }

  public double getKdhum() {
    return temcoreJNI.BgcData_kdhum_get(swigCPtr, this);
  }

  public void setKdmin(double value) {
    temcoreJNI.BgcData_kdmin_set(swigCPtr, this, value);
  }

  public double getKdmin() {
    return temcoreJNI.BgcData_kdmin_get(swigCPtr, this);
  }

  public void setKdslow(double value) {
    temcoreJNI.BgcData_kdslow_set(swigCPtr, this, value);
  }

  public double getKdslow() {
    return temcoreJNI.BgcData_kdslow_get(swigCPtr, this);
  }

  public void init() {
    temcoreJNI.BgcData_init(swigCPtr, this);
  }

  public void beginOfMonth(int curmrind) {
    temcoreJNI.BgcData_beginOfMonth(swigCPtr, this, curmrind);
  }

  public void beginOfYear() {
    temcoreJNI.BgcData_beginOfYear(swigCPtr, this);
  }

  public void endOfMonth(int currmind) {
    temcoreJNI.BgcData_endOfMonth(swigCPtr, this, currmind);
  }

  public void endOfYear(double cnsoil) {
    temcoreJNI.BgcData_endOfYear(swigCPtr, this, cnsoil);
  }

  public void setEnvData(EnvData edp) {
    temcoreJNI.BgcData_setEnvData(swigCPtr, this, EnvData.getCPtr(edp), edp);
  }

  public void setBaseline(int value) {
    temcoreJNI.BgcData_baseline_set(swigCPtr, this, value);
  }

  public int getBaseline() {
    return temcoreJNI.BgcData_baseline_get(swigCPtr, this);
  }

  public void setNfeed(int value) {
    temcoreJNI.BgcData_nfeed_set(swigCPtr, this, value);
  }

  public int getNfeed() {
    return temcoreJNI.BgcData_nfeed_get(swigCPtr, this);
  }

  public void setAvlnflg(int value) {
    temcoreJNI.BgcData_avlnflg_set(swigCPtr, this, value);
  }

  public int getAvlnflg() {
    return temcoreJNI.BgcData_avlnflg_get(swigCPtr, this);
  }

  public void setRd(RegionData value) {
    temcoreJNI.BgcData_rd_set(swigCPtr, this, RegionData.getCPtr(value), value);
  }

  public RegionData getRd() {
    long cPtr = temcoreJNI.BgcData_rd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RegionData(cPtr, false);
  }

  public void setGd(GridData value) {
    temcoreJNI.BgcData_gd_set(swigCPtr, this, GridData.getCPtr(value), value);
  }

  public GridData getGd() {
    long cPtr = temcoreJNI.BgcData_gd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GridData(cPtr, false);
  }

  public void setCd(CohortData value) {
    temcoreJNI.BgcData_cd_set(swigCPtr, this, CohortData.getCPtr(value), value);
  }

  public CohortData getCd() {
    long cPtr = temcoreJNI.BgcData_cd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CohortData(cPtr, false);
  }

}
