/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class CohortData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CohortData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CohortData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_CohortData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CohortData() {
    this(temcoreJNI.new_CohortData(), true);
  }

  public void setGrdid(int value) {
    temcoreJNI.CohortData_grdid_set(swigCPtr, this, value);
  }

  public int getGrdid() {
    return temcoreJNI.CohortData_grdid_get(swigCPtr, this);
  }

  public void setClmid(int value) {
    temcoreJNI.CohortData_clmid_set(swigCPtr, this, value);
  }

  public int getClmid() {
    return temcoreJNI.CohortData_clmid_get(swigCPtr, this);
  }

  public void setTrchtid(int value) {
    temcoreJNI.CohortData_trchtid_set(swigCPtr, this, value);
  }

  public int getTrchtid() {
    return temcoreJNI.CohortData_trchtid_get(swigCPtr, this);
  }

  public void setEqchtid(int value) {
    temcoreJNI.CohortData_eqchtid_set(swigCPtr, this, value);
  }

  public int getEqchtid() {
    return temcoreJNI.CohortData_eqchtid_get(swigCPtr, this);
  }

  public void setSpchtid(int value) {
    temcoreJNI.CohortData_spchtid_set(swigCPtr, this, value);
  }

  public int getSpchtid() {
    return temcoreJNI.CohortData_spchtid_get(swigCPtr, this);
  }

  public void setScchtid(int value) {
    temcoreJNI.CohortData_scchtid_set(swigCPtr, this, value);
  }

  public int getScchtid() {
    return temcoreJNI.CohortData_scchtid_get(swigCPtr, this);
  }

  public void setReschtid(int value) {
    temcoreJNI.CohortData_reschtid_set(swigCPtr, this, value);
  }

  public int getReschtid() {
    return temcoreJNI.CohortData_reschtid_get(swigCPtr, this);
  }

  public void setDrgtype(int value) {
    temcoreJNI.CohortData_drgtype_set(swigCPtr, this, value);
  }

  public int getDrgtype() {
    return temcoreJNI.CohortData_drgtype_get(swigCPtr, this);
  }

  public void setVegtype(int value) {
    temcoreJNI.CohortData_vegtype_set(swigCPtr, this, value);
  }

  public int getVegtype() {
    return temcoreJNI.CohortData_vegtype_get(swigCPtr, this);
  }

  public void setTrfireyear(int[] value) {
    temcoreJNI.CohortData_trfireyear_set(swigCPtr, this, value);
  }

  public int[] getTrfireyear() {
    return temcoreJNI.CohortData_trfireyear_get(swigCPtr, this);
  }

  public void setTrseason(int[] value) {
    temcoreJNI.CohortData_trseason_set(swigCPtr, this, value);
  }

  public int[] getTrseason() {
    return temcoreJNI.CohortData_trseason_get(swigCPtr, this);
  }

  public void setTrseverity(int[] value) {
    temcoreJNI.CohortData_trseverity_set(swigCPtr, this, value);
  }

  public int[] getTrseverity() {
    return temcoreJNI.CohortData_trseverity_get(swigCPtr, this);
  }

  public void setSpfireyear(int[] value) {
    temcoreJNI.CohortData_spfireyear_set(swigCPtr, this, value);
  }

  public int[] getSpfireyear() {
    return temcoreJNI.CohortData_spfireyear_get(swigCPtr, this);
  }

  public void setSpseason(int[] value) {
    temcoreJNI.CohortData_spseason_set(swigCPtr, this, value);
  }

  public int[] getSpseason() {
    return temcoreJNI.CohortData_spseason_get(swigCPtr, this);
  }

  public void setSpseverity(int[] value) {
    temcoreJNI.CohortData_spseverity_set(swigCPtr, this, value);
  }

  public int[] getSpseverity() {
    return temcoreJNI.CohortData_spseverity_get(swigCPtr, this);
  }

}
