/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class CohortLookup {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CohortLookup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CohortLookup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_CohortLookup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CohortLookup() {
    this(temcoreJNI.new_CohortLookup(), true);
  }

  public void init() {
    temcoreJNI.CohortLookup_init(swigCPtr, this);
  }

  public void setKc(float[] value) {
    temcoreJNI.CohortLookup_kc_set(swigCPtr, this, value);
  }

  public float[] getKc() {
    return temcoreJNI.CohortLookup_kc_get(swigCPtr, this);
  }

  public void setKi(float[] value) {
    temcoreJNI.CohortLookup_ki_set(swigCPtr, this, value);
  }

  public float[] getKi() {
    return temcoreJNI.CohortLookup_ki_get(swigCPtr, this);
  }

  public void setGva(float[] value) {
    temcoreJNI.CohortLookup_gva_set(swigCPtr, this, value);
  }

  public float[] getGva() {
    return temcoreJNI.CohortLookup_gva_get(swigCPtr, this);
  }

  public void setTmin(float[] value) {
    temcoreJNI.CohortLookup_tmin_set(swigCPtr, this, value);
  }

  public float[] getTmin() {
    return temcoreJNI.CohortLookup_tmin_get(swigCPtr, this);
  }

  public void setToptmin(float[] value) {
    temcoreJNI.CohortLookup_toptmin_set(swigCPtr, this, value);
  }

  public float[] getToptmin() {
    return temcoreJNI.CohortLookup_toptmin_get(swigCPtr, this);
  }

  public void setToptmax(float[] value) {
    temcoreJNI.CohortLookup_toptmax_set(swigCPtr, this, value);
  }

  public float[] getToptmax() {
    return temcoreJNI.CohortLookup_toptmax_get(swigCPtr, this);
  }

  public void setTmax(float[] value) {
    temcoreJNI.CohortLookup_tmax_set(swigCPtr, this, value);
  }

  public float[] getTmax() {
    return temcoreJNI.CohortLookup_tmax_get(swigCPtr, this);
  }

  public void setRaq10a0(float[] value) {
    temcoreJNI.CohortLookup_raq10a0_set(swigCPtr, this, value);
  }

  public float[] getRaq10a0() {
    return temcoreJNI.CohortLookup_raq10a0_get(swigCPtr, this);
  }

  public void setRaq10a1(float[] value) {
    temcoreJNI.CohortLookup_raq10a1_set(swigCPtr, this, value);
  }

  public float[] getRaq10a1() {
    return temcoreJNI.CohortLookup_raq10a1_get(swigCPtr, this);
  }

  public void setRaq10a2(float[] value) {
    temcoreJNI.CohortLookup_raq10a2_set(swigCPtr, this, value);
  }

  public float[] getRaq10a2() {
    return temcoreJNI.CohortLookup_raq10a2_get(swigCPtr, this);
  }

  public void setRaq10a3(float[] value) {
    temcoreJNI.CohortLookup_raq10a3_set(swigCPtr, this, value);
  }

  public float[] getRaq10a3() {
    return temcoreJNI.CohortLookup_raq10a3_get(swigCPtr, this);
  }

  public void setKn1(float[] value) {
    temcoreJNI.CohortLookup_kn1_set(swigCPtr, this, value);
  }

  public float[] getKn1() {
    return temcoreJNI.CohortLookup_kn1_get(swigCPtr, this);
  }

  public void setLabncon(float[] value) {
    temcoreJNI.CohortLookup_labncon_set(swigCPtr, this, value);
  }

  public float[] getLabncon() {
    return temcoreJNI.CohortLookup_labncon_get(swigCPtr, this);
  }

  public void setLeafmxc(float[] value) {
    temcoreJNI.CohortLookup_leafmxc_set(swigCPtr, this, value);
  }

  public float[] getLeafmxc() {
    return temcoreJNI.CohortLookup_leafmxc_get(swigCPtr, this);
  }

  public void setKleafc(float[] value) {
    temcoreJNI.CohortLookup_kleafc_set(swigCPtr, this, value);
  }

  public float[] getKleafc() {
    return temcoreJNI.CohortLookup_kleafc_get(swigCPtr, this);
  }

  public void setSla(float[] value) {
    temcoreJNI.CohortLookup_sla_set(swigCPtr, this, value);
  }

  public float[] getSla() {
    return temcoreJNI.CohortLookup_sla_get(swigCPtr, this);
  }

  public void setCov(float[] value) {
    temcoreJNI.CohortLookup_cov_set(swigCPtr, this, value);
  }

  public float[] getCov() {
    return temcoreJNI.CohortLookup_cov_get(swigCPtr, this);
  }

  public void setFpcmax(float[] value) {
    temcoreJNI.CohortLookup_fpcmax_set(swigCPtr, this, value);
  }

  public float[] getFpcmax() {
    return temcoreJNI.CohortLookup_fpcmax_get(swigCPtr, this);
  }

  public void setAbv2totmass(float[] value) {
    temcoreJNI.CohortLookup_abv2totmass_set(swigCPtr, this, value);
  }

  public float[] getAbv2totmass() {
    return temcoreJNI.CohortLookup_abv2totmass_get(swigCPtr, this);
  }

  public void setMaturefoliagemin(float[] value) {
    temcoreJNI.CohortLookup_maturefoliagemin_set(swigCPtr, this, value);
  }

  public float[] getMaturefoliagemin() {
    return temcoreJNI.CohortLookup_maturefoliagemin_get(swigCPtr, this);
  }

  public void setInitleafmx(float[] value) {
    temcoreJNI.CohortLookup_initleafmx_set(swigCPtr, this, value);
  }

  public float[] getInitleafmx() {
    return temcoreJNI.CohortLookup_initleafmx_get(swigCPtr, this);
  }

  public void setC2nmin(float[] value) {
    temcoreJNI.CohortLookup_c2nmin_set(swigCPtr, this, value);
  }

  public float[] getC2nmin() {
    return temcoreJNI.CohortLookup_c2nmin_get(swigCPtr, this);
  }

  public void setCnmin(float[] value) {
    temcoreJNI.CohortLookup_cnmin_set(swigCPtr, this, value);
  }

  public float[] getCnmin() {
    return temcoreJNI.CohortLookup_cnmin_get(swigCPtr, this);
  }

  public void setC2na(float[] value) {
    temcoreJNI.CohortLookup_c2na_set(swigCPtr, this, value);
  }

  public float[] getC2na() {
    return temcoreJNI.CohortLookup_c2na_get(swigCPtr, this);
  }

  public void setC2nb(float[] value) {
    temcoreJNI.CohortLookup_c2nb_set(swigCPtr, this, value);
  }

  public float[] getC2nb() {
    return temcoreJNI.CohortLookup_c2nb_get(swigCPtr, this);
  }

  public void setInitcneven(float[] value) {
    temcoreJNI.CohortLookup_initcneven_set(swigCPtr, this, value);
  }

  public float[] getInitcneven() {
    return temcoreJNI.CohortLookup_initcneven_get(swigCPtr, this);
  }

  public void setMinleaf(float[] value) {
    temcoreJNI.CohortLookup_minleaf_set(swigCPtr, this, value);
  }

  public float[] getMinleaf() {
    return temcoreJNI.CohortLookup_minleaf_get(swigCPtr, this);
  }

  public void setAleaf(float[] value) {
    temcoreJNI.CohortLookup_aleaf_set(swigCPtr, this, value);
  }

  public float[] getAleaf() {
    return temcoreJNI.CohortLookup_aleaf_get(swigCPtr, this);
  }

  public void setBleaf(float[] value) {
    temcoreJNI.CohortLookup_bleaf_set(swigCPtr, this, value);
  }

  public float[] getBleaf() {
    return temcoreJNI.CohortLookup_bleaf_get(swigCPtr, this);
  }

  public void setCleaf(float[] value) {
    temcoreJNI.CohortLookup_cleaf_set(swigCPtr, this, value);
  }

  public float[] getCleaf() {
    return temcoreJNI.CohortLookup_cleaf_get(swigCPtr, this);
  }

  public void setM1(float[] value) {
    temcoreJNI.CohortLookup_m1_set(swigCPtr, this, value);
  }

  public float[] getM1() {
    return temcoreJNI.CohortLookup_m1_get(swigCPtr, this);
  }

  public void setM2(float[] value) {
    temcoreJNI.CohortLookup_m2_set(swigCPtr, this, value);
  }

  public float[] getM2() {
    return temcoreJNI.CohortLookup_m2_get(swigCPtr, this);
  }

  public void setM3(float[] value) {
    temcoreJNI.CohortLookup_m3_set(swigCPtr, this, value);
  }

  public float[] getM3() {
    return temcoreJNI.CohortLookup_m3_get(swigCPtr, this);
  }

  public void setM4(float[] value) {
    temcoreJNI.CohortLookup_m4_set(swigCPtr, this, value);
  }

  public float[] getM4() {
    return temcoreJNI.CohortLookup_m4_get(swigCPtr, this);
  }

  public void setAlbvisnir(float[] value) {
    temcoreJNI.CohortLookup_albvisnir_set(swigCPtr, this, value);
  }

  public float[] getAlbvisnir() {
    return temcoreJNI.CohortLookup_albvisnir_get(swigCPtr, this);
  }

  public void setGl_bl(float[] value) {
    temcoreJNI.CohortLookup_gl_bl_set(swigCPtr, this, value);
  }

  public float[] getGl_bl() {
    return temcoreJNI.CohortLookup_gl_bl_get(swigCPtr, this);
  }

  public void setGl_c(float[] value) {
    temcoreJNI.CohortLookup_gl_c_set(swigCPtr, this, value);
  }

  public float[] getGl_c() {
    return temcoreJNI.CohortLookup_gl_c_get(swigCPtr, this);
  }

  public void setGlmax(float[] value) {
    temcoreJNI.CohortLookup_glmax_set(swigCPtr, this, value);
  }

  public float[] getGlmax() {
    return temcoreJNI.CohortLookup_glmax_get(swigCPtr, this);
  }

  public void setEr(float[] value) {
    temcoreJNI.CohortLookup_er_set(swigCPtr, this, value);
  }

  public float[] getEr() {
    return temcoreJNI.CohortLookup_er_get(swigCPtr, this);
  }

  public void setIrcoef(float[] value) {
    temcoreJNI.CohortLookup_ircoef_set(swigCPtr, this, value);
  }

  public float[] getIrcoef() {
    return temcoreJNI.CohortLookup_ircoef_get(swigCPtr, this);
  }

  public void setIscoef(float[] value) {
    temcoreJNI.CohortLookup_iscoef_set(swigCPtr, this, value);
  }

  public float[] getIscoef() {
    return temcoreJNI.CohortLookup_iscoef_get(swigCPtr, this);
  }

  public void setVpd_open(float[] value) {
    temcoreJNI.CohortLookup_vpd_open_set(swigCPtr, this, value);
  }

  public float[] getVpd_open() {
    return temcoreJNI.CohortLookup_vpd_open_get(swigCPtr, this);
  }

  public void setVpd_close(float[] value) {
    temcoreJNI.CohortLookup_vpd_close_set(swigCPtr, this, value);
  }

  public float[] getVpd_close() {
    return temcoreJNI.CohortLookup_vpd_close_get(swigCPtr, this);
  }

  public void setLwp_open(float[] value) {
    temcoreJNI.CohortLookup_lwp_open_set(swigCPtr, this, value);
  }

  public float[] getLwp_open() {
    return temcoreJNI.CohortLookup_lwp_open_get(swigCPtr, this);
  }

  public void setLwp_close(float[] value) {
    temcoreJNI.CohortLookup_lwp_close_set(swigCPtr, this, value);
  }

  public float[] getLwp_close() {
    return temcoreJNI.CohortLookup_lwp_close_get(swigCPtr, this);
  }

  public void setAll2prj(float[] value) {
    temcoreJNI.CohortLookup_all2prj_set(swigCPtr, this, value);
  }

  public float[] getAll2prj() {
    return temcoreJNI.CohortLookup_all2prj_get(swigCPtr, this);
  }

  public void setPpfd50(float[] value) {
    temcoreJNI.CohortLookup_ppfd50_set(swigCPtr, this, value);
  }

  public float[] getPpfd50() {
    return temcoreJNI.CohortLookup_ppfd50_get(swigCPtr, this);
  }

  public void setRhq10(float[] value) {
    temcoreJNI.CohortLookup_rhq10_set(swigCPtr, this, value);
  }

  public float[] getRhq10() {
    return temcoreJNI.CohortLookup_rhq10_get(swigCPtr, this);
  }

  public void setKn2(float[] value) {
    temcoreJNI.CohortLookup_kn2_set(swigCPtr, this, value);
  }

  public float[] getKn2() {
    return temcoreJNI.CohortLookup_kn2_get(swigCPtr, this);
  }

  public void setMoistmin(float[] value) {
    temcoreJNI.CohortLookup_moistmin_set(swigCPtr, this, value);
  }

  public float[] getMoistmin() {
    return temcoreJNI.CohortLookup_moistmin_get(swigCPtr, this);
  }

  public void setMoistopt(float[] value) {
    temcoreJNI.CohortLookup_moistopt_set(swigCPtr, this, value);
  }

  public float[] getMoistopt() {
    return temcoreJNI.CohortLookup_moistopt_get(swigCPtr, this);
  }

  public void setMoistmax(float[] value) {
    temcoreJNI.CohortLookup_moistmax_set(swigCPtr, this, value);
  }

  public float[] getMoistmax() {
    return temcoreJNI.CohortLookup_moistmax_get(swigCPtr, this);
  }

  public void setPropftos(float[] value) {
    temcoreJNI.CohortLookup_propftos_set(swigCPtr, this, value);
  }

  public float[] getPropftos() {
    return temcoreJNI.CohortLookup_propftos_get(swigCPtr, this);
  }

  public void setNloss(float[] value) {
    temcoreJNI.CohortLookup_nloss_set(swigCPtr, this, value);
  }

  public float[] getNloss() {
    return temcoreJNI.CohortLookup_nloss_get(swigCPtr, this);
  }

  public void setLcclnc(float[] value) {
    temcoreJNI.CohortLookup_lcclnc_set(swigCPtr, this, value);
  }

  public float[] getLcclnc() {
    return temcoreJNI.CohortLookup_lcclnc_get(swigCPtr, this);
  }

  public void setCnsoil(float[] value) {
    temcoreJNI.CohortLookup_cnsoil_set(swigCPtr, this, value);
  }

  public float[] getCnsoil() {
    return temcoreJNI.CohortLookup_cnsoil_get(swigCPtr, this);
  }

  public void setKdcfib(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_kdcfib_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getKdcfib() {
    long cPtr = temcoreJNI.CohortLookup_kdcfib_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setKdchum(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_kdchum_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getKdchum() {
    long cPtr = temcoreJNI.CohortLookup_kdchum_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setKdcmin(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_kdcmin_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getKdcmin() {
    long cPtr = temcoreJNI.CohortLookup_kdcmin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setKdcslow(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_kdcslow_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getKdcslow() {
    long cPtr = temcoreJNI.CohortLookup_kdcslow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setNup(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_nup_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getNup() {
    long cPtr = temcoreJNI.CohortLookup_nup_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setCmax(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_cmax_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getCmax() {
    long cPtr = temcoreJNI.CohortLookup_cmax_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setNmax(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_nmax_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getNmax() {
    long cPtr = temcoreJNI.CohortLookup_nmax_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setCfall(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_cfall_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getCfall() {
    long cPtr = temcoreJNI.CohortLookup_cfall_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setNfall(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_nfall_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getNfall() {
    long cPtr = temcoreJNI.CohortLookup_nfall_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setKra(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_kra_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getKra() {
    long cPtr = temcoreJNI.CohortLookup_kra_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setKrb(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_krb_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getKrb() {
    long cPtr = temcoreJNI.CohortLookup_krb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setInitvegc(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_initvegc_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getInitvegc() {
    long cPtr = temcoreJNI.CohortLookup_initvegc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setInitstrn(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_initstrn_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getInitstrn() {
    long cPtr = temcoreJNI.CohortLookup_initstrn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setInitston(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_initston_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getInitston() {
    long cPtr = temcoreJNI.CohortLookup_initston_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setInitsolc(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_initsolc_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getInitsolc() {
    long cPtr = temcoreJNI.CohortLookup_initsolc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setInitsoln(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_initsoln_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getInitsoln() {
    long cPtr = temcoreJNI.CohortLookup_initsoln_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setInitavln(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_initavln_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getInitavln() {
    long cPtr = temcoreJNI.CohortLookup_initavln_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setFrprod_frac(SWIGTYPE_p_a_MAX_FR_INT__float value) {
    temcoreJNI.CohortLookup_frprod_frac_set(swigCPtr, this, SWIGTYPE_p_a_MAX_FR_INT__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_FR_INT__float getFrprod_frac() {
    long cPtr = temcoreJNI.CohortLookup_frprod_frac_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_FR_INT__float(cPtr, false);
  }

  public void setRootza(float[] value) {
    temcoreJNI.CohortLookup_rootza_set(swigCPtr, this, value);
  }

  public float[] getRootza() {
    return temcoreJNI.CohortLookup_rootza_get(swigCPtr, this);
  }

  public void setRootzb(float[] value) {
    temcoreJNI.CohortLookup_rootzb_set(swigCPtr, this, value);
  }

  public float[] getRootzb() {
    return temcoreJNI.CohortLookup_rootzb_get(swigCPtr, this);
  }

  public void setRootzc(float[] value) {
    temcoreJNI.CohortLookup_rootzc_set(swigCPtr, this, value);
  }

  public float[] getRootzc() {
    return temcoreJNI.CohortLookup_rootzc_get(swigCPtr, this);
  }

  public void setMinrootz(float[] value) {
    temcoreJNI.CohortLookup_minrootz_set(swigCPtr, this, value);
  }

  public float[] getMinrootz() {
    return temcoreJNI.CohortLookup_minrootz_get(swigCPtr, this);
  }

  public void setRootmass(float[] value) {
    temcoreJNI.CohortLookup_rootmass_set(swigCPtr, this, value);
  }

  public float[] getRootmass() {
    return temcoreJNI.CohortLookup_rootmass_get(swigCPtr, this);
  }

  public void setRootbeta(float[] value) {
    temcoreJNI.CohortLookup_rootbeta_set(swigCPtr, this, value);
  }

  public float[] getRootbeta() {
    return temcoreJNI.CohortLookup_rootbeta_get(swigCPtr, this);
  }

  public void setRootdp4infil(float[] value) {
    temcoreJNI.CohortLookup_rootdp4infil_set(swigCPtr, this, value);
  }

  public float[] getRootdp4infil() {
    return temcoreJNI.CohortLookup_rootdp4infil_get(swigCPtr, this);
  }

  public void setRichardl(float[] value) {
    temcoreJNI.CohortLookup_richardl_set(swigCPtr, this, value);
  }

  public float[] getRichardl() {
    return temcoreJNI.CohortLookup_richardl_get(swigCPtr, this);
  }

  public void setRootdp4gpp(float[] value) {
    temcoreJNI.CohortLookup_rootdp4gpp_set(swigCPtr, this, value);
  }

  public float[] getRootdp4gpp() {
    return temcoreJNI.CohortLookup_rootdp4gpp_get(swigCPtr, this);
  }

  public void setMaxmossthick(float[] value) {
    temcoreJNI.CohortLookup_maxmossthick_set(swigCPtr, this, value);
  }

  public float[] getMaxmossthick() {
    return temcoreJNI.CohortLookup_maxmossthick_get(swigCPtr, this);
  }

  public void setAbvltrr2t(float[] value) {
    temcoreJNI.CohortLookup_abvltrr2t_set(swigCPtr, this, value);
  }

  public float[] getAbvltrr2t() {
    return temcoreJNI.CohortLookup_abvltrr2t_get(swigCPtr, this);
  }

  public void setBlwltrr2t(float[] value) {
    temcoreJNI.CohortLookup_blwltrr2t_set(swigCPtr, this, value);
  }

  public float[] getBlwltrr2t() {
    return temcoreJNI.CohortLookup_blwltrr2t_get(swigCPtr, this);
  }

  public void setEnvlai(SWIGTYPE_p_a_MINY__float value) {
    temcoreJNI.CohortLookup_envlai_set(swigCPtr, this, SWIGTYPE_p_a_MINY__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MINY__float getEnvlai() {
    long cPtr = temcoreJNI.CohortLookup_envlai_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MINY__float(cPtr, false);
  }

  public void setMossthick(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_mossthick_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getMossthick() {
    long cPtr = temcoreJNI.CohortLookup_mossthick_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setFibthick(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_fibthick_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getFibthick() {
    long cPtr = temcoreJNI.CohortLookup_fibthick_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setHumthick(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_humthick_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getHumthick() {
    long cPtr = temcoreJNI.CohortLookup_humthick_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setCoefshlwa(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_coefshlwa_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getCoefshlwa() {
    long cPtr = temcoreJNI.CohortLookup_coefshlwa_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setCoefshlwb(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_coefshlwb_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getCoefshlwb() {
    long cPtr = temcoreJNI.CohortLookup_coefshlwb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setCoefdeepa(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_coefdeepa_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getCoefdeepa() {
    long cPtr = temcoreJNI.CohortLookup_coefdeepa_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setCoefdeepb(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_coefdeepb_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getCoefdeepb() {
    long cPtr = temcoreJNI.CohortLookup_coefdeepb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setCoefminea(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_coefminea_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getCoefminea() {
    long cPtr = temcoreJNI.CohortLookup_coefminea_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setCoefmineb(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_coefmineb_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getCoefmineb() {
    long cPtr = temcoreJNI.CohortLookup_coefmineb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setLtrfalratiom2f(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_ltrfalratiom2f_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getLtrfalratiom2f() {
    long cPtr = temcoreJNI.CohortLookup_ltrfalratiom2f_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setLtrfalratioh2f(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_ltrfalratioh2f_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getLtrfalratioh2f() {
    long cPtr = temcoreJNI.CohortLookup_ltrfalratioh2f_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setFsoma(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_fsoma_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getFsoma() {
    long cPtr = temcoreJNI.CohortLookup_fsoma_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setFsompr(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_fsompr_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getFsompr() {
    long cPtr = temcoreJNI.CohortLookup_fsompr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setFsomcr(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_fsomcr_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getFsomcr() {
    long cPtr = temcoreJNI.CohortLookup_fsomcr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setSom2co2(SWIGTYPE_p_a_MAX_VEG_TYPE__float value) {
    temcoreJNI.CohortLookup_som2co2_set(swigCPtr, this, SWIGTYPE_p_a_MAX_VEG_TYPE__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_VEG_TYPE__float getSom2co2() {
    long cPtr = temcoreJNI.CohortLookup_som2co2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_VEG_TYPE__float(cPtr, false);
  }

  public void setMinthick(float[] value) {
    temcoreJNI.CohortLookup_minthick_set(swigCPtr, this, value);
  }

  public float[] getMinthick() {
    return temcoreJNI.CohortLookup_minthick_get(swigCPtr, this);
  }

  public void setMintype(int[] value) {
    temcoreJNI.CohortLookup_mintype_set(swigCPtr, this, value);
  }

  public int[] getMintype() {
    return temcoreJNI.CohortLookup_mintype_get(swigCPtr, this);
  }

  public void setPsimax(float[] value) {
    temcoreJNI.CohortLookup_psimax_set(swigCPtr, this, value);
  }

  public float[] getPsimax() {
    return temcoreJNI.CohortLookup_psimax_get(swigCPtr, this);
  }

  public void setEvapmin(float[] value) {
    temcoreJNI.CohortLookup_evapmin_set(swigCPtr, this, value);
  }

  public float[] getEvapmin() {
    return temcoreJNI.CohortLookup_evapmin_get(swigCPtr, this);
  }

  public void setDs(float[] value) {
    temcoreJNI.CohortLookup_Ds_set(swigCPtr, this, value);
  }

  public float[] getDs() {
    return temcoreJNI.CohortLookup_Ds_get(swigCPtr, this);
  }

  public void setWs(float[] value) {
    temcoreJNI.CohortLookup_Ws_set(swigCPtr, this, value);
  }

  public float[] getWs() {
    return temcoreJNI.CohortLookup_Ws_get(swigCPtr, this);
  }

  public void setDsmax(float[] value) {
    temcoreJNI.CohortLookup_Dsmax_set(swigCPtr, this, value);
  }

  public float[] getDsmax() {
    return temcoreJNI.CohortLookup_Dsmax_get(swigCPtr, this);
  }

  public void setB_infilt(float[] value) {
    temcoreJNI.CohortLookup_b_infilt_set(swigCPtr, this, value);
  }

  public float[] getB_infilt() {
    return temcoreJNI.CohortLookup_b_infilt_get(swigCPtr, this);
  }

  public void setDrainmax(float[] value) {
    temcoreJNI.CohortLookup_drainmax_set(swigCPtr, this, value);
  }

  public float[] getDrainmax() {
    return temcoreJNI.CohortLookup_drainmax_get(swigCPtr, this);
  }

  public void setWfact(float[] value) {
    temcoreJNI.CohortLookup_wfact_set(swigCPtr, this, value);
  }

  public float[] getWfact() {
    return temcoreJNI.CohortLookup_wfact_get(swigCPtr, this);
  }

  public void setSnwdenmax(float[] value) {
    temcoreJNI.CohortLookup_snwdenmax_set(swigCPtr, this, value);
  }

  public float[] getSnwdenmax() {
    return temcoreJNI.CohortLookup_snwdenmax_get(swigCPtr, this);
  }

  public void setSnwalbmax(float[] value) {
    temcoreJNI.CohortLookup_snwalbmax_set(swigCPtr, this, value);
  }

  public float[] getSnwalbmax() {
    return temcoreJNI.CohortLookup_snwalbmax_get(swigCPtr, this);
  }

  public void setSnwalbmin(float[] value) {
    temcoreJNI.CohortLookup_snwalbmin_set(swigCPtr, this, value);
  }

  public float[] getSnwalbmin() {
    return temcoreJNI.CohortLookup_snwalbmin_get(swigCPtr, this);
  }

  public void setSnwdennew(float[] value) {
    temcoreJNI.CohortLookup_snwdennew_set(swigCPtr, this, value);
  }

  public float[] getSnwdennew() {
    return temcoreJNI.CohortLookup_snwdennew_get(swigCPtr, this);
  }

  public void setBurnthick_max(float[] value) {
    temcoreJNI.CohortLookup_burnthick_max_set(swigCPtr, this, value);
  }

  public float[] getBurnthick_max() {
    return temcoreJNI.CohortLookup_burnthick_max_get(swigCPtr, this);
  }

  public void setVegcombust(float[] value) {
    temcoreJNI.CohortLookup_vegcombust_set(swigCPtr, this, value);
  }

  public float[] getVegcombust() {
    return temcoreJNI.CohortLookup_vegcombust_get(swigCPtr, this);
  }

  public void setVegslash(float[] value) {
    temcoreJNI.CohortLookup_vegslash_set(swigCPtr, this, value);
  }

  public float[] getVegslash() {
    return temcoreJNI.CohortLookup_vegslash_get(swigCPtr, this);
  }

  public void setMatureage(float[] value) {
    temcoreJNI.CohortLookup_matureage_set(swigCPtr, this, value);
  }

  public float[] getMatureage() {
    return temcoreJNI.CohortLookup_matureage_get(swigCPtr, this);
  }

}
