/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class Controller {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Controller(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Controller obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_Controller(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Controller() {
    this(temcoreJNI.new_Controller(), true);
  }

  public void setControlfile(SWIGTYPE_p_string value) {
    temcoreJNI.Controller_controlfile_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getControlfile() {
    return new SWIGTYPE_p_string(temcoreJNI.Controller_controlfile_get(swigCPtr, this), true);
  }

  public void ctrl4calirun(ModelData md) {
    temcoreJNI.Controller_ctrl4calirun(swigCPtr, this, ModelData.getCPtr(md), md);
  }

  public void ctrl4siterun(ModelData md) {
    temcoreJNI.Controller_ctrl4siterun(swigCPtr, this, ModelData.getCPtr(md), md);
  }

  public void ctrl4regnrun(ModelData md) {
    temcoreJNI.Controller_ctrl4regnrun(swigCPtr, this, ModelData.getCPtr(md), md);
  }

  public void setControlfile(String jcontrolfile) {
    temcoreJNI.Controller_setControlfile(swigCPtr, this, jcontrolfile);
  }

}
