/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public final class DRGKEY {
  public final static DRGKEY I_DRY = new DRGKEY("I_DRY");
  public final static DRGKEY I_WET = new DRGKEY("I_WET");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DRGKEY swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DRGKEY.class + " with value " + swigValue);
  }

  private DRGKEY(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DRGKEY(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DRGKEY(String swigName, DRGKEY swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DRGKEY[] swigValues = { I_DRY, I_WET };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

