/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class EnvData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EnvData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EnvData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_EnvData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EnvData() {
    this(temcoreJNI.new_EnvData(), true);
  }

  public void setDaylengths(double[] value) {
    temcoreJNI.EnvData_daylengths_set(swigCPtr, this, value);
  }

  public double[] getDaylengths() {
    return temcoreJNI.EnvData_daylengths_get(swigCPtr, this);
  }

  public void setD_atms(atmstate_env value) {
    temcoreJNI.EnvData_d_atms_set(swigCPtr, this, atmstate_env.getCPtr(value), value);
  }

  public atmstate_env getD_atms() {
    long cPtr = temcoreJNI.EnvData_d_atms_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atmstate_env(cPtr, false);
  }

  public void setD_vegs(vegstate_env value) {
    temcoreJNI.EnvData_d_vegs_set(swigCPtr, this, vegstate_env.getCPtr(value), value);
  }

  public vegstate_env getD_vegs() {
    long cPtr = temcoreJNI.EnvData_d_vegs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegstate_env(cPtr, false);
  }

  public void setD_snws(snwstate_env value) {
    temcoreJNI.EnvData_d_snws_set(swigCPtr, this, snwstate_env.getCPtr(value), value);
  }

  public snwstate_env getD_snws() {
    long cPtr = temcoreJNI.EnvData_d_snws_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwstate_env(cPtr, false);
  }

  public void setD_sois(soistate_env value) {
    temcoreJNI.EnvData_d_sois_set(swigCPtr, this, soistate_env.getCPtr(value), value);
  }

  public soistate_env getD_sois() {
    long cPtr = temcoreJNI.EnvData_d_sois_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soistate_env(cPtr, false);
  }

  public void setD_atmd(atmdiag_env value) {
    temcoreJNI.EnvData_d_atmd_set(swigCPtr, this, atmdiag_env.getCPtr(value), value);
  }

  public atmdiag_env getD_atmd() {
    long cPtr = temcoreJNI.EnvData_d_atmd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atmdiag_env(cPtr, false);
  }

  public void setD_vegd(vegdiag_env value) {
    temcoreJNI.EnvData_d_vegd_set(swigCPtr, this, vegdiag_env.getCPtr(value), value);
  }

  public vegdiag_env getD_vegd() {
    long cPtr = temcoreJNI.EnvData_d_vegd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegdiag_env(cPtr, false);
  }

  public void setD_snwd(snwdiag_env value) {
    temcoreJNI.EnvData_d_snwd_set(swigCPtr, this, snwdiag_env.getCPtr(value), value);
  }

  public snwdiag_env getD_snwd() {
    long cPtr = temcoreJNI.EnvData_d_snwd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwdiag_env(cPtr, false);
  }

  public void setD_soid(soidiag_env value) {
    temcoreJNI.EnvData_d_soid_set(swigCPtr, this, soidiag_env.getCPtr(value), value);
  }

  public soidiag_env getD_soid() {
    long cPtr = temcoreJNI.EnvData_d_soid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soidiag_env(cPtr, false);
  }

  public void setD_l2a(lnd2atm_env value) {
    temcoreJNI.EnvData_d_l2a_set(swigCPtr, this, lnd2atm_env.getCPtr(value), value);
  }

  public lnd2atm_env getD_l2a() {
    long cPtr = temcoreJNI.EnvData_d_l2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new lnd2atm_env(cPtr, false);
  }

  public void setD_a2l(atm2lnd_env value) {
    temcoreJNI.EnvData_d_a2l_set(swigCPtr, this, atm2lnd_env.getCPtr(value), value);
  }

  public atm2lnd_env getD_a2l() {
    long cPtr = temcoreJNI.EnvData_d_a2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2lnd_env(cPtr, false);
  }

  public void setD_a2v(atm2veg_env value) {
    temcoreJNI.EnvData_d_a2v_set(swigCPtr, this, atm2veg_env.getCPtr(value), value);
  }

  public atm2veg_env getD_a2v() {
    long cPtr = temcoreJNI.EnvData_d_a2v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2veg_env(cPtr, false);
  }

  public void setD_v2a(veg2atm_env value) {
    temcoreJNI.EnvData_d_v2a_set(swigCPtr, this, veg2atm_env.getCPtr(value), value);
  }

  public veg2atm_env getD_v2a() {
    long cPtr = temcoreJNI.EnvData_d_v2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2atm_env(cPtr, false);
  }

  public void setD_v2g(veg2gnd_env value) {
    temcoreJNI.EnvData_d_v2g_set(swigCPtr, this, veg2gnd_env.getCPtr(value), value);
  }

  public veg2gnd_env getD_v2g() {
    long cPtr = temcoreJNI.EnvData_d_v2g_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2gnd_env(cPtr, false);
  }

  public void setD_l2soi(lnd2soi_env value) {
    temcoreJNI.EnvData_d_l2soi_set(swigCPtr, this, lnd2soi_env.getCPtr(value), value);
  }

  public lnd2soi_env getD_l2soi() {
    long cPtr = temcoreJNI.EnvData_d_l2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new lnd2soi_env(cPtr, false);
  }

  public void setD_soi2l(soi2lnd_env value) {
    temcoreJNI.EnvData_d_soi2l_set(swigCPtr, this, soi2lnd_env.getCPtr(value), value);
  }

  public soi2lnd_env getD_soi2l() {
    long cPtr = temcoreJNI.EnvData_d_soi2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2lnd_env(cPtr, false);
  }

  public void setD_soi2a(soi2atm_env value) {
    temcoreJNI.EnvData_d_soi2a_set(swigCPtr, this, soi2atm_env.getCPtr(value), value);
  }

  public soi2atm_env getD_soi2a() {
    long cPtr = temcoreJNI.EnvData_d_soi2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2atm_env(cPtr, false);
  }

  public void setD_snw2a(snw2atm_env value) {
    temcoreJNI.EnvData_d_snw2a_set(swigCPtr, this, snw2atm_env.getCPtr(value), value);
  }

  public snw2atm_env getD_snw2a() {
    long cPtr = temcoreJNI.EnvData_d_snw2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snw2atm_env(cPtr, false);
  }

  public void setD_snw2soi(snw2soi_env value) {
    temcoreJNI.EnvData_d_snw2soi_set(swigCPtr, this, snw2soi_env.getCPtr(value), value);
  }

  public snw2soi_env getD_snw2soi() {
    long cPtr = temcoreJNI.EnvData_d_snw2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snw2soi_env(cPtr, false);
  }

  public void setM_atms(atmstate_env value) {
    temcoreJNI.EnvData_m_atms_set(swigCPtr, this, atmstate_env.getCPtr(value), value);
  }

  public atmstate_env getM_atms() {
    long cPtr = temcoreJNI.EnvData_m_atms_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atmstate_env(cPtr, false);
  }

  public void setM_vegs(vegstate_env value) {
    temcoreJNI.EnvData_m_vegs_set(swigCPtr, this, vegstate_env.getCPtr(value), value);
  }

  public vegstate_env getM_vegs() {
    long cPtr = temcoreJNI.EnvData_m_vegs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegstate_env(cPtr, false);
  }

  public void setM_snws(snwstate_env value) {
    temcoreJNI.EnvData_m_snws_set(swigCPtr, this, snwstate_env.getCPtr(value), value);
  }

  public snwstate_env getM_snws() {
    long cPtr = temcoreJNI.EnvData_m_snws_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwstate_env(cPtr, false);
  }

  public void setM_sois(soistate_env value) {
    temcoreJNI.EnvData_m_sois_set(swigCPtr, this, soistate_env.getCPtr(value), value);
  }

  public soistate_env getM_sois() {
    long cPtr = temcoreJNI.EnvData_m_sois_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soistate_env(cPtr, false);
  }

  public void setM_atmd(atmdiag_env value) {
    temcoreJNI.EnvData_m_atmd_set(swigCPtr, this, atmdiag_env.getCPtr(value), value);
  }

  public atmdiag_env getM_atmd() {
    long cPtr = temcoreJNI.EnvData_m_atmd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atmdiag_env(cPtr, false);
  }

  public void setM_vegd(vegdiag_env value) {
    temcoreJNI.EnvData_m_vegd_set(swigCPtr, this, vegdiag_env.getCPtr(value), value);
  }

  public vegdiag_env getM_vegd() {
    long cPtr = temcoreJNI.EnvData_m_vegd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegdiag_env(cPtr, false);
  }

  public void setM_snwd(snwdiag_env value) {
    temcoreJNI.EnvData_m_snwd_set(swigCPtr, this, snwdiag_env.getCPtr(value), value);
  }

  public snwdiag_env getM_snwd() {
    long cPtr = temcoreJNI.EnvData_m_snwd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwdiag_env(cPtr, false);
  }

  public void setM_soid(soidiag_env value) {
    temcoreJNI.EnvData_m_soid_set(swigCPtr, this, soidiag_env.getCPtr(value), value);
  }

  public soidiag_env getM_soid() {
    long cPtr = temcoreJNI.EnvData_m_soid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soidiag_env(cPtr, false);
  }

  public void setM_l2a(lnd2atm_env value) {
    temcoreJNI.EnvData_m_l2a_set(swigCPtr, this, lnd2atm_env.getCPtr(value), value);
  }

  public lnd2atm_env getM_l2a() {
    long cPtr = temcoreJNI.EnvData_m_l2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new lnd2atm_env(cPtr, false);
  }

  public void setM_a2l(atm2lnd_env value) {
    temcoreJNI.EnvData_m_a2l_set(swigCPtr, this, atm2lnd_env.getCPtr(value), value);
  }

  public atm2lnd_env getM_a2l() {
    long cPtr = temcoreJNI.EnvData_m_a2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2lnd_env(cPtr, false);
  }

  public void setM_a2v(atm2veg_env value) {
    temcoreJNI.EnvData_m_a2v_set(swigCPtr, this, atm2veg_env.getCPtr(value), value);
  }

  public atm2veg_env getM_a2v() {
    long cPtr = temcoreJNI.EnvData_m_a2v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2veg_env(cPtr, false);
  }

  public void setM_v2a(veg2atm_env value) {
    temcoreJNI.EnvData_m_v2a_set(swigCPtr, this, veg2atm_env.getCPtr(value), value);
  }

  public veg2atm_env getM_v2a() {
    long cPtr = temcoreJNI.EnvData_m_v2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2atm_env(cPtr, false);
  }

  public void setM_v2g(veg2gnd_env value) {
    temcoreJNI.EnvData_m_v2g_set(swigCPtr, this, veg2gnd_env.getCPtr(value), value);
  }

  public veg2gnd_env getM_v2g() {
    long cPtr = temcoreJNI.EnvData_m_v2g_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2gnd_env(cPtr, false);
  }

  public void setM_l2soi(lnd2soi_env value) {
    temcoreJNI.EnvData_m_l2soi_set(swigCPtr, this, lnd2soi_env.getCPtr(value), value);
  }

  public lnd2soi_env getM_l2soi() {
    long cPtr = temcoreJNI.EnvData_m_l2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new lnd2soi_env(cPtr, false);
  }

  public void setM_soi2l(soi2lnd_env value) {
    temcoreJNI.EnvData_m_soi2l_set(swigCPtr, this, soi2lnd_env.getCPtr(value), value);
  }

  public soi2lnd_env getM_soi2l() {
    long cPtr = temcoreJNI.EnvData_m_soi2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2lnd_env(cPtr, false);
  }

  public void setM_soi2a(soi2atm_env value) {
    temcoreJNI.EnvData_m_soi2a_set(swigCPtr, this, soi2atm_env.getCPtr(value), value);
  }

  public soi2atm_env getM_soi2a() {
    long cPtr = temcoreJNI.EnvData_m_soi2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2atm_env(cPtr, false);
  }

  public void setM_snw2a(snw2atm_env value) {
    temcoreJNI.EnvData_m_snw2a_set(swigCPtr, this, snw2atm_env.getCPtr(value), value);
  }

  public snw2atm_env getM_snw2a() {
    long cPtr = temcoreJNI.EnvData_m_snw2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snw2atm_env(cPtr, false);
  }

  public void setM_snw2soi(snw2soi_env value) {
    temcoreJNI.EnvData_m_snw2soi_set(swigCPtr, this, snw2soi_env.getCPtr(value), value);
  }

  public snw2soi_env getM_snw2soi() {
    long cPtr = temcoreJNI.EnvData_m_snw2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snw2soi_env(cPtr, false);
  }

  public void setY_atms(atmstate_env value) {
    temcoreJNI.EnvData_y_atms_set(swigCPtr, this, atmstate_env.getCPtr(value), value);
  }

  public atmstate_env getY_atms() {
    long cPtr = temcoreJNI.EnvData_y_atms_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atmstate_env(cPtr, false);
  }

  public void setY_vegs(vegstate_env value) {
    temcoreJNI.EnvData_y_vegs_set(swigCPtr, this, vegstate_env.getCPtr(value), value);
  }

  public vegstate_env getY_vegs() {
    long cPtr = temcoreJNI.EnvData_y_vegs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegstate_env(cPtr, false);
  }

  public void setY_snws(snwstate_env value) {
    temcoreJNI.EnvData_y_snws_set(swigCPtr, this, snwstate_env.getCPtr(value), value);
  }

  public snwstate_env getY_snws() {
    long cPtr = temcoreJNI.EnvData_y_snws_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwstate_env(cPtr, false);
  }

  public void setY_sois(soistate_env value) {
    temcoreJNI.EnvData_y_sois_set(swigCPtr, this, soistate_env.getCPtr(value), value);
  }

  public soistate_env getY_sois() {
    long cPtr = temcoreJNI.EnvData_y_sois_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soistate_env(cPtr, false);
  }

  public void setY_atmd(atmdiag_env value) {
    temcoreJNI.EnvData_y_atmd_set(swigCPtr, this, atmdiag_env.getCPtr(value), value);
  }

  public atmdiag_env getY_atmd() {
    long cPtr = temcoreJNI.EnvData_y_atmd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atmdiag_env(cPtr, false);
  }

  public void setY_vegd(vegdiag_env value) {
    temcoreJNI.EnvData_y_vegd_set(swigCPtr, this, vegdiag_env.getCPtr(value), value);
  }

  public vegdiag_env getY_vegd() {
    long cPtr = temcoreJNI.EnvData_y_vegd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegdiag_env(cPtr, false);
  }

  public void setY_snwd(snwdiag_env value) {
    temcoreJNI.EnvData_y_snwd_set(swigCPtr, this, snwdiag_env.getCPtr(value), value);
  }

  public snwdiag_env getY_snwd() {
    long cPtr = temcoreJNI.EnvData_y_snwd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwdiag_env(cPtr, false);
  }

  public void setY_soid(soidiag_env value) {
    temcoreJNI.EnvData_y_soid_set(swigCPtr, this, soidiag_env.getCPtr(value), value);
  }

  public soidiag_env getY_soid() {
    long cPtr = temcoreJNI.EnvData_y_soid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soidiag_env(cPtr, false);
  }

  public void setY_l2a(lnd2atm_env value) {
    temcoreJNI.EnvData_y_l2a_set(swigCPtr, this, lnd2atm_env.getCPtr(value), value);
  }

  public lnd2atm_env getY_l2a() {
    long cPtr = temcoreJNI.EnvData_y_l2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new lnd2atm_env(cPtr, false);
  }

  public void setY_a2l(atm2lnd_env value) {
    temcoreJNI.EnvData_y_a2l_set(swigCPtr, this, atm2lnd_env.getCPtr(value), value);
  }

  public atm2lnd_env getY_a2l() {
    long cPtr = temcoreJNI.EnvData_y_a2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2lnd_env(cPtr, false);
  }

  public void setY_a2v(atm2veg_env value) {
    temcoreJNI.EnvData_y_a2v_set(swigCPtr, this, atm2veg_env.getCPtr(value), value);
  }

  public atm2veg_env getY_a2v() {
    long cPtr = temcoreJNI.EnvData_y_a2v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2veg_env(cPtr, false);
  }

  public void setY_v2a(veg2atm_env value) {
    temcoreJNI.EnvData_y_v2a_set(swigCPtr, this, veg2atm_env.getCPtr(value), value);
  }

  public veg2atm_env getY_v2a() {
    long cPtr = temcoreJNI.EnvData_y_v2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2atm_env(cPtr, false);
  }

  public void setY_v2g(veg2gnd_env value) {
    temcoreJNI.EnvData_y_v2g_set(swigCPtr, this, veg2gnd_env.getCPtr(value), value);
  }

  public veg2gnd_env getY_v2g() {
    long cPtr = temcoreJNI.EnvData_y_v2g_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2gnd_env(cPtr, false);
  }

  public void setY_l2soi(lnd2soi_env value) {
    temcoreJNI.EnvData_y_l2soi_set(swigCPtr, this, lnd2soi_env.getCPtr(value), value);
  }

  public lnd2soi_env getY_l2soi() {
    long cPtr = temcoreJNI.EnvData_y_l2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new lnd2soi_env(cPtr, false);
  }

  public void setY_soi2l(soi2lnd_env value) {
    temcoreJNI.EnvData_y_soi2l_set(swigCPtr, this, soi2lnd_env.getCPtr(value), value);
  }

  public soi2lnd_env getY_soi2l() {
    long cPtr = temcoreJNI.EnvData_y_soi2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2lnd_env(cPtr, false);
  }

  public void setY_soi2a(soi2atm_env value) {
    temcoreJNI.EnvData_y_soi2a_set(swigCPtr, this, soi2atm_env.getCPtr(value), value);
  }

  public soi2atm_env getY_soi2a() {
    long cPtr = temcoreJNI.EnvData_y_soi2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2atm_env(cPtr, false);
  }

  public void setY_snw2a(snw2atm_env value) {
    temcoreJNI.EnvData_y_snw2a_set(swigCPtr, this, snw2atm_env.getCPtr(value), value);
  }

  public snw2atm_env getY_snw2a() {
    long cPtr = temcoreJNI.EnvData_y_snw2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snw2atm_env(cPtr, false);
  }

  public void setY_snw2soi(snw2soi_env value) {
    temcoreJNI.EnvData_y_snw2soi_set(swigCPtr, this, snw2soi_env.getCPtr(value), value);
  }

  public snw2soi_env getY_snw2soi() {
    long cPtr = temcoreJNI.EnvData_y_snw2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snw2soi_env(cPtr, false);
  }

  public void setEetmx(double value) {
    temcoreJNI.EnvData_eetmx_set(swigCPtr, this, value);
  }

  public double getEetmx() {
    return temcoreJNI.EnvData_eetmx_get(swigCPtr, this);
  }

  public void setPetmx(double value) {
    temcoreJNI.EnvData_petmx_set(swigCPtr, this, value);
  }

  public double getPetmx() {
    return temcoreJNI.EnvData_petmx_get(swigCPtr, this);
  }

  public void setPrveetmx(double value) {
    temcoreJNI.EnvData_prveetmx_set(swigCPtr, this, value);
  }

  public double getPrveetmx() {
    return temcoreJNI.EnvData_prveetmx_get(swigCPtr, this);
  }

  public void setPrvpetmx(double value) {
    temcoreJNI.EnvData_prvpetmx_set(swigCPtr, this, value);
  }

  public double getPrvpetmx() {
    return temcoreJNI.EnvData_prvpetmx_get(swigCPtr, this);
  }

  public void setInitco2(double value) {
    temcoreJNI.EnvData_initco2_set(swigCPtr, this, value);
  }

  public double getInitco2() {
    return temcoreJNI.EnvData_initco2_get(swigCPtr, this);
  }

  public void setPermafrost(int value) {
    temcoreJNI.EnvData_permafrost_set(swigCPtr, this, value);
  }

  public int getPermafrost() {
    return temcoreJNI.EnvData_permafrost_get(swigCPtr, this);
  }

  public void setY_ald(double value) {
    temcoreJNI.EnvData_y_ald_set(swigCPtr, this, value);
  }

  public double getY_ald() {
    return temcoreJNI.EnvData_y_ald_get(swigCPtr, this);
  }

  public void setM_ald(double value) {
    temcoreJNI.EnvData_m_ald_set(swigCPtr, this, value);
  }

  public double getM_ald() {
    return temcoreJNI.EnvData_m_ald_get(swigCPtr, this);
  }

  public void setD_ald(double value) {
    temcoreJNI.EnvData_d_ald_set(swigCPtr, this, value);
  }

  public double getD_ald() {
    return temcoreJNI.EnvData_d_ald_get(swigCPtr, this);
  }

  public void setYrfrozensoil(double value) {
    temcoreJNI.EnvData_yrfrozensoil_set(swigCPtr, this, value);
  }

  public double getYrfrozensoil() {
    return temcoreJNI.EnvData_yrfrozensoil_get(swigCPtr, this);
  }

  public void init() {
    temcoreJNI.EnvData_init(swigCPtr, this);
  }

  public void beginOfDay() {
    temcoreJNI.EnvData_beginOfDay(swigCPtr, this);
  }

  public void beginOfMonth() {
    temcoreJNI.EnvData_beginOfMonth(swigCPtr, this);
  }

  public void beginOfYear() {
    temcoreJNI.EnvData_beginOfYear(swigCPtr, this);
  }

  public void endOfDay(int dinm, int doy) {
    temcoreJNI.EnvData_endOfDay(swigCPtr, this, dinm, doy);
  }

  public void endOfMonth(int currmind, boolean assign) {
    temcoreJNI.EnvData_endOfMonth(swigCPtr, this, currmind, assign);
  }

  public void endOfYear(boolean assign) {
    temcoreJNI.EnvData_endOfYear(swigCPtr, this, assign);
  }

  public void setEq_ts(SWIGTYPE_p_a_MAX_SOI_LAY__double value) {
    temcoreJNI.EnvData_eq_ts_set(swigCPtr, this, SWIGTYPE_p_a_MAX_SOI_LAY__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_SOI_LAY__double getEq_ts() {
    long cPtr = temcoreJNI.EnvData_eq_ts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_SOI_LAY__double(cPtr, false);
  }

  public void setEq_liq(SWIGTYPE_p_a_MAX_SOI_LAY__double value) {
    temcoreJNI.EnvData_eq_liq_set(swigCPtr, this, SWIGTYPE_p_a_MAX_SOI_LAY__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_SOI_LAY__double getEq_liq() {
    long cPtr = temcoreJNI.EnvData_eq_liq_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_SOI_LAY__double(cPtr, false);
  }

  public void setEq_ice(SWIGTYPE_p_a_MAX_SOI_LAY__double value) {
    temcoreJNI.EnvData_eq_ice_set(swigCPtr, this, SWIGTYPE_p_a_MAX_SOI_LAY__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_SOI_LAY__double getEq_ice() {
    long cPtr = temcoreJNI.EnvData_eq_ice_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_SOI_LAY__double(cPtr, false);
  }

  public void setEq_vwc(SWIGTYPE_p_a_MAX_SOI_LAY__double value) {
    temcoreJNI.EnvData_eq_vwc_set(swigCPtr, this, SWIGTYPE_p_a_MAX_SOI_LAY__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_SOI_LAY__double getEq_vwc() {
    long cPtr = temcoreJNI.EnvData_eq_vwc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_SOI_LAY__double(cPtr, false);
  }

  public void setEq_sws(SWIGTYPE_p_a_MAX_SOI_LAY__double value) {
    temcoreJNI.EnvData_eq_sws_set(swigCPtr, this, SWIGTYPE_p_a_MAX_SOI_LAY__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_SOI_LAY__double getEq_sws() {
    long cPtr = temcoreJNI.EnvData_eq_sws_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_SOI_LAY__double(cPtr, false);
  }

  public void setEq_aws(SWIGTYPE_p_a_MAX_SOI_LAY__double value) {
    temcoreJNI.EnvData_eq_aws_set(swigCPtr, this, SWIGTYPE_p_a_MAX_SOI_LAY__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_SOI_LAY__double getEq_aws() {
    long cPtr = temcoreJNI.EnvData_eq_aws_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_SOI_LAY__double(cPtr, false);
  }

  public void setEq_ta(double[] value) {
    temcoreJNI.EnvData_eq_ta_set(swigCPtr, this, value);
  }

  public double[] getEq_ta() {
    return temcoreJNI.EnvData_eq_ta_get(swigCPtr, this);
  }

  public void setEq_co2(double[] value) {
    temcoreJNI.EnvData_eq_co2_set(swigCPtr, this, value);
  }

  public double[] getEq_co2() {
    return temcoreJNI.EnvData_eq_co2_get(swigCPtr, this);
  }

  public void setEq_eet(double[] value) {
    temcoreJNI.EnvData_eq_eet_set(swigCPtr, this, value);
  }

  public double[] getEq_eet() {
    return temcoreJNI.EnvData_eq_eet_get(swigCPtr, this);
  }

  public void setEq_pet(double[] value) {
    temcoreJNI.EnvData_eq_pet_set(swigCPtr, this, value);
  }

  public double[] getEq_pet() {
    return temcoreJNI.EnvData_eq_pet_get(swigCPtr, this);
  }

  public void setEq_par(double[] value) {
    temcoreJNI.EnvData_eq_par_set(swigCPtr, this, value);
  }

  public double[] getEq_par() {
    return temcoreJNI.EnvData_eq_par_get(swigCPtr, this);
  }

  public void setEq_grow(double[] value) {
    temcoreJNI.EnvData_eq_grow_set(swigCPtr, this, value);
  }

  public double[] getEq_grow() {
    return temcoreJNI.EnvData_eq_grow_get(swigCPtr, this);
  }

  public void setEq_y_eet(double value) {
    temcoreJNI.EnvData_eq_y_eet_set(swigCPtr, this, value);
  }

  public double getEq_y_eet() {
    return temcoreJNI.EnvData_eq_y_eet_get(swigCPtr, this);
  }

  public void setEq_y_pet(double value) {
    temcoreJNI.EnvData_eq_y_pet_set(swigCPtr, this, value);
  }

  public double getEq_y_pet() {
    return temcoreJNI.EnvData_eq_y_pet_get(swigCPtr, this);
  }

  public void setEq_y_co2(double value) {
    temcoreJNI.EnvData_eq_y_co2_set(swigCPtr, this, value);
  }

  public double getEq_y_co2() {
    return temcoreJNI.EnvData_eq_y_co2_get(swigCPtr, this);
  }

  public void setEq_prveetmx(double value) {
    temcoreJNI.EnvData_eq_prveetmx_set(swigCPtr, this, value);
  }

  public double getEq_prveetmx() {
    return temcoreJNI.EnvData_eq_prveetmx_get(swigCPtr, this);
  }

  public void setEq_prvpetmx(double value) {
    temcoreJNI.EnvData_eq_prvpetmx_set(swigCPtr, this, value);
  }

  public double getEq_prvpetmx() {
    return temcoreJNI.EnvData_eq_prvpetmx_get(swigCPtr, this);
  }

  public void setEetmxque(SWIGTYPE_p_dequeT_double_t value) {
    temcoreJNI.EnvData_eetmxque_set(swigCPtr, this, SWIGTYPE_p_dequeT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_dequeT_double_t getEetmxque() {
    return new SWIGTYPE_p_dequeT_double_t(temcoreJNI.EnvData_eetmxque_get(swigCPtr, this), true);
  }

  public void setPetmxque(SWIGTYPE_p_dequeT_double_t value) {
    temcoreJNI.EnvData_petmxque_set(swigCPtr, this, SWIGTYPE_p_dequeT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_dequeT_double_t getPetmxque() {
    return new SWIGTYPE_p_dequeT_double_t(temcoreJNI.EnvData_petmxque_get(swigCPtr, this), true);
  }

  public void setRd(RegionData value) {
    temcoreJNI.EnvData_rd_set(swigCPtr, this, RegionData.getCPtr(value), value);
  }

  public RegionData getRd() {
    long cPtr = temcoreJNI.EnvData_rd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RegionData(cPtr, false);
  }

  public void setGd(GridData value) {
    temcoreJNI.EnvData_gd_set(swigCPtr, this, GridData.getCPtr(value), value);
  }

  public GridData getGd() {
    long cPtr = temcoreJNI.EnvData_gd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GridData(cPtr, false);
  }

  public void setCd(CohortData value) {
    temcoreJNI.EnvData_cd_set(swigCPtr, this, CohortData.getCPtr(value), value);
  }

  public CohortData getCd() {
    long cPtr = temcoreJNI.EnvData_cd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CohortData(cPtr, false);
  }

  public void setEq_ts1d(double[] value) {
    temcoreJNI.EnvData_eq_ts1d_set(swigCPtr, this, value);
  }

  public double[] getEq_ts1d() {
    return temcoreJNI.EnvData_eq_ts1d_get(swigCPtr, this);
  }

  public void setEq_liq1d(double[] value) {
    temcoreJNI.EnvData_eq_liq1d_set(swigCPtr, this, value);
  }

  public double[] getEq_liq1d() {
    return temcoreJNI.EnvData_eq_liq1d_get(swigCPtr, this);
  }

  public void setEq_vwc1d(double[] value) {
    temcoreJNI.EnvData_eq_vwc1d_set(swigCPtr, this, value);
  }

  public double[] getEq_vwc1d() {
    return temcoreJNI.EnvData_eq_vwc1d_get(swigCPtr, this);
  }

  public void setEq_sws1d(double[] value) {
    temcoreJNI.EnvData_eq_sws1d_set(swigCPtr, this, value);
  }

  public double[] getEq_sws1d() {
    return temcoreJNI.EnvData_eq_sws1d_get(swigCPtr, this);
  }

  public void setEq_ice1d(double[] value) {
    temcoreJNI.EnvData_eq_ice1d_set(swigCPtr, this, value);
  }

  public double[] getEq_ice1d() {
    return temcoreJNI.EnvData_eq_ice1d_get(swigCPtr, this);
  }

  public void d1tod2() {
    temcoreJNI.EnvData_d1tod2(swigCPtr, this);
  }

  public void d2tod1() {
    temcoreJNI.EnvData_d2tod1(swigCPtr, this);
  }

}
