/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class FirData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FirData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FirData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_FirData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FirData() {
    this(temcoreJNI.new_FirData(), true);
  }

  public void setY_v2a(veg2atm_fir value) {
    temcoreJNI.FirData_y_v2a_set(swigCPtr, this, veg2atm_fir.getCPtr(value), value);
  }

  public veg2atm_fir getY_v2a() {
    long cPtr = temcoreJNI.FirData_y_v2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2atm_fir(cPtr, false);
  }

  public void setY_v2soi(veg2soi_fir value) {
    temcoreJNI.FirData_y_v2soi_set(swigCPtr, this, veg2soi_fir.getCPtr(value), value);
  }

  public veg2soi_fir getY_v2soi() {
    long cPtr = temcoreJNI.FirData_y_v2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2soi_fir(cPtr, false);
  }

  public void setY_soi2a(soi2atm_fir value) {
    temcoreJNI.FirData_y_soi2a_set(swigCPtr, this, soi2atm_fir.getCPtr(value), value);
  }

  public soi2atm_fir getY_soi2a() {
    long cPtr = temcoreJNI.FirData_y_soi2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2atm_fir(cPtr, false);
  }

  public void setY_soid(soidiag_fir value) {
    temcoreJNI.FirData_y_soid_set(swigCPtr, this, soidiag_fir.getCPtr(value), value);
  }

  public soidiag_fir getY_soid() {
    long cPtr = temcoreJNI.FirData_y_soid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soidiag_fir(cPtr, false);
  }

  public void setY_a2soi(atm2soi_fir value) {
    temcoreJNI.FirData_y_a2soi_set(swigCPtr, this, atm2soi_fir.getCPtr(value), value);
  }

  public atm2soi_fir getY_a2soi() {
    long cPtr = temcoreJNI.FirData_y_a2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2soi_fir(cPtr, false);
  }

  public void setUseseverity(boolean value) {
    temcoreJNI.FirData_useseverity_set(swigCPtr, this, value);
  }

  public boolean getUseseverity() {
    return temcoreJNI.FirData_useseverity_get(swigCPtr, this);
  }

  public void init() {
    temcoreJNI.FirData_init(swigCPtr, this);
  }

  public void beginOfYear() {
    temcoreJNI.FirData_beginOfYear(swigCPtr, this);
  }

  public void endOfYear() {
    temcoreJNI.FirData_endOfYear(swigCPtr, this);
  }

  public void burn() {
    temcoreJNI.FirData_burn(swigCPtr, this);
  }

  public void setYsf(int value) {
    temcoreJNI.FirData_ysf_set(swigCPtr, this, value);
  }

  public int getYsf() {
    return temcoreJNI.FirData_ysf_get(swigCPtr, this);
  }

  public void setRd(RegionData value) {
    temcoreJNI.FirData_rd_set(swigCPtr, this, RegionData.getCPtr(value), value);
  }

  public RegionData getRd() {
    long cPtr = temcoreJNI.FirData_rd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RegionData(cPtr, false);
  }

  public void setGd(GridData value) {
    temcoreJNI.FirData_gd_set(swigCPtr, this, GridData.getCPtr(value), value);
  }

  public GridData getGd() {
    long cPtr = temcoreJNI.FirData_gd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GridData(cPtr, false);
  }

  public void setCd(CohortData value) {
    temcoreJNI.FirData_cd_set(swigCPtr, this, CohortData.getCPtr(value), value);
  }

  public CohortData getCd() {
    long cPtr = temcoreJNI.FirData_cd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CohortData(cPtr, false);
  }

}
