/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class fire_par {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected fire_par(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fire_par obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_fire_par(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBurnthick_max(float value) {
    temcoreJNI.fire_par_burnthick_max_set(swigCPtr, this, value);
  }

  public float getBurnthick_max() {
    return temcoreJNI.fire_par_burnthick_max_get(swigCPtr, this);
  }

  public void setVegcombust(float value) {
    temcoreJNI.fire_par_vegcombust_set(swigCPtr, this, value);
  }

  public float getVegcombust() {
    return temcoreJNI.fire_par_vegcombust_get(swigCPtr, this);
  }

  public void setVegslash(float value) {
    temcoreJNI.fire_par_vegslash_set(swigCPtr, this, value);
  }

  public float getVegslash() {
    return temcoreJNI.fire_par_vegslash_get(swigCPtr, this);
  }

  public fire_par() {
    this(temcoreJNI.new_fire_par(), true);
  }

}
