/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class GridData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GridData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GridData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_GridData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GridData() {
    this(temcoreJNI.new_GridData(), true);
  }

  public void setGid(int value) {
    temcoreJNI.GridData_gid_set(swigCPtr, this, value);
  }

  public int getGid() {
    return temcoreJNI.GridData_gid_get(swigCPtr, this);
  }

  public void setLat(float value) {
    temcoreJNI.GridData_lat_set(swigCPtr, this, value);
  }

  public float getLat() {
    return temcoreJNI.GridData_lat_get(swigCPtr, this);
  }

  public void setLon(float value) {
    temcoreJNI.GridData_lon_set(swigCPtr, this, value);
  }

  public float getLon() {
    return temcoreJNI.GridData_lon_get(swigCPtr, this);
  }

  public void setAlldaylengths(float[] value) {
    temcoreJNI.GridData_alldaylengths_set(swigCPtr, this, value);
  }

  public float[] getAlldaylengths() {
    return temcoreJNI.GridData_alldaylengths_get(swigCPtr, this);
  }

  public void setFri(int value) {
    temcoreJNI.GridData_fri_set(swigCPtr, this, value);
  }

  public int getFri() {
    return temcoreJNI.GridData_fri_get(swigCPtr, this);
  }

  public void setFireyear(int[] value) {
    temcoreJNI.GridData_fireyear_set(swigCPtr, this, value);
  }

  public int[] getFireyear() {
    return temcoreJNI.GridData_fireyear_get(swigCPtr, this);
  }

  public void setFiresize(int[] value) {
    temcoreJNI.GridData_firesize_set(swigCPtr, this, value);
  }

  public int[] getFiresize() {
    return temcoreJNI.GridData_firesize_get(swigCPtr, this);
  }

  public void setFireseason(int[] value) {
    temcoreJNI.GridData_fireseason_set(swigCPtr, this, value);
  }

  public int[] getFireseason() {
    return temcoreJNI.GridData_fireseason_get(swigCPtr, this);
  }

  public void setTopsoil(int value) {
    temcoreJNI.GridData_topsoil_set(swigCPtr, this, value);
  }

  public int getTopsoil() {
    return temcoreJNI.GridData_topsoil_get(swigCPtr, this);
  }

  public void setBotsoil(int value) {
    temcoreJNI.GridData_botsoil_set(swigCPtr, this, value);
  }

  public int getBotsoil() {
    return temcoreJNI.GridData_botsoil_get(swigCPtr, this);
  }

  public void setAct_atm_drv_yr(int value) {
    temcoreJNI.GridData_act_atm_drv_yr_set(swigCPtr, this, value);
  }

  public int getAct_atm_drv_yr() {
    return temcoreJNI.GridData_act_atm_drv_yr_get(swigCPtr, this);
  }

  public void setTa(SWIGTYPE_p_a_12__float value) {
    temcoreJNI.GridData_ta_set(swigCPtr, this, SWIGTYPE_p_a_12__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_12__float getTa() {
    long cPtr = temcoreJNI.GridData_ta_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_12__float(cPtr, false);
  }

  public void setPrec(SWIGTYPE_p_a_12__float value) {
    temcoreJNI.GridData_prec_set(swigCPtr, this, SWIGTYPE_p_a_12__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_12__float getPrec() {
    long cPtr = temcoreJNI.GridData_prec_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_12__float(cPtr, false);
  }

  public void setNirr(SWIGTYPE_p_a_12__float value) {
    temcoreJNI.GridData_nirr_set(swigCPtr, this, SWIGTYPE_p_a_12__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_12__float getNirr() {
    long cPtr = temcoreJNI.GridData_nirr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_12__float(cPtr, false);
  }

  public void setVap(SWIGTYPE_p_a_12__float value) {
    temcoreJNI.GridData_vap_set(swigCPtr, this, SWIGTYPE_p_a_12__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_12__float getVap() {
    long cPtr = temcoreJNI.GridData_vap_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_12__float(cPtr, false);
  }

  public void setTa1d(float[] value) {
    temcoreJNI.GridData_ta1d_set(swigCPtr, this, value);
  }

  public float[] getTa1d() {
    return temcoreJNI.GridData_ta1d_get(swigCPtr, this);
  }

  public void setPrec1d(float[] value) {
    temcoreJNI.GridData_prec1d_set(swigCPtr, this, value);
  }

  public float[] getPrec1d() {
    return temcoreJNI.GridData_prec1d_get(swigCPtr, this);
  }

  public void setNirr1d(float[] value) {
    temcoreJNI.GridData_nirr1d_set(swigCPtr, this, value);
  }

  public float[] getNirr1d() {
    return temcoreJNI.GridData_nirr1d_get(swigCPtr, this);
  }

  public void setVap1d(float[] value) {
    temcoreJNI.GridData_vap1d_set(swigCPtr, this, value);
  }

  public float[] getVap1d() {
    return temcoreJNI.GridData_vap1d_get(swigCPtr, this);
  }

  public void d1tod2() {
    temcoreJNI.GridData_d1tod2(swigCPtr, this);
  }

}
