/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class Grid {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Grid(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Grid obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_Grid(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Grid() {
    this(temcoreJNI.new_Grid(), true);
  }

  public void setGid(int value) {
    temcoreJNI.Grid_gid_set(swigCPtr, this, value);
  }

  public int getGid() {
    return temcoreJNI.Grid_gid_get(swigCPtr, this);
  }

  public int reinit(int gid1) {
    return temcoreJNI.Grid_reinit(swigCPtr, this, gid1);
  }

  public void setEnvData(EnvData ed) {
    temcoreJNI.Grid_setEnvData(swigCPtr, this, EnvData.getCPtr(ed), ed);
  }

  public void setRegionData(RegionData rd) {
    temcoreJNI.Grid_setRegionData(swigCPtr, this, RegionData.getCPtr(rd), rd);
  }

  public void setGridData(GridData gd) {
    temcoreJNI.Grid_setGridData(swigCPtr, this, GridData.getCPtr(gd), gd);
  }

  public void setAtm(SWIGTYPE_p_Atmosphere value) {
    temcoreJNI.Grid_atm_set(swigCPtr, this, SWIGTYPE_p_Atmosphere.getCPtr(value));
  }

  public SWIGTYPE_p_Atmosphere getAtm() {
    return new SWIGTYPE_p_Atmosphere(temcoreJNI.Grid_atm_get(swigCPtr, this), true);
  }

  public void setEd(EnvData value) {
    temcoreJNI.Grid_ed_set(swigCPtr, this, EnvData.getCPtr(value), value);
  }

  public EnvData getEd() {
    long cPtr = temcoreJNI.Grid_ed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EnvData(cPtr, false);
  }

  public void setRd(RegionData value) {
    temcoreJNI.Grid_rd_set(swigCPtr, this, RegionData.getCPtr(value), value);
  }

  public RegionData getRd() {
    long cPtr = temcoreJNI.Grid_rd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RegionData(cPtr, false);
  }

  public void setGd(GridData value) {
    temcoreJNI.Grid_gd_set(swigCPtr, this, GridData.getCPtr(value), value);
  }

  public GridData getGd() {
    long cPtr = temcoreJNI.Grid_gd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GridData(cPtr, false);
  }

}
