/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class lnd2soi_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected lnd2soi_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(lnd2soi_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_lnd2soi_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRperc(double value) {
    temcoreJNI.lnd2soi_env_rperc_set(swigCPtr, this, value);
  }

  public double getRperc() {
    return temcoreJNI.lnd2soi_env_rperc_get(swigCPtr, this);
  }

  public void setSperc(double value) {
    temcoreJNI.lnd2soi_env_sperc_set(swigCPtr, this, value);
  }

  public double getSperc() {
    return temcoreJNI.lnd2soi_env_sperc_get(swigCPtr, this);
  }

  public void setPerc(double value) {
    temcoreJNI.lnd2soi_env_perc_set(swigCPtr, this, value);
  }

  public double getPerc() {
    return temcoreJNI.lnd2soi_env_perc_get(swigCPtr, this);
  }

  public lnd2soi_env() {
    this(temcoreJNI.new_lnd2soi_env(), true);
  }

}
