/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class ModelData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ModelData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ModelData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_ModelData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ModelData() {
    this(temcoreJNI.new_ModelData(), true);
  }

  public void setRuneq(boolean value) {
    temcoreJNI.ModelData_runeq_set(swigCPtr, this, value);
  }

  public boolean getRuneq() {
    return temcoreJNI.ModelData_runeq_get(swigCPtr, this);
  }

  public void setRunsp(boolean value) {
    temcoreJNI.ModelData_runsp_set(swigCPtr, this, value);
  }

  public boolean getRunsp() {
    return temcoreJNI.ModelData_runsp_get(swigCPtr, this);
  }

  public void setRuntr(boolean value) {
    temcoreJNI.ModelData_runtr_set(swigCPtr, this, value);
  }

  public boolean getRuntr() {
    return temcoreJNI.ModelData_runtr_get(swigCPtr, this);
  }

  public void setRunsc(boolean value) {
    temcoreJNI.ModelData_runsc_set(swigCPtr, this, value);
  }

  public boolean getRunsc() {
    return temcoreJNI.ModelData_runsc_get(swigCPtr, this);
  }

  public void setChangeco2(boolean value) {
    temcoreJNI.ModelData_changeco2_set(swigCPtr, this, value);
  }

  public boolean getChangeco2() {
    return temcoreJNI.ModelData_changeco2_get(swigCPtr, this);
  }

  public void setChangeclimate(boolean value) {
    temcoreJNI.ModelData_changeclimate_set(swigCPtr, this, value);
  }

  public boolean getChangeclimate() {
    return temcoreJNI.ModelData_changeclimate_get(swigCPtr, this);
  }

  public void setUseseverity(boolean value) {
    temcoreJNI.ModelData_useseverity_set(swigCPtr, this, value);
  }

  public boolean getUseseverity() {
    return temcoreJNI.ModelData_useseverity_get(swigCPtr, this);
  }

  public void setMyid(int value) {
    temcoreJNI.ModelData_myid_set(swigCPtr, this, value);
  }

  public int getMyid() {
    return temcoreJNI.ModelData_myid_get(swigCPtr, this);
  }

  public void setNumprocs(int value) {
    temcoreJNI.ModelData_numprocs_set(swigCPtr, this, value);
  }

  public int getNumprocs() {
    return temcoreJNI.ModelData_numprocs_get(swigCPtr, this);
  }

  public void setInitmode(int value) {
    temcoreJNI.ModelData_initmode_set(swigCPtr, this, value);
  }

  public int getInitmode() {
    return temcoreJNI.ModelData_initmode_get(swigCPtr, this);
  }

  public void setConsoledebug(boolean value) {
    temcoreJNI.ModelData_consoledebug_set(swigCPtr, this, value);
  }

  public boolean getConsoledebug() {
    return temcoreJNI.ModelData_consoledebug_get(swigCPtr, this);
  }

  public void setOutputdir(SWIGTYPE_p_string value) {
    temcoreJNI.ModelData_outputdir_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getOutputdir() {
    return new SWIGTYPE_p_string(temcoreJNI.ModelData_outputdir_get(swigCPtr, this), true);
  }

  public void setCasename(SWIGTYPE_p_string value) {
    temcoreJNI.ModelData_casename_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getCasename() {
    return new SWIGTYPE_p_string(temcoreJNI.ModelData_casename_get(swigCPtr, this), true);
  }

  public void setCctypes(SWIGTYPE_p_string value) {
    temcoreJNI.ModelData_cctypes_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getCctypes() {
    return new SWIGTYPE_p_string(temcoreJNI.ModelData_cctypes_get(swigCPtr, this), true);
  }

  public void setReginputdir(SWIGTYPE_p_string value) {
    temcoreJNI.ModelData_reginputdir_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getReginputdir() {
    return new SWIGTYPE_p_string(temcoreJNI.ModelData_reginputdir_get(swigCPtr, this), true);
  }

  public void setGrdinputdir(SWIGTYPE_p_string value) {
    temcoreJNI.ModelData_grdinputdir_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getGrdinputdir() {
    return new SWIGTYPE_p_string(temcoreJNI.ModelData_grdinputdir_get(swigCPtr, this), true);
  }

  public void setRunchtfile(SWIGTYPE_p_string value) {
    temcoreJNI.ModelData_runchtfile_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getRunchtfile() {
    return new SWIGTYPE_p_string(temcoreJNI.ModelData_runchtfile_get(swigCPtr, this), true);
  }

  public void setInitmodes(SWIGTYPE_p_string value) {
    temcoreJNI.ModelData_initmodes_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getInitmodes() {
    return new SWIGTYPE_p_string(temcoreJNI.ModelData_initmodes_get(swigCPtr, this), true);
  }

  public void setRunstages(SWIGTYPE_p_string value) {
    temcoreJNI.ModelData_runstages_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getRunstages() {
    return new SWIGTYPE_p_string(temcoreJNI.ModelData_runstages_get(swigCPtr, this), true);
  }

  public void setInitialfile(SWIGTYPE_p_string value) {
    temcoreJNI.ModelData_initialfile_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getInitialfile() {
    return new SWIGTYPE_p_string(temcoreJNI.ModelData_initialfile_get(swigCPtr, this), true);
  }

  public void setEqchtinputdir(SWIGTYPE_p_string value) {
    temcoreJNI.ModelData_eqchtinputdir_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getEqchtinputdir() {
    return new SWIGTYPE_p_string(temcoreJNI.ModelData_eqchtinputdir_get(swigCPtr, this), true);
  }

  public void setSpchtinputdir(SWIGTYPE_p_string value) {
    temcoreJNI.ModelData_spchtinputdir_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getSpchtinputdir() {
    return new SWIGTYPE_p_string(temcoreJNI.ModelData_spchtinputdir_get(swigCPtr, this), true);
  }

  public void setTrchtinputdir(SWIGTYPE_p_string value) {
    temcoreJNI.ModelData_trchtinputdir_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getTrchtinputdir() {
    return new SWIGTYPE_p_string(temcoreJNI.ModelData_trchtinputdir_get(swigCPtr, this), true);
  }

  public void setCalibrationdir(SWIGTYPE_p_string value) {
    temcoreJNI.ModelData_calibrationdir_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getCalibrationdir() {
    return new SWIGTYPE_p_string(temcoreJNI.ModelData_calibrationdir_get(swigCPtr, this), true);
  }

  public void checking4run() {
    temcoreJNI.ModelData_checking4run(swigCPtr, this);
  }

  public void setJoutputdir(String value) {
    temcoreJNI.ModelData_joutputdir_set(swigCPtr, this, value);
  }

  public String getJoutputdir() {
    return temcoreJNI.ModelData_joutputdir_get(swigCPtr, this);
  }

  public void setJcasename(String value) {
    temcoreJNI.ModelData_jcasename_set(swigCPtr, this, value);
  }

  public String getJcasename() {
    return temcoreJNI.ModelData_jcasename_get(swigCPtr, this);
  }

  public void setJcctypes(String value) {
    temcoreJNI.ModelData_jcctypes_set(swigCPtr, this, value);
  }

  public String getJcctypes() {
    return temcoreJNI.ModelData_jcctypes_get(swigCPtr, this);
  }

  public void setJreginputdir(String value) {
    temcoreJNI.ModelData_jreginputdir_set(swigCPtr, this, value);
  }

  public String getJreginputdir() {
    return temcoreJNI.ModelData_jreginputdir_get(swigCPtr, this);
  }

  public void setJgrdinputdir(String value) {
    temcoreJNI.ModelData_jgrdinputdir_set(swigCPtr, this, value);
  }

  public String getJgrdinputdir() {
    return temcoreJNI.ModelData_jgrdinputdir_get(swigCPtr, this);
  }

  public void setJrunchtfile(String value) {
    temcoreJNI.ModelData_jrunchtfile_set(swigCPtr, this, value);
  }

  public String getJrunchtfile() {
    return temcoreJNI.ModelData_jrunchtfile_get(swigCPtr, this);
  }

  public void setJinitmodes(String value) {
    temcoreJNI.ModelData_jinitmodes_set(swigCPtr, this, value);
  }

  public String getJinitmodes() {
    return temcoreJNI.ModelData_jinitmodes_get(swigCPtr, this);
  }

  public void setJrunstages(String value) {
    temcoreJNI.ModelData_jrunstages_set(swigCPtr, this, value);
  }

  public String getJrunstages() {
    return temcoreJNI.ModelData_jrunstages_get(swigCPtr, this);
  }

  public void setJinitialfile(String value) {
    temcoreJNI.ModelData_jinitialfile_set(swigCPtr, this, value);
  }

  public String getJinitialfile() {
    return temcoreJNI.ModelData_jinitialfile_get(swigCPtr, this);
  }

  public void setJeqchtinputdir(String value) {
    temcoreJNI.ModelData_jeqchtinputdir_set(swigCPtr, this, value);
  }

  public String getJeqchtinputdir() {
    return temcoreJNI.ModelData_jeqchtinputdir_get(swigCPtr, this);
  }

  public void setJspchtinputdir(String value) {
    temcoreJNI.ModelData_jspchtinputdir_set(swigCPtr, this, value);
  }

  public String getJspchtinputdir() {
    return temcoreJNI.ModelData_jspchtinputdir_get(swigCPtr, this);
  }

  public void setJtrchtinputdir(String value) {
    temcoreJNI.ModelData_jtrchtinputdir_set(swigCPtr, this, value);
  }

  public String getJtrchtinputdir() {
    return temcoreJNI.ModelData_jtrchtinputdir_get(swigCPtr, this);
  }

  public void setJcalibrationdir(String value) {
    temcoreJNI.ModelData_jcalibrationdir_set(swigCPtr, this, value);
  }

  public String getJcalibrationdir() {
    return temcoreJNI.ModelData_jcalibrationdir_get(swigCPtr, this);
  }

  public void stringtochar() {
    temcoreJNI.ModelData_stringtochar(swigCPtr, this);
  }

}
