/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class RegionData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RegionData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RegionData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_RegionData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RegionData() {
    this(temcoreJNI.new_RegionData(), true);
  }

  public void setAct_co2_drv_yr(int value) {
    temcoreJNI.RegionData_act_co2_drv_yr_set(swigCPtr, this, value);
  }

  public int getAct_co2_drv_yr() {
    return temcoreJNI.RegionData_act_co2_drv_yr_get(swigCPtr, this);
  }

  public void setCo2year(int[] value) {
    temcoreJNI.RegionData_co2year_set(swigCPtr, this, value);
  }

  public int[] getCo2year() {
    return temcoreJNI.RegionData_co2year_get(swigCPtr, this);
  }

  public void setCo2(float[] value) {
    temcoreJNI.RegionData_co2_set(swigCPtr, this, value);
  }

  public float[] getCo2() {
    return temcoreJNI.RegionData_co2_get(swigCPtr, this);
  }

}
