/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class RegnOutData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RegnOutData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RegnOutData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_RegnOutData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RegnOutData() {
    this(temcoreJNI.new_RegnOutData(), true);
  }

  public void setChtid(int value) {
    temcoreJNI.RegnOutData_chtid_set(swigCPtr, this, value);
  }

  public int getChtid() {
    return temcoreJNI.RegnOutData_chtid_get(swigCPtr, this);
  }

  public void setStatus(int value) {
    temcoreJNI.RegnOutData_status_set(swigCPtr, this, value);
  }

  public int getStatus() {
    return temcoreJNI.RegnOutData_status_get(swigCPtr, this);
  }

  public void setYsf(float value) {
    temcoreJNI.RegnOutData_ysf_set(swigCPtr, this, value);
  }

  public float getYsf() {
    return temcoreJNI.RegnOutData_ysf_get(swigCPtr, this);
  }

  public void setOutvarlist(int[] value) {
    temcoreJNI.RegnOutData_outvarlist_set(swigCPtr, this, value);
  }

  public int[] getOutvarlist() {
    return temcoreJNI.RegnOutData_outvarlist_get(swigCPtr, this);
  }

  public void setBurnthick(float value) {
    temcoreJNI.RegnOutData_burnthick_set(swigCPtr, this, value);
  }

  public float getBurnthick() {
    return temcoreJNI.RegnOutData_burnthick_get(swigCPtr, this);
  }

  public void setBurnsoic(float value) {
    temcoreJNI.RegnOutData_burnsoic_set(swigCPtr, this, value);
  }

  public float getBurnsoic() {
    return temcoreJNI.RegnOutData_burnsoic_get(swigCPtr, this);
  }

  public void setBurnvegc(float value) {
    temcoreJNI.RegnOutData_burnvegc_set(swigCPtr, this, value);
  }

  public float getBurnvegc() {
    return temcoreJNI.RegnOutData_burnvegc_get(swigCPtr, this);
  }

  public void setGrowstart(float value) {
    temcoreJNI.RegnOutData_growstart_set(swigCPtr, this, value);
  }

  public float getGrowstart() {
    return temcoreJNI.RegnOutData_growstart_get(swigCPtr, this);
  }

  public void setGrowend(float value) {
    temcoreJNI.RegnOutData_growend_set(swigCPtr, this, value);
  }

  public float getGrowend() {
    return temcoreJNI.RegnOutData_growend_get(swigCPtr, this);
  }

  public void setPerm(float value) {
    temcoreJNI.RegnOutData_perm_set(swigCPtr, this, value);
  }

  public float getPerm() {
    return temcoreJNI.RegnOutData_perm_get(swigCPtr, this);
  }

  public void setMossdz(float value) {
    temcoreJNI.RegnOutData_mossdz_set(swigCPtr, this, value);
  }

  public float getMossdz() {
    return temcoreJNI.RegnOutData_mossdz_get(swigCPtr, this);
  }

  public void setShlwdz(float value) {
    temcoreJNI.RegnOutData_shlwdz_set(swigCPtr, this, value);
  }

  public float getShlwdz() {
    return temcoreJNI.RegnOutData_shlwdz_get(swigCPtr, this);
  }

  public void setDeepdz(float value) {
    temcoreJNI.RegnOutData_deepdz_set(swigCPtr, this, value);
  }

  public float getDeepdz() {
    return temcoreJNI.RegnOutData_deepdz_get(swigCPtr, this);
  }

  public void setLai(float[] value) {
    temcoreJNI.RegnOutData_lai_set(swigCPtr, this, value);
  }

  public float[] getLai() {
    return temcoreJNI.RegnOutData_lai_get(swigCPtr, this);
  }

  public void setVegc(float[] value) {
    temcoreJNI.RegnOutData_vegc_set(swigCPtr, this, value);
  }

  public float[] getVegc() {
    return temcoreJNI.RegnOutData_vegc_get(swigCPtr, this);
  }

  public void setVegn(float[] value) {
    temcoreJNI.RegnOutData_vegn_set(swigCPtr, this, value);
  }

  public float[] getVegn() {
    return temcoreJNI.RegnOutData_vegn_get(swigCPtr, this);
  }

  public void setGpp(float[] value) {
    temcoreJNI.RegnOutData_gpp_set(swigCPtr, this, value);
  }

  public float[] getGpp() {
    return temcoreJNI.RegnOutData_gpp_get(swigCPtr, this);
  }

  public void setNpp(float[] value) {
    temcoreJNI.RegnOutData_npp_set(swigCPtr, this, value);
  }

  public float[] getNpp() {
    return temcoreJNI.RegnOutData_npp_get(swigCPtr, this);
  }

  public void setRh(float[] value) {
    temcoreJNI.RegnOutData_rh_set(swigCPtr, this, value);
  }

  public float[] getRh() {
    return temcoreJNI.RegnOutData_rh_get(swigCPtr, this);
  }

  public void setLtrfalc(float[] value) {
    temcoreJNI.RegnOutData_ltrfalc_set(swigCPtr, this, value);
  }

  public float[] getLtrfalc() {
    return temcoreJNI.RegnOutData_ltrfalc_get(swigCPtr, this);
  }

  public void setLtrfaln(float[] value) {
    temcoreJNI.RegnOutData_ltrfaln_set(swigCPtr, this, value);
  }

  public float[] getLtrfaln() {
    return temcoreJNI.RegnOutData_ltrfaln_get(swigCPtr, this);
  }

  public void setShlwc(float[] value) {
    temcoreJNI.RegnOutData_shlwc_set(swigCPtr, this, value);
  }

  public float[] getShlwc() {
    return temcoreJNI.RegnOutData_shlwc_get(swigCPtr, this);
  }

  public void setDeepc(float[] value) {
    temcoreJNI.RegnOutData_deepc_set(swigCPtr, this, value);
  }

  public float[] getDeepc() {
    return temcoreJNI.RegnOutData_deepc_get(swigCPtr, this);
  }

  public void setMinec(float[] value) {
    temcoreJNI.RegnOutData_minec_set(swigCPtr, this, value);
  }

  public float[] getMinec() {
    return temcoreJNI.RegnOutData_minec_get(swigCPtr, this);
  }

  public void setOrgn(float[] value) {
    temcoreJNI.RegnOutData_orgn_set(swigCPtr, this, value);
  }

  public float[] getOrgn() {
    return temcoreJNI.RegnOutData_orgn_get(swigCPtr, this);
  }

  public void setAvln(float[] value) {
    temcoreJNI.RegnOutData_avln_set(swigCPtr, this, value);
  }

  public float[] getAvln() {
    return temcoreJNI.RegnOutData_avln_get(swigCPtr, this);
  }

  public void setNetnmin(float[] value) {
    temcoreJNI.RegnOutData_netnmin_set(swigCPtr, this, value);
  }

  public float[] getNetnmin() {
    return temcoreJNI.RegnOutData_netnmin_get(swigCPtr, this);
  }

  public void setNuptake(float[] value) {
    temcoreJNI.RegnOutData_nuptake_set(swigCPtr, this, value);
  }

  public float[] getNuptake() {
    return temcoreJNI.RegnOutData_nuptake_get(swigCPtr, this);
  }

  public void setNinput(float[] value) {
    temcoreJNI.RegnOutData_ninput_set(swigCPtr, this, value);
  }

  public float[] getNinput() {
    return temcoreJNI.RegnOutData_ninput_get(swigCPtr, this);
  }

  public void setNlost(float[] value) {
    temcoreJNI.RegnOutData_nlost_set(swigCPtr, this, value);
  }

  public float[] getNlost() {
    return temcoreJNI.RegnOutData_nlost_get(swigCPtr, this);
  }

  public void setEet(float[] value) {
    temcoreJNI.RegnOutData_eet_set(swigCPtr, this, value);
  }

  public float[] getEet() {
    return temcoreJNI.RegnOutData_eet_get(swigCPtr, this);
  }

  public void setPet(float[] value) {
    temcoreJNI.RegnOutData_pet_set(swigCPtr, this, value);
  }

  public float[] getPet() {
    return temcoreJNI.RegnOutData_pet_get(swigCPtr, this);
  }

  public void setQdrain(float[] value) {
    temcoreJNI.RegnOutData_qdrain_set(swigCPtr, this, value);
  }

  public float[] getQdrain() {
    return temcoreJNI.RegnOutData_qdrain_get(swigCPtr, this);
  }

  public void setQrunoff(float[] value) {
    temcoreJNI.RegnOutData_qrunoff_set(swigCPtr, this, value);
  }

  public float[] getQrunoff() {
    return temcoreJNI.RegnOutData_qrunoff_get(swigCPtr, this);
  }

  public void setSnowthick(float[] value) {
    temcoreJNI.RegnOutData_snowthick_set(swigCPtr, this, value);
  }

  public float[] getSnowthick() {
    return temcoreJNI.RegnOutData_snowthick_get(swigCPtr, this);
  }

  public void setSwe(float[] value) {
    temcoreJNI.RegnOutData_swe_set(swigCPtr, this, value);
  }

  public float[] getSwe() {
    return temcoreJNI.RegnOutData_swe_get(swigCPtr, this);
  }

  public void setWtd(float[] value) {
    temcoreJNI.RegnOutData_wtd_set(swigCPtr, this, value);
  }

  public float[] getWtd() {
    return temcoreJNI.RegnOutData_wtd_get(swigCPtr, this);
  }

  public void setAld(float[] value) {
    temcoreJNI.RegnOutData_ald_set(swigCPtr, this, value);
  }

  public float[] getAld() {
    return temcoreJNI.RegnOutData_ald_get(swigCPtr, this);
  }

  public void setVwcshlw(float[] value) {
    temcoreJNI.RegnOutData_vwcshlw_set(swigCPtr, this, value);
  }

  public float[] getVwcshlw() {
    return temcoreJNI.RegnOutData_vwcshlw_get(swigCPtr, this);
  }

  public void setVwcdeep(float[] value) {
    temcoreJNI.RegnOutData_vwcdeep_set(swigCPtr, this, value);
  }

  public float[] getVwcdeep() {
    return temcoreJNI.RegnOutData_vwcdeep_get(swigCPtr, this);
  }

  public void setVwcminetop(float[] value) {
    temcoreJNI.RegnOutData_vwcminetop_set(swigCPtr, this, value);
  }

  public float[] getVwcminetop() {
    return temcoreJNI.RegnOutData_vwcminetop_get(swigCPtr, this);
  }

  public void setVwcminebot(float[] value) {
    temcoreJNI.RegnOutData_vwcminebot_set(swigCPtr, this, value);
  }

  public float[] getVwcminebot() {
    return temcoreJNI.RegnOutData_vwcminebot_get(swigCPtr, this);
  }

  public void setTshlw(float[] value) {
    temcoreJNI.RegnOutData_tshlw_set(swigCPtr, this, value);
  }

  public float[] getTshlw() {
    return temcoreJNI.RegnOutData_tshlw_get(swigCPtr, this);
  }

  public void setTdeep(float[] value) {
    temcoreJNI.RegnOutData_tdeep_set(swigCPtr, this, value);
  }

  public float[] getTdeep() {
    return temcoreJNI.RegnOutData_tdeep_get(swigCPtr, this);
  }

  public void setTminetop(float[] value) {
    temcoreJNI.RegnOutData_tminetop_set(swigCPtr, this, value);
  }

  public float[] getTminetop() {
    return temcoreJNI.RegnOutData_tminetop_get(swigCPtr, this);
  }

  public void setTminebot(float[] value) {
    temcoreJNI.RegnOutData_tminebot_set(swigCPtr, this, value);
  }

  public float[] getTminebot() {
    return temcoreJNI.RegnOutData_tminebot_get(swigCPtr, this);
  }

  public void setHkshlw(float[] value) {
    temcoreJNI.RegnOutData_hkshlw_set(swigCPtr, this, value);
  }

  public float[] getHkshlw() {
    return temcoreJNI.RegnOutData_hkshlw_get(swigCPtr, this);
  }

  public void setHkdeep(float[] value) {
    temcoreJNI.RegnOutData_hkdeep_set(swigCPtr, this, value);
  }

  public float[] getHkdeep() {
    return temcoreJNI.RegnOutData_hkdeep_get(swigCPtr, this);
  }

  public void setHkminetop(float[] value) {
    temcoreJNI.RegnOutData_hkminetop_set(swigCPtr, this, value);
  }

  public float[] getHkminetop() {
    return temcoreJNI.RegnOutData_hkminetop_get(swigCPtr, this);
  }

  public void setHkminebot(float[] value) {
    temcoreJNI.RegnOutData_hkminebot_set(swigCPtr, this, value);
  }

  public float[] getHkminebot() {
    return temcoreJNI.RegnOutData_hkminebot_get(swigCPtr, this);
  }

  public void setTcshlw(float[] value) {
    temcoreJNI.RegnOutData_tcshlw_set(swigCPtr, this, value);
  }

  public float[] getTcshlw() {
    return temcoreJNI.RegnOutData_tcshlw_get(swigCPtr, this);
  }

  public void setTcdeep(float[] value) {
    temcoreJNI.RegnOutData_tcdeep_set(swigCPtr, this, value);
  }

  public float[] getTcdeep() {
    return temcoreJNI.RegnOutData_tcdeep_get(swigCPtr, this);
  }

  public void setTcminetop(float[] value) {
    temcoreJNI.RegnOutData_tcminetop_set(swigCPtr, this, value);
  }

  public float[] getTcminetop() {
    return temcoreJNI.RegnOutData_tcminetop_get(swigCPtr, this);
  }

  public void setTcminebot(float[] value) {
    temcoreJNI.RegnOutData_tcminebot_set(swigCPtr, this, value);
  }

  public float[] getTcminebot() {
    return temcoreJNI.RegnOutData_tcminebot_get(swigCPtr, this);
  }

  public void setTrock34(float[] value) {
    temcoreJNI.RegnOutData_trock34_set(swigCPtr, this, value);
  }

  public float[] getTrock34() {
    return temcoreJNI.RegnOutData_trock34_get(swigCPtr, this);
  }

  public void setSomcald(float[] value) {
    temcoreJNI.RegnOutData_somcald_set(swigCPtr, this, value);
  }

  public float[] getSomcald() {
    return temcoreJNI.RegnOutData_somcald_get(swigCPtr, this);
  }

  public void setVwcald(float[] value) {
    temcoreJNI.RegnOutData_vwcald_set(swigCPtr, this, value);
  }

  public float[] getVwcald() {
    return temcoreJNI.RegnOutData_vwcald_get(swigCPtr, this);
  }

  public void setTald(float[] value) {
    temcoreJNI.RegnOutData_tald_set(swigCPtr, this, value);
  }

  public float[] getTald() {
    return temcoreJNI.RegnOutData_tald_get(swigCPtr, this);
  }

}
