/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class RestartData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RestartData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RestartData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_RestartData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RestartData() {
    this(temcoreJNI.new_RestartData(), true);
  }

  public void reinitValue() {
    temcoreJNI.RestartData_reinitValue(swigCPtr, this);
  }

  public void setChtid(int value) {
    temcoreJNI.RestartData_chtid_set(swigCPtr, this, value);
  }

  public int getChtid() {
    return temcoreJNI.RestartData_chtid_get(swigCPtr, this);
  }

  public void setPerma(int value) {
    temcoreJNI.RestartData_perma_set(swigCPtr, this, value);
  }

  public int getPerma() {
    return temcoreJNI.RestartData_perma_get(swigCPtr, this);
  }

  public void setTSsnow(double[] value) {
    temcoreJNI.RestartData_TSsnow_set(swigCPtr, this, value);
  }

  public double[] getTSsnow() {
    return temcoreJNI.RestartData_TSsnow_get(swigCPtr, this);
  }

  public void setDZsnow(double[] value) {
    temcoreJNI.RestartData_DZsnow_set(swigCPtr, this, value);
  }

  public double[] getDZsnow() {
    return temcoreJNI.RestartData_DZsnow_get(swigCPtr, this);
  }

  public void setLIQsnow(double[] value) {
    temcoreJNI.RestartData_LIQsnow_set(swigCPtr, this, value);
  }

  public double[] getLIQsnow() {
    return temcoreJNI.RestartData_LIQsnow_get(swigCPtr, this);
  }

  public void setRHOsnow(double[] value) {
    temcoreJNI.RestartData_RHOsnow_set(swigCPtr, this, value);
  }

  public double[] getRHOsnow() {
    return temcoreJNI.RestartData_RHOsnow_get(swigCPtr, this);
  }

  public void setICEsnow(double[] value) {
    temcoreJNI.RestartData_ICEsnow_set(swigCPtr, this, value);
  }

  public double[] getICEsnow() {
    return temcoreJNI.RestartData_ICEsnow_get(swigCPtr, this);
  }

  public void setAGEsnow(double[] value) {
    temcoreJNI.RestartData_AGEsnow_set(swigCPtr, this, value);
  }

  public double[] getAGEsnow() {
    return temcoreJNI.RestartData_AGEsnow_get(swigCPtr, this);
  }

  public void setTSsoil(double[] value) {
    temcoreJNI.RestartData_TSsoil_set(swigCPtr, this, value);
  }

  public double[] getTSsoil() {
    return temcoreJNI.RestartData_TSsoil_get(swigCPtr, this);
  }

  public void setDZsoil(double[] value) {
    temcoreJNI.RestartData_DZsoil_set(swigCPtr, this, value);
  }

  public double[] getDZsoil() {
    return temcoreJNI.RestartData_DZsoil_get(swigCPtr, this);
  }

  public void setLIQsoil(double[] value) {
    temcoreJNI.RestartData_LIQsoil_set(swigCPtr, this, value);
  }

  public double[] getLIQsoil() {
    return temcoreJNI.RestartData_LIQsoil_get(swigCPtr, this);
  }

  public void setICEsoil(double[] value) {
    temcoreJNI.RestartData_ICEsoil_set(swigCPtr, this, value);
  }

  public double[] getICEsoil() {
    return temcoreJNI.RestartData_ICEsoil_get(swigCPtr, this);
  }

  public void setFROZENsoil(int[] value) {
    temcoreJNI.RestartData_FROZENsoil_set(swigCPtr, this, value);
  }

  public int[] getFROZENsoil() {
    return temcoreJNI.RestartData_FROZENsoil_get(swigCPtr, this);
  }

  public void setTYPEsoil(int[] value) {
    temcoreJNI.RestartData_TYPEsoil_set(swigCPtr, this, value);
  }

  public int[] getTYPEsoil() {
    return temcoreJNI.RestartData_TYPEsoil_get(swigCPtr, this);
  }

  public void setNONCsoil(double[] value) {
    temcoreJNI.RestartData_NONCsoil_set(swigCPtr, this, value);
  }

  public double[] getNONCsoil() {
    return temcoreJNI.RestartData_NONCsoil_get(swigCPtr, this);
  }

  public void setREACsoil(double[] value) {
    temcoreJNI.RestartData_REACsoil_set(swigCPtr, this, value);
  }

  public double[] getREACsoil() {
    return temcoreJNI.RestartData_REACsoil_get(swigCPtr, this);
  }

  public void setToptA(double[] value) {
    temcoreJNI.RestartData_toptA_set(swigCPtr, this, value);
  }

  public double[] getToptA() {
    return temcoreJNI.RestartData_toptA_get(swigCPtr, this);
  }

  public void setEetmxA(double[] value) {
    temcoreJNI.RestartData_eetmxA_set(swigCPtr, this, value);
  }

  public double[] getEetmxA() {
    return temcoreJNI.RestartData_eetmxA_get(swigCPtr, this);
  }

  public void setPetmxA(double[] value) {
    temcoreJNI.RestartData_petmxA_set(swigCPtr, this, value);
  }

  public double[] getPetmxA() {
    return temcoreJNI.RestartData_petmxA_get(swigCPtr, this);
  }

  public void setUnnormleafmxA(double[] value) {
    temcoreJNI.RestartData_unnormleafmxA_set(swigCPtr, this, value);
  }

  public double[] getUnnormleafmxA() {
    return temcoreJNI.RestartData_unnormleafmxA_get(swigCPtr, this);
  }

  public void setTYPEmin(int[] value) {
    temcoreJNI.RestartData_TYPEmin_set(swigCPtr, this, value);
  }

  public int[] getTYPEmin() {
    return temcoreJNI.RestartData_TYPEmin_get(swigCPtr, this);
  }

  public void setTSrock(double[] value) {
    temcoreJNI.RestartData_TSrock_set(swigCPtr, this, value);
  }

  public double[] getTSrock() {
    return temcoreJNI.RestartData_TSrock_get(swigCPtr, this);
  }

  public void setDZrock(double[] value) {
    temcoreJNI.RestartData_DZrock_set(swigCPtr, this, value);
  }

  public double[] getDZrock() {
    return temcoreJNI.RestartData_DZrock_get(swigCPtr, this);
  }

  public void setFrontZ(double[] value) {
    temcoreJNI.RestartData_frontZ_set(swigCPtr, this, value);
  }

  public double[] getFrontZ() {
    return temcoreJNI.RestartData_frontZ_get(swigCPtr, this);
  }

  public void setFrontFT(int[] value) {
    temcoreJNI.RestartData_frontFT_set(swigCPtr, this, value);
  }

  public int[] getFrontFT() {
    return temcoreJNI.RestartData_frontFT_get(swigCPtr, this);
  }

  public void setSoln(double value) {
    temcoreJNI.RestartData_soln_set(swigCPtr, this, value);
  }

  public double getSoln() {
    return temcoreJNI.RestartData_soln_get(swigCPtr, this);
  }

  public void setAvln(double value) {
    temcoreJNI.RestartData_avln_set(swigCPtr, this, value);
  }

  public double getAvln() {
    return temcoreJNI.RestartData_avln_get(swigCPtr, this);
  }

  public void setWdebris(double value) {
    temcoreJNI.RestartData_wdebris_set(swigCPtr, this, value);
  }

  public double getWdebris() {
    return temcoreJNI.RestartData_wdebris_get(swigCPtr, this);
  }

  public void setStrn(double value) {
    temcoreJNI.RestartData_strn_set(swigCPtr, this, value);
  }

  public double getStrn() {
    return temcoreJNI.RestartData_strn_get(swigCPtr, this);
  }

  public void setSton(double value) {
    temcoreJNI.RestartData_ston_set(swigCPtr, this, value);
  }

  public double getSton() {
    return temcoreJNI.RestartData_ston_get(swigCPtr, this);
  }

  public void setVegc(double value) {
    temcoreJNI.RestartData_vegc_set(swigCPtr, this, value);
  }

  public double getVegc() {
    return temcoreJNI.RestartData_vegc_get(swigCPtr, this);
  }

  public void setDeadc(double value) {
    temcoreJNI.RestartData_deadc_set(swigCPtr, this, value);
  }

  public double getDeadc() {
    return temcoreJNI.RestartData_deadc_get(swigCPtr, this);
  }

  public void setDeadn(double value) {
    temcoreJNI.RestartData_deadn_set(swigCPtr, this, value);
  }

  public double getDeadn() {
    return temcoreJNI.RestartData_deadn_get(swigCPtr, this);
  }

  public void setPrveetmx(double value) {
    temcoreJNI.RestartData_prveetmx_set(swigCPtr, this, value);
  }

  public double getPrveetmx() {
    return temcoreJNI.RestartData_prveetmx_get(swigCPtr, this);
  }

  public void setPrvpetmx(double value) {
    temcoreJNI.RestartData_prvpetmx_set(swigCPtr, this, value);
  }

  public double getPrvpetmx() {
    return temcoreJNI.RestartData_prvpetmx_get(swigCPtr, this);
  }

  public void setUnnormleaf(double value) {
    temcoreJNI.RestartData_unnormleaf_set(swigCPtr, this, value);
  }

  public double getUnnormleaf() {
    return temcoreJNI.RestartData_unnormleaf_get(swigCPtr, this);
  }

  public void setPrvunnormleafmx(double value) {
    temcoreJNI.RestartData_prvunnormleafmx_set(swigCPtr, this, value);
  }

  public double getPrvunnormleafmx() {
    return temcoreJNI.RestartData_prvunnormleafmx_get(swigCPtr, this);
  }

  public void setPrvtopt(double value) {
    temcoreJNI.RestartData_prvtopt_set(swigCPtr, this, value);
  }

  public double getPrvtopt() {
    return temcoreJNI.RestartData_prvtopt_get(swigCPtr, this);
  }

  public void setC2n(double value) {
    temcoreJNI.RestartData_c2n_set(swigCPtr, this, value);
  }

  public double getC2n() {
    return temcoreJNI.RestartData_c2n_get(swigCPtr, this);
  }

  public void setKdfib(double value) {
    temcoreJNI.RestartData_kdfib_set(swigCPtr, this, value);
  }

  public double getKdfib() {
    return temcoreJNI.RestartData_kdfib_get(swigCPtr, this);
  }

  public void setKdhum(double value) {
    temcoreJNI.RestartData_kdhum_set(swigCPtr, this, value);
  }

  public double getKdhum() {
    return temcoreJNI.RestartData_kdhum_get(swigCPtr, this);
  }

  public void setKdmin(double value) {
    temcoreJNI.RestartData_kdmin_set(swigCPtr, this, value);
  }

  public double getKdmin() {
    return temcoreJNI.RestartData_kdmin_get(swigCPtr, this);
  }

  public void setKdslow(double value) {
    temcoreJNI.RestartData_kdslow_set(swigCPtr, this, value);
  }

  public double getKdslow() {
    return temcoreJNI.RestartData_kdslow_get(swigCPtr, this);
  }

  public void setFoliagemx(double value) {
    temcoreJNI.RestartData_foliagemx_set(swigCPtr, this, value);
  }

  public double getFoliagemx() {
    return temcoreJNI.RestartData_foliagemx_get(swigCPtr, this);
  }

  public void setYsf(int value) {
    temcoreJNI.RestartData_ysf_set(swigCPtr, this, value);
  }

  public int getYsf() {
    return temcoreJNI.RestartData_ysf_get(swigCPtr, this);
  }

  public void setBurnedn(double value) {
    temcoreJNI.RestartData_burnedn_set(swigCPtr, this, value);
  }

  public double getBurnedn() {
    return temcoreJNI.RestartData_burnedn_get(swigCPtr, this);
  }

  public void setLai(double value) {
    temcoreJNI.RestartData_lai_set(swigCPtr, this, value);
  }

  public double getLai() {
    return temcoreJNI.RestartData_lai_get(swigCPtr, this);
  }

}
