/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public final class RUNMODE {
  public final static RUNMODE I_CALIB = new RUNMODE("I_CALIB");
  public final static RUNMODE I_SITE = new RUNMODE("I_SITE");
  public final static RUNMODE I_REGION = new RUNMODE("I_REGION");
  public final static RUNMODE I_SENSI = new RUNMODE("I_SENSI");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static RUNMODE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + RUNMODE.class + " with value " + swigValue);
  }

  private RUNMODE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private RUNMODE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private RUNMODE(String swigName, RUNMODE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static RUNMODE[] swigValues = { I_CALIB, I_SITE, I_REGION, I_SENSI };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

