/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class SiteIn {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SiteIn(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SiteIn obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_SiteIn(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SiteIn() {
    this(temcoreJNI.new_SiteIn(), true);
  }

  public void setSiteid(int value) {
    temcoreJNI.SiteIn_siteid_set(swigCPtr, this, value);
  }

  public int getSiteid() {
    return temcoreJNI.SiteIn_siteid_get(swigCPtr, this);
  }

  public void setYsf(int value) {
    temcoreJNI.SiteIn_ysf_set(swigCPtr, this, value);
  }

  public int getYsf() {
    return temcoreJNI.SiteIn_ysf_get(swigCPtr, this);
  }

  public void setLai(float[] value) {
    temcoreJNI.SiteIn_lai_set(swigCPtr, this, value);
  }

  public float[] getLai() {
    return temcoreJNI.SiteIn_lai_get(swigCPtr, this);
  }

  public void setVegc(float value) {
    temcoreJNI.SiteIn_vegc_set(swigCPtr, this, value);
  }

  public float getVegc() {
    return temcoreJNI.SiteIn_vegc_get(swigCPtr, this);
  }

  public void setVegn(float value) {
    temcoreJNI.SiteIn_vegn_set(swigCPtr, this, value);
  }

  public float getVegn() {
    return temcoreJNI.SiteIn_vegn_get(swigCPtr, this);
  }

  public void setMossthick(float value) {
    temcoreJNI.SiteIn_mossthick_set(swigCPtr, this, value);
  }

  public float getMossthick() {
    return temcoreJNI.SiteIn_mossthick_get(swigCPtr, this);
  }

  public void setFibthick(float value) {
    temcoreJNI.SiteIn_fibthick_set(swigCPtr, this, value);
  }

  public float getFibthick() {
    return temcoreJNI.SiteIn_fibthick_get(swigCPtr, this);
  }

  public void setHumthick(float value) {
    temcoreJNI.SiteIn_humthick_set(swigCPtr, this, value);
  }

  public float getHumthick() {
    return temcoreJNI.SiteIn_humthick_get(swigCPtr, this);
  }

  public void setSoilc(float value) {
    temcoreJNI.SiteIn_soilc_set(swigCPtr, this, value);
  }

  public float getSoilc() {
    return temcoreJNI.SiteIn_soilc_get(swigCPtr, this);
  }

  public void setFibc(float value) {
    temcoreJNI.SiteIn_fibc_set(swigCPtr, this, value);
  }

  public float getFibc() {
    return temcoreJNI.SiteIn_fibc_get(swigCPtr, this);
  }

  public void setHumc(float value) {
    temcoreJNI.SiteIn_humc_set(swigCPtr, this, value);
  }

  public float getHumc() {
    return temcoreJNI.SiteIn_humc_get(swigCPtr, this);
  }

  public void setMinc(float value) {
    temcoreJNI.SiteIn_minc_set(swigCPtr, this, value);
  }

  public float getMinc() {
    return temcoreJNI.SiteIn_minc_get(swigCPtr, this);
  }

  public void setOrgn(float value) {
    temcoreJNI.SiteIn_orgn_set(swigCPtr, this, value);
  }

  public float getOrgn() {
    return temcoreJNI.SiteIn_orgn_get(swigCPtr, this);
  }

  public void setAvln(float value) {
    temcoreJNI.SiteIn_avln_set(swigCPtr, this, value);
  }

  public float getAvln() {
    return temcoreJNI.SiteIn_avln_get(swigCPtr, this);
  }

  public void setMintype(int[] value) {
    temcoreJNI.SiteIn_mintype_set(swigCPtr, this, value);
  }

  public int[] getMintype() {
    return temcoreJNI.SiteIn_mintype_get(swigCPtr, this);
  }

  public void setInitz(float[] value) {
    temcoreJNI.SiteIn_initz_set(swigCPtr, this, value);
  }

  public float[] getInitz() {
    return temcoreJNI.SiteIn_initz_get(swigCPtr, this);
  }

  public void setInitst(float[] value) {
    temcoreJNI.SiteIn_initst_set(swigCPtr, this, value);
  }

  public float[] getInitst() {
    return temcoreJNI.SiteIn_initst_get(swigCPtr, this);
  }

  public void setInitsm(float[] value) {
    temcoreJNI.SiteIn_initsm_set(swigCPtr, this, value);
  }

  public float[] getInitsm() {
    return temcoreJNI.SiteIn_initsm_get(swigCPtr, this);
  }

}
