/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class SnowSoilOutData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SnowSoilOutData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SnowSoilOutData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_SnowSoilOutData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SnowSoilOutData() {
    this(temcoreJNI.new_SnowSoilOutData(), true);
  }

  public void setErrord(int value) {
    temcoreJNI.SnowSoilOutData_errord_set(swigCPtr, this, value);
  }

  public int getErrord() {
    return temcoreJNI.SnowSoilOutData_errord_get(swigCPtr, this);
  }

  public void setInfild(float[] value) {
    temcoreJNI.SnowSoilOutData_infild_set(swigCPtr, this, value);
  }

  public float[] getInfild() {
    return temcoreJNI.SnowSoilOutData_infild_get(swigCPtr, this);
  }

  public void setWtd(float[] value) {
    temcoreJNI.SnowSoilOutData_wtd_set(swigCPtr, this, value);
  }

  public float[] getWtd() {
    return temcoreJNI.SnowSoilOutData_wtd_get(swigCPtr, this);
  }

  public void setFsatd(float[] value) {
    temcoreJNI.SnowSoilOutData_fsatd_set(swigCPtr, this, value);
  }

  public float[] getFsatd() {
    return temcoreJNI.SnowSoilOutData_fsatd_get(swigCPtr, this);
  }

  public void setQoverd(float[] value) {
    temcoreJNI.SnowSoilOutData_qoverd_set(swigCPtr, this, value);
  }

  public float[] getQoverd() {
    return temcoreJNI.SnowSoilOutData_qoverd_get(swigCPtr, this);
  }

  public void setQdraind(float[] value) {
    temcoreJNI.SnowSoilOutData_qdraind_set(swigCPtr, this, value);
  }

  public float[] getQdraind() {
    return temcoreJNI.SnowSoilOutData_qdraind_get(swigCPtr, this);
  }

  public void setGrowd(float[] value) {
    temcoreJNI.SnowSoilOutData_growd_set(swigCPtr, this, value);
  }

  public float[] getGrowd() {
    return temcoreJNI.SnowSoilOutData_growd_get(swigCPtr, this);
  }

  public void setSlradrefld(float[] value) {
    temcoreJNI.SnowSoilOutData_slradrefld_set(swigCPtr, this, value);
  }

  public float[] getSlradrefld() {
    return temcoreJNI.SnowSoilOutData_slradrefld_get(swigCPtr, this);
  }

  public void setSevapd(float[] value) {
    temcoreJNI.SnowSoilOutData_sevapd_set(swigCPtr, this, value);
  }

  public float[] getSevapd() {
    return temcoreJNI.SnowSoilOutData_sevapd_get(swigCPtr, this);
  }

  public void setTsd(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_tsd_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getTsd() {
    long cPtr = temcoreJNI.SnowSoilOutData_tsd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setTcondd(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_tcondd_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getTcondd() {
    long cPtr = temcoreJNI.SnowSoilOutData_tcondd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setLiqd(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_liqd_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getLiqd() {
    long cPtr = temcoreJNI.SnowSoilOutData_liqd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setIced(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_iced_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getIced() {
    long cPtr = temcoreJNI.SnowSoilOutData_iced_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setFrzfnt(SWIGTYPE_p_a_MAX_NUM_FNT__float value) {
    temcoreJNI.SnowSoilOutData_frzfnt_set(swigCPtr, this, SWIGTYPE_p_a_MAX_NUM_FNT__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_NUM_FNT__float getFrzfnt() {
    long cPtr = temcoreJNI.SnowSoilOutData_frzfnt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_NUM_FNT__float(cPtr, false);
  }

  public void setThwfnt(SWIGTYPE_p_a_MAX_NUM_FNT__float value) {
    temcoreJNI.SnowSoilOutData_thwfnt_set(swigCPtr, this, SWIGTYPE_p_a_MAX_NUM_FNT__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_NUM_FNT__float getThwfnt() {
    long cPtr = temcoreJNI.SnowSoilOutData_thwfnt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_NUM_FNT__float(cPtr, false);
  }

  public void setNumiter(float[] value) {
    temcoreJNI.SnowSoilOutData_numiter_set(swigCPtr, this, value);
  }

  public float[] getNumiter() {
    return temcoreJNI.SnowSoilOutData_numiter_get(swigCPtr, this);
  }

  public void setNumiterliq(float[] value) {
    temcoreJNI.SnowSoilOutData_numiterliq_set(swigCPtr, this, value);
  }

  public float[] getNumiterliq() {
    return temcoreJNI.SnowSoilOutData_numiterliq_get(swigCPtr, this);
  }

  public void setSnowthick(float[] value) {
    temcoreJNI.SnowSoilOutData_snowthick_set(swigCPtr, this, value);
  }

  public float[] getSnowthick() {
    return temcoreJNI.SnowSoilOutData_snowthick_get(swigCPtr, this);
  }

  public void setSwed(float[] value) {
    temcoreJNI.SnowSoilOutData_swed_set(swigCPtr, this, value);
  }

  public float[] getSwed() {
    return temcoreJNI.SnowSoilOutData_swed_get(swigCPtr, this);
  }

  public void setSmeltd(float[] value) {
    temcoreJNI.SnowSoilOutData_smeltd_set(swigCPtr, this, value);
  }

  public float[] getSmeltd() {
    return temcoreJNI.SnowSoilOutData_smeltd_get(swigCPtr, this);
  }

  public void setSsubld(float[] value) {
    temcoreJNI.SnowSoilOutData_ssubld_set(swigCPtr, this, value);
  }

  public float[] getSsubld() {
    return temcoreJNI.SnowSoilOutData_ssubld_get(swigCPtr, this);
  }

  public void setSnradrefld(float[] value) {
    temcoreJNI.SnowSoilOutData_snradrefld_set(swigCPtr, this, value);
  }

  public float[] getSnradrefld() {
    return temcoreJNI.SnowSoilOutData_snradrefld_get(swigCPtr, this);
  }

  public void setAldd(float[] value) {
    temcoreJNI.SnowSoilOutData_aldd_set(swigCPtr, this, value);
  }

  public float[] getAldd() {
    return temcoreJNI.SnowSoilOutData_aldd_get(swigCPtr, this);
  }

  public void setErrorm(int value) {
    temcoreJNI.SnowSoilOutData_errorm_set(swigCPtr, this, value);
  }

  public int getErrorm() {
    return temcoreJNI.SnowSoilOutData_errorm_get(swigCPtr, this);
  }

  public void setDz(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_dz_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getDz() {
    long cPtr = temcoreJNI.SnowSoilOutData_dz_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setTs(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_ts_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getTs() {
    long cPtr = temcoreJNI.SnowSoilOutData_ts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setLiq(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_liq_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getLiq() {
    long cPtr = temcoreJNI.SnowSoilOutData_liq_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setVwc(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_vwc_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getVwc() {
    long cPtr = temcoreJNI.SnowSoilOutData_vwc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setIce(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_ice_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getIce() {
    long cPtr = temcoreJNI.SnowSoilOutData_ice_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setAld(float[] value) {
    temcoreJNI.SnowSoilOutData_ald_set(swigCPtr, this, value);
  }

  public float[] getAld() {
    return temcoreJNI.SnowSoilOutData_ald_get(swigCPtr, this);
  }

  public void setSsubl(float[] value) {
    temcoreJNI.SnowSoilOutData_ssubl_set(swigCPtr, this, value);
  }

  public float[] getSsubl() {
    return temcoreJNI.SnowSoilOutData_ssubl_get(swigCPtr, this);
  }

  public void setSninfl(float[] value) {
    temcoreJNI.SnowSoilOutData_sninfl_set(swigCPtr, this, value);
  }

  public float[] getSninfl() {
    return temcoreJNI.SnowSoilOutData_sninfl_get(swigCPtr, this);
  }

  public void setSevap(float[] value) {
    temcoreJNI.SnowSoilOutData_sevap_set(swigCPtr, this, value);
  }

  public float[] getSevap() {
    return temcoreJNI.SnowSoilOutData_sevap_get(swigCPtr, this);
  }

  public void setWatertab(float[] value) {
    temcoreJNI.SnowSoilOutData_watertab_set(swigCPtr, this, value);
  }

  public float[] getWatertab() {
    return temcoreJNI.SnowSoilOutData_watertab_get(swigCPtr, this);
  }

  public void setMossdz(float[] value) {
    temcoreJNI.SnowSoilOutData_mossdz_set(swigCPtr, this, value);
  }

  public float[] getMossdz() {
    return temcoreJNI.SnowSoilOutData_mossdz_get(swigCPtr, this);
  }

  public void setShlwdz(float[] value) {
    temcoreJNI.SnowSoilOutData_shlwdz_set(swigCPtr, this, value);
  }

  public float[] getShlwdz() {
    return temcoreJNI.SnowSoilOutData_shlwdz_get(swigCPtr, this);
  }

  public void setDeepdz(float[] value) {
    temcoreJNI.SnowSoilOutData_deepdz_set(swigCPtr, this, value);
  }

  public float[] getDeepdz() {
    return temcoreJNI.SnowSoilOutData_deepdz_get(swigCPtr, this);
  }

  public void setZ(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_z_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getZ() {
    long cPtr = temcoreJNI.SnowSoilOutData_z_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setPor(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_por_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getPor() {
    long cPtr = temcoreJNI.SnowSoilOutData_por_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setType(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_type_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getType() {
    long cPtr = temcoreJNI.SnowSoilOutData_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setReac(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_reac_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getReac() {
    long cPtr = temcoreJNI.SnowSoilOutData_reac_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setNonc(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_nonc_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getNonc() {
    long cPtr = temcoreJNI.SnowSoilOutData_nonc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setRrh(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_rrh_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getRrh() {
    long cPtr = temcoreJNI.SnowSoilOutData_rrh_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setNrh(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_nrh_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getNrh() {
    long cPtr = temcoreJNI.SnowSoilOutData_nrh_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setRhmoist(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_rhmoist_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getRhmoist() {
    long cPtr = temcoreJNI.SnowSoilOutData_rhmoist_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setRhq10(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_rhq10_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getRhq10() {
    long cPtr = temcoreJNI.SnowSoilOutData_rhq10_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setKsoil(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_ksoil_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getKsoil() {
    long cPtr = temcoreJNI.SnowSoilOutData_ksoil_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setKdl(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_kdl_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getKdl() {
    long cPtr = temcoreJNI.SnowSoilOutData_kdl_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setKdr(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_kdr_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getKdr() {
    long cPtr = temcoreJNI.SnowSoilOutData_kdr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setKdn(SWIGTYPE_p_a_MAX_OUT_SOI__float value) {
    temcoreJNI.SnowSoilOutData_kdn_set(swigCPtr, this, SWIGTYPE_p_a_MAX_OUT_SOI__float.getCPtr(value));
  }

  public SWIGTYPE_p_a_MAX_OUT_SOI__float getKdn() {
    long cPtr = temcoreJNI.SnowSoilOutData_kdn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_MAX_OUT_SOI__float(cPtr, false);
  }

  public void setNinput(float[] value) {
    temcoreJNI.SnowSoilOutData_ninput_set(swigCPtr, this, value);
  }

  public float[] getNinput() {
    return temcoreJNI.SnowSoilOutData_ninput_get(swigCPtr, this);
  }

  public void setNlost(float[] value) {
    temcoreJNI.SnowSoilOutData_nlost_set(swigCPtr, this, value);
  }

  public float[] getNlost() {
    return temcoreJNI.SnowSoilOutData_nlost_get(swigCPtr, this);
  }

  public void setNetnmin(float[] value) {
    temcoreJNI.SnowSoilOutData_netnmin_set(swigCPtr, this, value);
  }

  public float[] getNetnmin() {
    return temcoreJNI.SnowSoilOutData_netnmin_get(swigCPtr, this);
  }

  public void setNimmob(float[] value) {
    temcoreJNI.SnowSoilOutData_nimmob_set(swigCPtr, this, value);
  }

  public float[] getNimmob() {
    return temcoreJNI.SnowSoilOutData_nimmob_get(swigCPtr, this);
  }

  public void setOrgn(float[] value) {
    temcoreJNI.SnowSoilOutData_orgn_set(swigCPtr, this, value);
  }

  public float[] getOrgn() {
    return temcoreJNI.SnowSoilOutData_orgn_get(swigCPtr, this);
  }

  public void setAvln(float[] value) {
    temcoreJNI.SnowSoilOutData_avln_set(swigCPtr, this, value);
  }

  public float[] getAvln() {
    return temcoreJNI.SnowSoilOutData_avln_get(swigCPtr, this);
  }

  public void setReacsum(float[] value) {
    temcoreJNI.SnowSoilOutData_reacsum_set(swigCPtr, this, value);
  }

  public float[] getReacsum() {
    return temcoreJNI.SnowSoilOutData_reacsum_get(swigCPtr, this);
  }

  public void setNoncsum(float[] value) {
    temcoreJNI.SnowSoilOutData_noncsum_set(swigCPtr, this, value);
  }

  public float[] getNoncsum() {
    return temcoreJNI.SnowSoilOutData_noncsum_get(swigCPtr, this);
  }

  public void setShlwcsum(float[] value) {
    temcoreJNI.SnowSoilOutData_shlwcsum_set(swigCPtr, this, value);
  }

  public float[] getShlwcsum() {
    return temcoreJNI.SnowSoilOutData_shlwcsum_get(swigCPtr, this);
  }

  public void setDeepcsum(float[] value) {
    temcoreJNI.SnowSoilOutData_deepcsum_set(swigCPtr, this, value);
  }

  public float[] getDeepcsum() {
    return temcoreJNI.SnowSoilOutData_deepcsum_get(swigCPtr, this);
  }

  public void setMinecsum(float[] value) {
    temcoreJNI.SnowSoilOutData_minecsum_set(swigCPtr, this, value);
  }

  public float[] getMinecsum() {
    return temcoreJNI.SnowSoilOutData_minecsum_get(swigCPtr, this);
  }

  public void setGrowpct(float[] value) {
    temcoreJNI.SnowSoilOutData_growpct_set(swigCPtr, this, value);
  }

  public float[] getGrowpct() {
    return temcoreJNI.SnowSoilOutData_growpct_get(swigCPtr, this);
  }

  public void setErrory(int value) {
    temcoreJNI.SnowSoilOutData_errory_set(swigCPtr, this, value);
  }

  public int getErrory() {
    return temcoreJNI.SnowSoilOutData_errory_get(swigCPtr, this);
  }

  public void setYrsevap(float value) {
    temcoreJNI.SnowSoilOutData_yrsevap_set(swigCPtr, this, value);
  }

  public float getYrsevap() {
    return temcoreJNI.SnowSoilOutData_yrsevap_get(swigCPtr, this);
  }

  public void setYrqover(float value) {
    temcoreJNI.SnowSoilOutData_yrqover_set(swigCPtr, this, value);
  }

  public float getYrqover() {
    return temcoreJNI.SnowSoilOutData_yrqover_get(swigCPtr, this);
  }

  public void setYrqdrain(float value) {
    temcoreJNI.SnowSoilOutData_yrqdrain_set(swigCPtr, this, value);
  }

  public float getYrqdrain() {
    return temcoreJNI.SnowSoilOutData_yrqdrain_get(swigCPtr, this);
  }

  public void setYrssubl(float value) {
    temcoreJNI.SnowSoilOutData_yrssubl_set(swigCPtr, this, value);
  }

  public float getYrssubl() {
    return temcoreJNI.SnowSoilOutData_yrssubl_get(swigCPtr, this);
  }

  public void setYrliqsum(float value) {
    temcoreJNI.SnowSoilOutData_yrliqsum_set(swigCPtr, this, value);
  }

  public float getYrliqsum() {
    return temcoreJNI.SnowSoilOutData_yrliqsum_get(swigCPtr, this);
  }

  public void setYricesum(float value) {
    temcoreJNI.SnowSoilOutData_yricesum_set(swigCPtr, this, value);
  }

  public float getYricesum() {
    return temcoreJNI.SnowSoilOutData_yricesum_get(swigCPtr, this);
  }

  public void setYrtsave(float value) {
    temcoreJNI.SnowSoilOutData_yrtsave_set(swigCPtr, this, value);
  }

  public float getYrtsave() {
    return temcoreJNI.SnowSoilOutData_yrtsave_get(swigCPtr, this);
  }

  public void setYrvwcmin10(float value) {
    temcoreJNI.SnowSoilOutData_yrvwcmin10_set(swigCPtr, this, value);
  }

  public float getYrvwcmin10() {
    return temcoreJNI.SnowSoilOutData_yrvwcmin10_get(swigCPtr, this);
  }

  public void setYrvwcshlw(float value) {
    temcoreJNI.SnowSoilOutData_yrvwcshlw_set(swigCPtr, this, value);
  }

  public float getYrvwcshlw() {
    return temcoreJNI.SnowSoilOutData_yrvwcshlw_get(swigCPtr, this);
  }

  public void setYrvwcdeep(float value) {
    temcoreJNI.SnowSoilOutData_yrvwcdeep_set(swigCPtr, this, value);
  }

  public float getYrvwcdeep() {
    return temcoreJNI.SnowSoilOutData_yrvwcdeep_get(swigCPtr, this);
  }

  public void setYrvwcmine(float value) {
    temcoreJNI.SnowSoilOutData_yrvwcmine_set(swigCPtr, this, value);
  }

  public float getYrvwcmine() {
    return temcoreJNI.SnowSoilOutData_yrvwcmine_get(swigCPtr, this);
  }

  public void setYrtmin10(float value) {
    temcoreJNI.SnowSoilOutData_yrtmin10_set(swigCPtr, this, value);
  }

  public float getYrtmin10() {
    return temcoreJNI.SnowSoilOutData_yrtmin10_get(swigCPtr, this);
  }

  public void setYrtshlw(float value) {
    temcoreJNI.SnowSoilOutData_yrtshlw_set(swigCPtr, this, value);
  }

  public float getYrtshlw() {
    return temcoreJNI.SnowSoilOutData_yrtshlw_get(swigCPtr, this);
  }

  public void setYrtdeep(float value) {
    temcoreJNI.SnowSoilOutData_yrtdeep_set(swigCPtr, this, value);
  }

  public float getYrtdeep() {
    return temcoreJNI.SnowSoilOutData_yrtdeep_get(swigCPtr, this);
  }

  public void setYrtmine(float value) {
    temcoreJNI.SnowSoilOutData_yrtmine_set(swigCPtr, this, value);
  }

  public float getYrtmine() {
    return temcoreJNI.SnowSoilOutData_yrtmine_get(swigCPtr, this);
  }

  public void setYrald(float value) {
    temcoreJNI.SnowSoilOutData_yrald_set(swigCPtr, this, value);
  }

  public float getYrald() {
    return temcoreJNI.SnowSoilOutData_yrald_get(swigCPtr, this);
  }

  public void setYrperm(float value) {
    temcoreJNI.SnowSoilOutData_yrperm_set(swigCPtr, this, value);
  }

  public float getYrperm() {
    return temcoreJNI.SnowSoilOutData_yrperm_get(swigCPtr, this);
  }

  public void setYrmossdz(float value) {
    temcoreJNI.SnowSoilOutData_yrmossdz_set(swigCPtr, this, value);
  }

  public float getYrmossdz() {
    return temcoreJNI.SnowSoilOutData_yrmossdz_get(swigCPtr, this);
  }

  public void setYrshlwdz(float value) {
    temcoreJNI.SnowSoilOutData_yrshlwdz_set(swigCPtr, this, value);
  }

  public float getYrshlwdz() {
    return temcoreJNI.SnowSoilOutData_yrshlwdz_get(swigCPtr, this);
  }

  public void setYrdeepdz(float value) {
    temcoreJNI.SnowSoilOutData_yrdeepdz_set(swigCPtr, this, value);
  }

  public float getYrdeepdz() {
    return temcoreJNI.SnowSoilOutData_yrdeepdz_get(swigCPtr, this);
  }

  public void setYrwatertab(float value) {
    temcoreJNI.SnowSoilOutData_yrwatertab_set(swigCPtr, this, value);
  }

  public float getYrwatertab() {
    return temcoreJNI.SnowSoilOutData_yrwatertab_get(swigCPtr, this);
  }

  public void setYrmossnum(float value) {
    temcoreJNI.SnowSoilOutData_yrmossnum_set(swigCPtr, this, value);
  }

  public float getYrmossnum() {
    return temcoreJNI.SnowSoilOutData_yrmossnum_get(swigCPtr, this);
  }

  public void setYrshlwnum(float value) {
    temcoreJNI.SnowSoilOutData_yrshlwnum_set(swigCPtr, this, value);
  }

  public float getYrshlwnum() {
    return temcoreJNI.SnowSoilOutData_yrshlwnum_get(swigCPtr, this);
  }

  public void setYrdeepnum(float value) {
    temcoreJNI.SnowSoilOutData_yrdeepnum_set(swigCPtr, this, value);
  }

  public float getYrdeepnum() {
    return temcoreJNI.SnowSoilOutData_yrdeepnum_get(swigCPtr, this);
  }

  public void setYrnetnmin(float value) {
    temcoreJNI.SnowSoilOutData_yrnetnmin_set(swigCPtr, this, value);
  }

  public float getYrnetnmin() {
    return temcoreJNI.SnowSoilOutData_yrnetnmin_get(swigCPtr, this);
  }

  public void setYrrrhsum(float value) {
    temcoreJNI.SnowSoilOutData_yrrrhsum_set(swigCPtr, this, value);
  }

  public float getYrrrhsum() {
    return temcoreJNI.SnowSoilOutData_yrrrhsum_get(swigCPtr, this);
  }

  public void setYrnrhsum(float value) {
    temcoreJNI.SnowSoilOutData_yrnrhsum_set(swigCPtr, this, value);
  }

  public float getYrnrhsum() {
    return temcoreJNI.SnowSoilOutData_yrnrhsum_get(swigCPtr, this);
  }

  public void setYrreacsum(float value) {
    temcoreJNI.SnowSoilOutData_yrreacsum_set(swigCPtr, this, value);
  }

  public float getYrreacsum() {
    return temcoreJNI.SnowSoilOutData_yrreacsum_get(swigCPtr, this);
  }

  public void setYrnoncsum(float value) {
    temcoreJNI.SnowSoilOutData_yrnoncsum_set(swigCPtr, this, value);
  }

  public float getYrnoncsum() {
    return temcoreJNI.SnowSoilOutData_yrnoncsum_get(swigCPtr, this);
  }

  public void setYrshlwcsum(float value) {
    temcoreJNI.SnowSoilOutData_yrshlwcsum_set(swigCPtr, this, value);
  }

  public float getYrshlwcsum() {
    return temcoreJNI.SnowSoilOutData_yrshlwcsum_get(swigCPtr, this);
  }

  public void setYrdeepcsum(float value) {
    temcoreJNI.SnowSoilOutData_yrdeepcsum_set(swigCPtr, this, value);
  }

  public float getYrdeepcsum() {
    return temcoreJNI.SnowSoilOutData_yrdeepcsum_get(swigCPtr, this);
  }

  public void setYrminecsum(float value) {
    temcoreJNI.SnowSoilOutData_yrminecsum_set(swigCPtr, this, value);
  }

  public float getYrminecsum() {
    return temcoreJNI.SnowSoilOutData_yrminecsum_get(swigCPtr, this);
  }

  public void setYrorgn(float value) {
    temcoreJNI.SnowSoilOutData_yrorgn_set(swigCPtr, this, value);
  }

  public float getYrorgn() {
    return temcoreJNI.SnowSoilOutData_yrorgn_get(swigCPtr, this);
  }

  public void setYravln(float value) {
    temcoreJNI.SnowSoilOutData_yravln_set(swigCPtr, this, value);
  }

  public float getYravln() {
    return temcoreJNI.SnowSoilOutData_yravln_get(swigCPtr, this);
  }

  public void setYrsnuptake(float value) {
    temcoreJNI.SnowSoilOutData_yrsnuptake_set(swigCPtr, this, value);
  }

  public float getYrsnuptake() {
    return temcoreJNI.SnowSoilOutData_yrsnuptake_get(swigCPtr, this);
  }

  public void setYrwdebris(float value) {
    temcoreJNI.SnowSoilOutData_yrwdebris_set(swigCPtr, this, value);
  }

  public float getYrwdebris() {
    return temcoreJNI.SnowSoilOutData_yrwdebris_get(swigCPtr, this);
  }

  public void setYrwdrh(float value) {
    temcoreJNI.SnowSoilOutData_yrwdrh_set(swigCPtr, this, value);
  }

  public float getYrwdrh() {
    return temcoreJNI.SnowSoilOutData_yrwdrh_get(swigCPtr, this);
  }

  public void setYrninput(float value) {
    temcoreJNI.SnowSoilOutData_yrninput_set(swigCPtr, this, value);
  }

  public float getYrninput() {
    return temcoreJNI.SnowSoilOutData_yrninput_get(swigCPtr, this);
  }

  public void setYrnlost(float value) {
    temcoreJNI.SnowSoilOutData_yrnlost_set(swigCPtr, this, value);
  }

  public float getYrnlost() {
    return temcoreJNI.SnowSoilOutData_yrnlost_get(swigCPtr, this);
  }

  public void setYrburnthick(float value) {
    temcoreJNI.SnowSoilOutData_yrburnthick_set(swigCPtr, this, value);
  }

  public float getYrburnthick() {
    return temcoreJNI.SnowSoilOutData_yrburnthick_get(swigCPtr, this);
  }

  public void setYrburnsoilc(float value) {
    temcoreJNI.SnowSoilOutData_yrburnsoilc_set(swigCPtr, this, value);
  }

  public float getYrburnsoilc() {
    return temcoreJNI.SnowSoilOutData_yrburnsoilc_get(swigCPtr, this);
  }

  public void setYrburnsoiln(float value) {
    temcoreJNI.SnowSoilOutData_yrburnsoiln_set(swigCPtr, this, value);
  }

  public float getYrburnsoiln() {
    return temcoreJNI.SnowSoilOutData_yrburnsoiln_get(swigCPtr, this);
  }

  public void setYrorgnreturn(float value) {
    temcoreJNI.SnowSoilOutData_yrorgnreturn_set(swigCPtr, this, value);
  }

  public float getYrorgnreturn() {
    return temcoreJNI.SnowSoilOutData_yrorgnreturn_get(swigCPtr, this);
  }

  public void setTs1D(float[] value) {
    temcoreJNI.SnowSoilOutData_ts1D_set(swigCPtr, this, value);
  }

  public float[] getTs1D() {
    return temcoreJNI.SnowSoilOutData_ts1D_get(swigCPtr, this);
  }

  public void setLiq1D(float[] value) {
    temcoreJNI.SnowSoilOutData_liq1D_set(swigCPtr, this, value);
  }

  public float[] getLiq1D() {
    return temcoreJNI.SnowSoilOutData_liq1D_get(swigCPtr, this);
  }

  public void setVwc1D(float[] value) {
    temcoreJNI.SnowSoilOutData_vwc1D_set(swigCPtr, this, value);
  }

  public float[] getVwc1D() {
    return temcoreJNI.SnowSoilOutData_vwc1D_get(swigCPtr, this);
  }

  public void setIce1D(float[] value) {
    temcoreJNI.SnowSoilOutData_ice1D_set(swigCPtr, this, value);
  }

  public float[] getIce1D() {
    return temcoreJNI.SnowSoilOutData_ice1D_get(swigCPtr, this);
  }

  public void setDz1D(float[] value) {
    temcoreJNI.SnowSoilOutData_dz1D_set(swigCPtr, this, value);
  }

  public float[] getDz1D() {
    return temcoreJNI.SnowSoilOutData_dz1D_get(swigCPtr, this);
  }

  public void setZ1D(float[] value) {
    temcoreJNI.SnowSoilOutData_z1D_set(swigCPtr, this, value);
  }

  public float[] getZ1D() {
    return temcoreJNI.SnowSoilOutData_z1D_get(swigCPtr, this);
  }

  public void setPor1D(float[] value) {
    temcoreJNI.SnowSoilOutData_por1D_set(swigCPtr, this, value);
  }

  public float[] getPor1D() {
    return temcoreJNI.SnowSoilOutData_por1D_get(swigCPtr, this);
  }

  public void setType1D(float[] value) {
    temcoreJNI.SnowSoilOutData_type1D_set(swigCPtr, this, value);
  }

  public float[] getType1D() {
    return temcoreJNI.SnowSoilOutData_type1D_get(swigCPtr, this);
  }

  public void setReac1D(float[] value) {
    temcoreJNI.SnowSoilOutData_reac1D_set(swigCPtr, this, value);
  }

  public float[] getReac1D() {
    return temcoreJNI.SnowSoilOutData_reac1D_get(swigCPtr, this);
  }

  public void setRrh1D(float[] value) {
    temcoreJNI.SnowSoilOutData_rrh1D_set(swigCPtr, this, value);
  }

  public float[] getRrh1D() {
    return temcoreJNI.SnowSoilOutData_rrh1D_get(swigCPtr, this);
  }

  public void setNonc1D(float[] value) {
    temcoreJNI.SnowSoilOutData_nonc1D_set(swigCPtr, this, value);
  }

  public float[] getNonc1D() {
    return temcoreJNI.SnowSoilOutData_nonc1D_get(swigCPtr, this);
  }

  public void setNrh1D(float[] value) {
    temcoreJNI.SnowSoilOutData_nrh1D_set(swigCPtr, this, value);
  }

  public float[] getNrh1D() {
    return temcoreJNI.SnowSoilOutData_nrh1D_get(swigCPtr, this);
  }

  public void setRhmoist1D(float[] value) {
    temcoreJNI.SnowSoilOutData_rhmoist1D_set(swigCPtr, this, value);
  }

  public float[] getRhmoist1D() {
    return temcoreJNI.SnowSoilOutData_rhmoist1D_get(swigCPtr, this);
  }

  public void setRhq101D(float[] value) {
    temcoreJNI.SnowSoilOutData_rhq101D_set(swigCPtr, this, value);
  }

  public float[] getRhq101D() {
    return temcoreJNI.SnowSoilOutData_rhq101D_get(swigCPtr, this);
  }

  public void setKsoil1D(float[] value) {
    temcoreJNI.SnowSoilOutData_ksoil1D_set(swigCPtr, this, value);
  }

  public float[] getKsoil1D() {
    return temcoreJNI.SnowSoilOutData_ksoil1D_get(swigCPtr, this);
  }

  public void setKdl1D(float[] value) {
    temcoreJNI.SnowSoilOutData_kdl1D_set(swigCPtr, this, value);
  }

  public float[] getKdl1D() {
    return temcoreJNI.SnowSoilOutData_kdl1D_get(swigCPtr, this);
  }

  public void setKdr1D(float[] value) {
    temcoreJNI.SnowSoilOutData_kdr1D_set(swigCPtr, this, value);
  }

  public float[] getKdr1D() {
    return temcoreJNI.SnowSoilOutData_kdr1D_get(swigCPtr, this);
  }

  public void setKdn1D(float[] value) {
    temcoreJNI.SnowSoilOutData_kdn1D_set(swigCPtr, this, value);
  }

  public float[] getKdn1D() {
    return temcoreJNI.SnowSoilOutData_kdn1D_get(swigCPtr, this);
  }

  public void setSnz1D(float[] value) {
    temcoreJNI.SnowSoilOutData_snz1D_set(swigCPtr, this, value);
  }

  public float[] getSnz1D() {
    return temcoreJNI.SnowSoilOutData_snz1D_get(swigCPtr, this);
  }

  public void setFrzfnt1D(float[] value) {
    temcoreJNI.SnowSoilOutData_frzfnt1D_set(swigCPtr, this, value);
  }

  public float[] getFrzfnt1D() {
    return temcoreJNI.SnowSoilOutData_frzfnt1D_get(swigCPtr, this);
  }

  public void setThwfnt1D(float[] value) {
    temcoreJNI.SnowSoilOutData_thwfnt1D_set(swigCPtr, this, value);
  }

  public float[] getThwfnt1D() {
    return temcoreJNI.SnowSoilOutData_thwfnt1D_get(swigCPtr, this);
  }

  public void setLiqd1D(float[] value) {
    temcoreJNI.SnowSoilOutData_liqd1D_set(swigCPtr, this, value);
  }

  public float[] getLiqd1D() {
    return temcoreJNI.SnowSoilOutData_liqd1D_get(swigCPtr, this);
  }

  public void setTcondd1D(float[] value) {
    temcoreJNI.SnowSoilOutData_tcondd1D_set(swigCPtr, this, value);
  }

  public float[] getTcondd1D() {
    return temcoreJNI.SnowSoilOutData_tcondd1D_get(swigCPtr, this);
  }

  public void setIced1D(float[] value) {
    temcoreJNI.SnowSoilOutData_iced1D_set(swigCPtr, this, value);
  }

  public float[] getIced1D() {
    return temcoreJNI.SnowSoilOutData_iced1D_get(swigCPtr, this);
  }

  public void setTsd1D(float[] value) {
    temcoreJNI.SnowSoilOutData_tsd1D_set(swigCPtr, this, value);
  }

  public float[] getTsd1D() {
    return temcoreJNI.SnowSoilOutData_tsd1D_get(swigCPtr, this);
  }

}
