/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class snw2atm_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected snw2atm_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(snw2atm_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_snw2atm_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSublim(double value) {
    temcoreJNI.snw2atm_env_sublim_set(swigCPtr, this, value);
  }

  public double getSublim() {
    return temcoreJNI.snw2atm_env_sublim_get(swigCPtr, this);
  }

  public void setSolrad(double value) {
    temcoreJNI.snw2atm_env_solrad_set(swigCPtr, this, value);
  }

  public double getSolrad() {
    return temcoreJNI.snw2atm_env_solrad_get(swigCPtr, this);
  }

  public snw2atm_env() {
    this(temcoreJNI.new_snw2atm_env(), true);
  }

}
