/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class snwdiag_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected snwdiag_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(snwdiag_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_snwdiag_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDense(double value) {
    temcoreJNI.snwdiag_env_dense_set(swigCPtr, this, value);
  }

  public double getDense() {
    return temcoreJNI.snwdiag_env_dense_get(swigCPtr, this);
  }

  public void setMelt(double value) {
    temcoreJNI.snwdiag_env_melt_set(swigCPtr, this, value);
  }

  public double getMelt() {
    return temcoreJNI.snwdiag_env_melt_get(swigCPtr, this);
  }

  public snwdiag_env() {
    this(temcoreJNI.new_snwdiag_env(), true);
  }

}
