/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class snwstate_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected snwstate_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(snwstate_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_snwstate_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setThick(double value) {
    temcoreJNI.snwstate_env_thick_set(swigCPtr, this, value);
  }

  public double getThick() {
    return temcoreJNI.snwstate_env_thick_get(swigCPtr, this);
  }

  public void setSwe(double value) {
    temcoreJNI.snwstate_env_swe_set(swigCPtr, this, value);
  }

  public double getSwe() {
    return temcoreJNI.snwstate_env_swe_get(swigCPtr, this);
  }

  public snwstate_env() {
    this(temcoreJNI.new_snwstate_env(), true);
  }

}
