/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soi2atm_fir {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soi2atm_fir(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soi2atm_fir obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soi2atm_fir(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOrgc(double value) {
    temcoreJNI.soi2atm_fir_orgc_set(swigCPtr, this, value);
  }

  public double getOrgc() {
    return temcoreJNI.soi2atm_fir_orgc_get(swigCPtr, this);
  }

  public void setOrgn(double value) {
    temcoreJNI.soi2atm_fir_orgn_set(swigCPtr, this, value);
  }

  public double getOrgn() {
    return temcoreJNI.soi2atm_fir_orgn_get(swigCPtr, this);
  }

  public soi2atm_fir() {
    this(temcoreJNI.new_soi2atm_fir(), true);
  }

}
