/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soi2atm_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soi2atm_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soi2atm_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soi2atm_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEvap(double value) {
    temcoreJNI.soi2atm_env_evap_set(swigCPtr, this, value);
  }

  public double getEvap() {
    return temcoreJNI.soi2atm_env_evap_get(swigCPtr, this);
  }

  public void setTrans(double value) {
    temcoreJNI.soi2atm_env_trans_set(swigCPtr, this, value);
  }

  public double getTrans() {
    return temcoreJNI.soi2atm_env_trans_get(swigCPtr, this);
  }

  public void setSolrad(double value) {
    temcoreJNI.soi2atm_env_solrad_set(swigCPtr, this, value);
  }

  public double getSolrad() {
    return temcoreJNI.soi2atm_env_solrad_get(swigCPtr, this);
  }

  public soi2atm_env() {
    this(temcoreJNI.new_soi2atm_env(), true);
  }

}
