/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soi2atm_bgc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soi2atm_bgc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soi2atm_bgc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soi2atm_bgc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRrh(double[] value) {
    temcoreJNI.soi2atm_bgc_rrh_set(swigCPtr, this, value);
  }

  public double[] getRrh() {
    return temcoreJNI.soi2atm_bgc_rrh_get(swigCPtr, this);
  }

  public void setNrh(double[] value) {
    temcoreJNI.soi2atm_bgc_nrh_set(swigCPtr, this, value);
  }

  public double[] getNrh() {
    return temcoreJNI.soi2atm_bgc_nrh_get(swigCPtr, this);
  }

  public void setWdrh(double value) {
    temcoreJNI.soi2atm_bgc_wdrh_set(swigCPtr, this, value);
  }

  public double getWdrh() {
    return temcoreJNI.soi2atm_bgc_wdrh_get(swigCPtr, this);
  }

  public soi2atm_bgc() {
    this(temcoreJNI.new_soi2atm_bgc(), true);
  }

}
