/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soi2veg_bgc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soi2veg_bgc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soi2veg_bgc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soi2veg_bgc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInnuptake(double value) {
    temcoreJNI.soi2veg_bgc_innuptake_set(swigCPtr, this, value);
  }

  public double getInnuptake() {
    return temcoreJNI.soi2veg_bgc_innuptake_get(swigCPtr, this);
  }

  public void setNuptake(double value) {
    temcoreJNI.soi2veg_bgc_nuptake_set(swigCPtr, this, value);
  }

  public double getNuptake() {
    return temcoreJNI.soi2veg_bgc_nuptake_get(swigCPtr, this);
  }

  public void setSuptake(double value) {
    temcoreJNI.soi2veg_bgc_suptake_set(swigCPtr, this, value);
  }

  public double getSuptake() {
    return temcoreJNI.soi2veg_bgc_suptake_get(swigCPtr, this);
  }

  public void setLuptake(double value) {
    temcoreJNI.soi2veg_bgc_luptake_set(swigCPtr, this, value);
  }

  public double getLuptake() {
    return temcoreJNI.soi2veg_bgc_luptake_get(swigCPtr, this);
  }

  public soi2veg_bgc() {
    this(temcoreJNI.new_soi2veg_bgc(), true);
  }

}
