/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soidiag_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soidiag_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soidiag_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soidiag_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGrowpct(double value) {
    temcoreJNI.soidiag_env_growpct_set(swigCPtr, this, value);
  }

  public double getGrowpct() {
    return temcoreJNI.soidiag_env_growpct_get(swigCPtr, this);
  }

  public void setWatertab(double value) {
    temcoreJNI.soidiag_env_watertab_set(swigCPtr, this, value);
  }

  public double getWatertab() {
    return temcoreJNI.soidiag_env_watertab_get(swigCPtr, this);
  }

  public void setFrasat(double value) {
    temcoreJNI.soidiag_env_frasat_set(swigCPtr, this, value);
  }

  public double getFrasat() {
    return temcoreJNI.soidiag_env_frasat_get(swigCPtr, this);
  }

  public void setItnum(double value) {
    temcoreJNI.soidiag_env_itnum_set(swigCPtr, this, value);
  }

  public double getItnum() {
    return temcoreJNI.soidiag_env_itnum_get(swigCPtr, this);
  }

  public void setItnumliq(double value) {
    temcoreJNI.soidiag_env_itnumliq_set(swigCPtr, this, value);
  }

  public double getItnumliq() {
    return temcoreJNI.soidiag_env_itnumliq_get(swigCPtr, this);
  }

  public void setBtran(double value) {
    temcoreJNI.soidiag_env_btran_set(swigCPtr, this, value);
  }

  public double getBtran() {
    return temcoreJNI.soidiag_env_btran_get(swigCPtr, this);
  }

  public void setDegday10(double value) {
    temcoreJNI.soidiag_env_degday10_set(swigCPtr, this, value);
  }

  public double getDegday10() {
    return temcoreJNI.soidiag_env_degday10_get(swigCPtr, this);
  }

  public void setNfactor(double value) {
    temcoreJNI.soidiag_env_nfactor_set(swigCPtr, this, value);
  }

  public double getNfactor() {
    return temcoreJNI.soidiag_env_nfactor_get(swigCPtr, this);
  }

  public void setPermafrost(int value) {
    temcoreJNI.soidiag_env_permafrost_set(swigCPtr, this, value);
  }

  public int getPermafrost() {
    return temcoreJNI.soidiag_env_permafrost_get(swigCPtr, this);
  }

  public void setGrowstart(int value) {
    temcoreJNI.soidiag_env_growstart_set(swigCPtr, this, value);
  }

  public int getGrowstart() {
    return temcoreJNI.soidiag_env_growstart_get(swigCPtr, this);
  }

  public void setSnowfree1st(int value) {
    temcoreJNI.soidiag_env_snowfree1st_set(swigCPtr, this, value);
  }

  public int getSnowfree1st() {
    return temcoreJNI.soidiag_env_snowfree1st_get(swigCPtr, this);
  }

  public void setGrowend(int value) {
    temcoreJNI.soidiag_env_growend_set(swigCPtr, this, value);
  }

  public int getGrowend() {
    return temcoreJNI.soidiag_env_growend_get(swigCPtr, this);
  }

  public void setTmineral10cm(double value) {
    temcoreJNI.soidiag_env_tmineral10cm_set(swigCPtr, this, value);
  }

  public double getTmineral10cm() {
    return temcoreJNI.soidiag_env_tmineral10cm_get(swigCPtr, this);
  }

  public void setTrock34m(double value) {
    temcoreJNI.soidiag_env_trock34m_set(swigCPtr, this, value);
  }

  public double getTrock34m() {
    return temcoreJNI.soidiag_env_trock34m_get(swigCPtr, this);
  }

  public void setUnfrzcolumn(double value) {
    temcoreJNI.soidiag_env_unfrzcolumn_set(swigCPtr, this, value);
  }

  public double getUnfrzcolumn() {
    return temcoreJNI.soidiag_env_unfrzcolumn_get(swigCPtr, this);
  }

  public void setAllvwc(double[] value) {
    temcoreJNI.soidiag_env_allvwc_set(swigCPtr, this, value);
  }

  public double[] getAllvwc() {
    return temcoreJNI.soidiag_env_allvwc_get(swigCPtr, this);
  }

  public void setAlliwc(double[] value) {
    temcoreJNI.soidiag_env_alliwc_set(swigCPtr, this, value);
  }

  public double[] getAlliwc() {
    return temcoreJNI.soidiag_env_alliwc_get(swigCPtr, this);
  }

  public void setAlllwc(double[] value) {
    temcoreJNI.soidiag_env_alllwc_set(swigCPtr, this, value);
  }

  public double[] getAlllwc() {
    return temcoreJNI.soidiag_env_alllwc_get(swigCPtr, this);
  }

  public void setAllsws(double[] value) {
    temcoreJNI.soidiag_env_allsws_set(swigCPtr, this, value);
  }

  public double[] getAllsws() {
    return temcoreJNI.soidiag_env_allsws_get(swigCPtr, this);
  }

  public void setAllaws(double[] value) {
    temcoreJNI.soidiag_env_allaws_set(swigCPtr, this, value);
  }

  public double[] getAllaws() {
    return temcoreJNI.soidiag_env_allaws_get(swigCPtr, this);
  }

  public void setHcond(double[] value) {
    temcoreJNI.soidiag_env_hcond_set(swigCPtr, this, value);
  }

  public double[] getHcond() {
    return temcoreJNI.soidiag_env_hcond_get(swigCPtr, this);
  }

  public void setMinliq(double[] value) {
    temcoreJNI.soidiag_env_minliq_set(swigCPtr, this, value);
  }

  public double[] getMinliq() {
    return temcoreJNI.soidiag_env_minliq_get(swigCPtr, this);
  }

  public void setTem(double[] value) {
    temcoreJNI.soidiag_env_tem_set(swigCPtr, this, value);
  }

  public double[] getTem() {
    return temcoreJNI.soidiag_env_tem_get(swigCPtr, this);
  }

  public void setTcond(double[] value) {
    temcoreJNI.soidiag_env_tcond_set(swigCPtr, this, value);
  }

  public double[] getTcond() {
    return temcoreJNI.soidiag_env_tcond_get(swigCPtr, this);
  }

  public void setFrzfnt(double[] value) {
    temcoreJNI.soidiag_env_frzfnt_set(swigCPtr, this, value);
  }

  public double[] getFrzfnt() {
    return temcoreJNI.soidiag_env_frzfnt_get(swigCPtr, this);
  }

  public void setThwfnt(double[] value) {
    temcoreJNI.soidiag_env_thwfnt_set(swigCPtr, this, value);
  }

  public double[] getThwfnt() {
    return temcoreJNI.soidiag_env_thwfnt_get(swigCPtr, this);
  }

  public void setActual_num_soil(int value) {
    temcoreJNI.soidiag_env_actual_num_soil_set(swigCPtr, this, value);
  }

  public int getActual_num_soil() {
    return temcoreJNI.soidiag_env_actual_num_soil_get(swigCPtr, this);
  }

  public void setMossthick(double value) {
    temcoreJNI.soidiag_env_mossthick_set(swigCPtr, this, value);
  }

  public double getMossthick() {
    return temcoreJNI.soidiag_env_mossthick_get(swigCPtr, this);
  }

  public void setShlwthick(double value) {
    temcoreJNI.soidiag_env_shlwthick_set(swigCPtr, this, value);
  }

  public double getShlwthick() {
    return temcoreJNI.soidiag_env_shlwthick_get(swigCPtr, this);
  }

  public void setDeepthick(double value) {
    temcoreJNI.soidiag_env_deepthick_set(swigCPtr, this, value);
  }

  public double getDeepthick() {
    return temcoreJNI.soidiag_env_deepthick_get(swigCPtr, this);
  }

  public void setMinethick(double value) {
    temcoreJNI.soidiag_env_minethick_set(swigCPtr, this, value);
  }

  public double getMinethick() {
    return temcoreJNI.soidiag_env_minethick_get(swigCPtr, this);
  }

  public void setMossnum(double value) {
    temcoreJNI.soidiag_env_mossnum_set(swigCPtr, this, value);
  }

  public double getMossnum() {
    return temcoreJNI.soidiag_env_mossnum_get(swigCPtr, this);
  }

  public void setShlwnum(double value) {
    temcoreJNI.soidiag_env_shlwnum_set(swigCPtr, this, value);
  }

  public double getShlwnum() {
    return temcoreJNI.soidiag_env_shlwnum_get(swigCPtr, this);
  }

  public void setDeepnum(double value) {
    temcoreJNI.soidiag_env_deepnum_set(swigCPtr, this, value);
  }

  public double getDeepnum() {
    return temcoreJNI.soidiag_env_deepnum_get(swigCPtr, this);
  }

  public void setMaxrootratio(double value) {
    temcoreJNI.soidiag_env_maxrootratio_set(swigCPtr, this, value);
  }

  public double getMaxrootratio() {
    return temcoreJNI.soidiag_env_maxrootratio_get(swigCPtr, this);
  }

  public void setMaxrootind(int value) {
    temcoreJNI.soidiag_env_maxrootind_set(swigCPtr, this, value);
  }

  public int getMaxrootind() {
    return temcoreJNI.soidiag_env_maxrootind_get(swigCPtr, this);
  }

  public soidiag_env() {
    this(temcoreJNI.new_soidiag_env(), true);
  }

}
