/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soidiag_fir {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soidiag_fir(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soidiag_fir obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soidiag_fir(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBurnthick(double value) {
    temcoreJNI.soidiag_fir_burnthick_set(swigCPtr, this, value);
  }

  public double getBurnthick() {
    return temcoreJNI.soidiag_fir_burnthick_get(swigCPtr, this);
  }

  public soidiag_fir() {
    this(temcoreJNI.new_soidiag_fir(), true);
  }

}
