/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soidiag_bgc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soidiag_bgc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soidiag_bgc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soidiag_bgc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKsoil(double[] value) {
    temcoreJNI.soidiag_bgc_ksoil_set(swigCPtr, this, value);
  }

  public double[] getKsoil() {
    return temcoreJNI.soidiag_bgc_ksoil_get(swigCPtr, this);
  }

  public void setRhmoist(double[] value) {
    temcoreJNI.soidiag_bgc_rhmoist_set(swigCPtr, this, value);
  }

  public double[] getRhmoist() {
    return temcoreJNI.soidiag_bgc_rhmoist_get(swigCPtr, this);
  }

  public void setRhq10(double[] value) {
    temcoreJNI.soidiag_bgc_rhq10_set(swigCPtr, this, value);
  }

  public double[] getRhq10() {
    return temcoreJNI.soidiag_bgc_rhq10_get(swigCPtr, this);
  }

  public void setFrprod_frac(double[] value) {
    temcoreJNI.soidiag_bgc_frprod_frac_set(swigCPtr, this, value);
  }

  public double[] getFrprod_frac() {
    return temcoreJNI.soidiag_bgc_frprod_frac_get(swigCPtr, this);
  }

  public void setTotc(double[] value) {
    temcoreJNI.soidiag_bgc_totc_set(swigCPtr, this, value);
  }

  public double[] getTotc() {
    return temcoreJNI.soidiag_bgc_totc_get(swigCPtr, this);
  }

  public void setReacsum(double value) {
    temcoreJNI.soidiag_bgc_reacsum_set(swigCPtr, this, value);
  }

  public double getReacsum() {
    return temcoreJNI.soidiag_bgc_reacsum_get(swigCPtr, this);
  }

  public void setNoncsum(double value) {
    temcoreJNI.soidiag_bgc_noncsum_set(swigCPtr, this, value);
  }

  public double getNoncsum() {
    return temcoreJNI.soidiag_bgc_noncsum_get(swigCPtr, this);
  }

  public void setRrhsum(double value) {
    temcoreJNI.soidiag_bgc_rrhsum_set(swigCPtr, this, value);
  }

  public double getRrhsum() {
    return temcoreJNI.soidiag_bgc_rrhsum_get(swigCPtr, this);
  }

  public void setNrhsum(double value) {
    temcoreJNI.soidiag_bgc_nrhsum_set(swigCPtr, this, value);
  }

  public double getNrhsum() {
    return temcoreJNI.soidiag_bgc_nrhsum_get(swigCPtr, this);
  }

  public void setShlwc(double value) {
    temcoreJNI.soidiag_bgc_shlwc_set(swigCPtr, this, value);
  }

  public double getShlwc() {
    return temcoreJNI.soidiag_bgc_shlwc_get(swigCPtr, this);
  }

  public void setDeepc(double value) {
    temcoreJNI.soidiag_bgc_deepc_set(swigCPtr, this, value);
  }

  public double getDeepc() {
    return temcoreJNI.soidiag_bgc_deepc_get(swigCPtr, this);
  }

  public void setMinec(double value) {
    temcoreJNI.soidiag_bgc_minec_set(swigCPtr, this, value);
  }

  public double getMinec() {
    return temcoreJNI.soidiag_bgc_minec_get(swigCPtr, this);
  }

  public void setKdl(double[] value) {
    temcoreJNI.soidiag_bgc_kdl_set(swigCPtr, this, value);
  }

  public double[] getKdl() {
    return temcoreJNI.soidiag_bgc_kdl_get(swigCPtr, this);
  }

  public void setKdr(double[] value) {
    temcoreJNI.soidiag_bgc_kdr_set(swigCPtr, this, value);
  }

  public double[] getKdr() {
    return temcoreJNI.soidiag_bgc_kdr_get(swigCPtr, this);
  }

  public void setKdn(double[] value) {
    temcoreJNI.soidiag_bgc_kdn_set(swigCPtr, this, value);
  }

  public double[] getKdn() {
    return temcoreJNI.soidiag_bgc_kdn_get(swigCPtr, this);
  }

  public soidiag_bgc() {
    this(temcoreJNI.new_soidiag_bgc(), true);
  }

}
