/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soipar_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soipar_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soipar_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soipar_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPsimax(float value) {
    temcoreJNI.soipar_env_psimax_set(swigCPtr, this, value);
  }

  public float getPsimax() {
    return temcoreJNI.soipar_env_psimax_get(swigCPtr, this);
  }

  public void setRootmass(float value) {
    temcoreJNI.soipar_env_rootmass_set(swigCPtr, this, value);
  }

  public float getRootmass() {
    return temcoreJNI.soipar_env_rootmass_get(swigCPtr, this);
  }

  public void setRootbeta(float value) {
    temcoreJNI.soipar_env_rootbeta_set(swigCPtr, this, value);
  }

  public float getRootbeta() {
    return temcoreJNI.soipar_env_rootbeta_get(swigCPtr, this);
  }

  public void setRootdp4infil(float value) {
    temcoreJNI.soipar_env_rootdp4infil_set(swigCPtr, this, value);
  }

  public float getRootdp4infil() {
    return temcoreJNI.soipar_env_rootdp4infil_get(swigCPtr, this);
  }

  public void setRichardl(float value) {
    temcoreJNI.soipar_env_richardl_set(swigCPtr, this, value);
  }

  public float getRichardl() {
    return temcoreJNI.soipar_env_richardl_get(swigCPtr, this);
  }

  public void setRootdp4gpp(float value) {
    temcoreJNI.soipar_env_rootdp4gpp_set(swigCPtr, this, value);
  }

  public float getRootdp4gpp() {
    return temcoreJNI.soipar_env_rootdp4gpp_get(swigCPtr, this);
  }

  public void setFrprod_frac(float[] value) {
    temcoreJNI.soipar_env_frprod_frac_set(swigCPtr, this, value);
  }

  public float[] getFrprod_frac() {
    return temcoreJNI.soipar_env_frprod_frac_get(swigCPtr, this);
  }

  public void setDs(float value) {
    temcoreJNI.soipar_env_Ds_set(swigCPtr, this, value);
  }

  public float getDs() {
    return temcoreJNI.soipar_env_Ds_get(swigCPtr, this);
  }

  public void setWs(float value) {
    temcoreJNI.soipar_env_Ws_set(swigCPtr, this, value);
  }

  public float getWs() {
    return temcoreJNI.soipar_env_Ws_get(swigCPtr, this);
  }

  public void setDsmax(float value) {
    temcoreJNI.soipar_env_Dsmax_set(swigCPtr, this, value);
  }

  public float getDsmax() {
    return temcoreJNI.soipar_env_Dsmax_get(swigCPtr, this);
  }

  public void setB_infilt(float value) {
    temcoreJNI.soipar_env_b_infilt_set(swigCPtr, this, value);
  }

  public float getB_infilt() {
    return temcoreJNI.soipar_env_b_infilt_get(swigCPtr, this);
  }

  public void setDrainmax(float value) {
    temcoreJNI.soipar_env_drainmax_set(swigCPtr, this, value);
  }

  public float getDrainmax() {
    return temcoreJNI.soipar_env_drainmax_get(swigCPtr, this);
  }

  public void setWfact(float value) {
    temcoreJNI.soipar_env_wfact_set(swigCPtr, this, value);
  }

  public float getWfact() {
    return temcoreJNI.soipar_env_wfact_get(swigCPtr, this);
  }

  public void setEvapmin(float value) {
    temcoreJNI.soipar_env_evapmin_set(swigCPtr, this, value);
  }

  public float getEvapmin() {
    return temcoreJNI.soipar_env_evapmin_get(swigCPtr, this);
  }

  public soipar_env() {
    this(temcoreJNI.new_soipar_env(), true);
  }

}
