/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soipar_bgc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soipar_bgc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soipar_bgc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soipar_bgc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKn2(float value) {
    temcoreJNI.soipar_bgc_kn2_set(swigCPtr, this, value);
  }

  public float getKn2() {
    return temcoreJNI.soipar_bgc_kn2_get(swigCPtr, this);
  }

  public void setMoistmin(float value) {
    temcoreJNI.soipar_bgc_moistmin_set(swigCPtr, this, value);
  }

  public float getMoistmin() {
    return temcoreJNI.soipar_bgc_moistmin_get(swigCPtr, this);
  }

  public void setMoistmax(float value) {
    temcoreJNI.soipar_bgc_moistmax_set(swigCPtr, this, value);
  }

  public float getMoistmax() {
    return temcoreJNI.soipar_bgc_moistmax_get(swigCPtr, this);
  }

  public void setMoistopt(float value) {
    temcoreJNI.soipar_bgc_moistopt_set(swigCPtr, this, value);
  }

  public float getMoistopt() {
    return temcoreJNI.soipar_bgc_moistopt_get(swigCPtr, this);
  }

  public void setRhq10(float value) {
    temcoreJNI.soipar_bgc_rhq10_set(swigCPtr, this, value);
  }

  public float getRhq10() {
    return temcoreJNI.soipar_bgc_rhq10_get(swigCPtr, this);
  }

  public void setRootza(float value) {
    temcoreJNI.soipar_bgc_rootza_set(swigCPtr, this, value);
  }

  public float getRootza() {
    return temcoreJNI.soipar_bgc_rootza_get(swigCPtr, this);
  }

  public void setRootzb(float value) {
    temcoreJNI.soipar_bgc_rootzb_set(swigCPtr, this, value);
  }

  public float getRootzb() {
    return temcoreJNI.soipar_bgc_rootzb_get(swigCPtr, this);
  }

  public void setRootzc(float value) {
    temcoreJNI.soipar_bgc_rootzc_set(swigCPtr, this, value);
  }

  public float getRootzc() {
    return temcoreJNI.soipar_bgc_rootzc_get(swigCPtr, this);
  }

  public void setMinrootz(float value) {
    temcoreJNI.soipar_bgc_minrootz_set(swigCPtr, this, value);
  }

  public float getMinrootz() {
    return temcoreJNI.soipar_bgc_minrootz_get(swigCPtr, this);
  }

  public void setPropftos(float value) {
    temcoreJNI.soipar_bgc_propftos_set(swigCPtr, this, value);
  }

  public float getPropftos() {
    return temcoreJNI.soipar_bgc_propftos_get(swigCPtr, this);
  }

  public void setLcclnc(float value) {
    temcoreJNI.soipar_bgc_lcclnc_set(swigCPtr, this, value);
  }

  public float getLcclnc() {
    return temcoreJNI.soipar_bgc_lcclnc_get(swigCPtr, this);
  }

  public void setNloss(float value) {
    temcoreJNI.soipar_bgc_nloss_set(swigCPtr, this, value);
  }

  public float getNloss() {
    return temcoreJNI.soipar_bgc_nloss_get(swigCPtr, this);
  }

  public void setCnsoil(float value) {
    temcoreJNI.soipar_bgc_cnsoil_set(swigCPtr, this, value);
  }

  public float getCnsoil() {
    return temcoreJNI.soipar_bgc_cnsoil_get(swigCPtr, this);
  }

  public void setAbvltrr2t(float value) {
    temcoreJNI.soipar_bgc_abvltrr2t_set(swigCPtr, this, value);
  }

  public float getAbvltrr2t() {
    return temcoreJNI.soipar_bgc_abvltrr2t_get(swigCPtr, this);
  }

  public void setBlwltrr2t(float value) {
    temcoreJNI.soipar_bgc_blwltrr2t_set(swigCPtr, this, value);
  }

  public float getBlwltrr2t() {
    return temcoreJNI.soipar_bgc_blwltrr2t_get(swigCPtr, this);
  }

  public void setShlwa(float value) {
    temcoreJNI.soipar_bgc_shlwa_set(swigCPtr, this, value);
  }

  public float getShlwa() {
    return temcoreJNI.soipar_bgc_shlwa_get(swigCPtr, this);
  }

  public void setShlwb(float value) {
    temcoreJNI.soipar_bgc_shlwb_set(swigCPtr, this, value);
  }

  public float getShlwb() {
    return temcoreJNI.soipar_bgc_shlwb_get(swigCPtr, this);
  }

  public void setDeepa(float value) {
    temcoreJNI.soipar_bgc_deepa_set(swigCPtr, this, value);
  }

  public float getDeepa() {
    return temcoreJNI.soipar_bgc_deepa_get(swigCPtr, this);
  }

  public void setDeepb(float value) {
    temcoreJNI.soipar_bgc_deepb_set(swigCPtr, this, value);
  }

  public float getDeepb() {
    return temcoreJNI.soipar_bgc_deepb_get(swigCPtr, this);
  }

  public void setMinea(float value) {
    temcoreJNI.soipar_bgc_minea_set(swigCPtr, this, value);
  }

  public float getMinea() {
    return temcoreJNI.soipar_bgc_minea_get(swigCPtr, this);
  }

  public void setMineb(float value) {
    temcoreJNI.soipar_bgc_mineb_set(swigCPtr, this, value);
  }

  public float getMineb() {
    return temcoreJNI.soipar_bgc_mineb_get(swigCPtr, this);
  }

  public void setMaxmossthick(float value) {
    temcoreJNI.soipar_bgc_maxmossthick_set(swigCPtr, this, value);
  }

  public float getMaxmossthick() {
    return temcoreJNI.soipar_bgc_maxmossthick_get(swigCPtr, this);
  }

  public void setFsoma(float value) {
    temcoreJNI.soipar_bgc_fsoma_set(swigCPtr, this, value);
  }

  public float getFsoma() {
    return temcoreJNI.soipar_bgc_fsoma_get(swigCPtr, this);
  }

  public void setFsompr(float value) {
    temcoreJNI.soipar_bgc_fsompr_set(swigCPtr, this, value);
  }

  public float getFsompr() {
    return temcoreJNI.soipar_bgc_fsompr_get(swigCPtr, this);
  }

  public void setFsomcr(float value) {
    temcoreJNI.soipar_bgc_fsomcr_set(swigCPtr, this, value);
  }

  public float getFsomcr() {
    return temcoreJNI.soipar_bgc_fsomcr_get(swigCPtr, this);
  }

  public void setSom2co2(float value) {
    temcoreJNI.soipar_bgc_som2co2_set(swigCPtr, this, value);
  }

  public float getSom2co2() {
    return temcoreJNI.soipar_bgc_som2co2_get(swigCPtr, this);
  }

  public soipar_bgc() {
    this(temcoreJNI.new_soipar_bgc(), true);
  }

}
