/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soipar_cal {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soipar_cal(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soipar_cal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soipar_cal(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNup(float value) {
    temcoreJNI.soipar_cal_nup_set(swigCPtr, this, value);
  }

  public float getNup() {
    return temcoreJNI.soipar_cal_nup_get(swigCPtr, this);
  }

  public void setKdcfib(float value) {
    temcoreJNI.soipar_cal_kdcfib_set(swigCPtr, this, value);
  }

  public float getKdcfib() {
    return temcoreJNI.soipar_cal_kdcfib_get(swigCPtr, this);
  }

  public void setKdchum(float value) {
    temcoreJNI.soipar_cal_kdchum_set(swigCPtr, this, value);
  }

  public float getKdchum() {
    return temcoreJNI.soipar_cal_kdchum_get(swigCPtr, this);
  }

  public void setKdcmin(float value) {
    temcoreJNI.soipar_cal_kdcmin_set(swigCPtr, this, value);
  }

  public float getKdcmin() {
    return temcoreJNI.soipar_cal_kdcmin_get(swigCPtr, this);
  }

  public void setKdcslow(float value) {
    temcoreJNI.soipar_cal_kdcslow_set(swigCPtr, this, value);
  }

  public float getKdcslow() {
    return temcoreJNI.soipar_cal_kdcslow_get(swigCPtr, this);
  }

  public soipar_cal() {
    this(temcoreJNI.new_soipar_cal(), true);
  }

}
