/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soistate_bgc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soistate_bgc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soistate_bgc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soistate_bgc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setReac(double[] value) {
    temcoreJNI.soistate_bgc_reac_set(swigCPtr, this, value);
  }

  public double[] getReac() {
    return temcoreJNI.soistate_bgc_reac_get(swigCPtr, this);
  }

  public void setNonc(double[] value) {
    temcoreJNI.soistate_bgc_nonc_set(swigCPtr, this, value);
  }

  public double[] getNonc() {
    return temcoreJNI.soistate_bgc_nonc_get(swigCPtr, this);
  }

  public void setWdebris(double value) {
    temcoreJNI.soistate_bgc_wdebris_set(swigCPtr, this, value);
  }

  public double getWdebris() {
    return temcoreJNI.soistate_bgc_wdebris_get(swigCPtr, this);
  }

  public void setOrgn(double value) {
    temcoreJNI.soistate_bgc_orgn_set(swigCPtr, this, value);
  }

  public double getOrgn() {
    return temcoreJNI.soistate_bgc_orgn_get(swigCPtr, this);
  }

  public void setAvln(double value) {
    temcoreJNI.soistate_bgc_avln_set(swigCPtr, this, value);
  }

  public double getAvln() {
    return temcoreJNI.soistate_bgc_avln_get(swigCPtr, this);
  }

  public soistate_bgc() {
    this(temcoreJNI.new_soistate_bgc(), true);
  }

}
