/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soistate_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soistate_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soistate_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soistate_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumsl(int value) {
    temcoreJNI.soistate_env_numsl_set(swigCPtr, this, value);
  }

  public int getNumsl() {
    return temcoreJNI.soistate_env_numsl_get(swigCPtr, this);
  }

  public void setNumal(int value) {
    temcoreJNI.soistate_env_numal_set(swigCPtr, this, value);
  }

  public int getNumal() {
    return temcoreJNI.soistate_env_numal_get(swigCPtr, this);
  }

  public void setTsave(double value) {
    temcoreJNI.soistate_env_tsave_set(swigCPtr, this, value);
  }

  public double getTsave() {
    return temcoreJNI.soistate_env_tsave_get(swigCPtr, this);
  }

  public void setTs(double[] value) {
    temcoreJNI.soistate_env_ts_set(swigCPtr, this, value);
  }

  public double[] getTs() {
    return temcoreJNI.soistate_env_ts_get(swigCPtr, this);
  }

  public void setLiq(double[] value) {
    temcoreJNI.soistate_env_liq_set(swigCPtr, this, value);
  }

  public double[] getLiq() {
    return temcoreJNI.soistate_env_liq_get(swigCPtr, this);
  }

  public void setIce(double[] value) {
    temcoreJNI.soistate_env_ice_set(swigCPtr, this, value);
  }

  public double[] getIce() {
    return temcoreJNI.soistate_env_ice_get(swigCPtr, this);
  }

  public void setLiqsum(double value) {
    temcoreJNI.soistate_env_liqsum_set(swigCPtr, this, value);
  }

  public double getLiqsum() {
    return temcoreJNI.soistate_env_liqsum_get(swigCPtr, this);
  }

  public void setIcesum(double value) {
    temcoreJNI.soistate_env_icesum_set(swigCPtr, this, value);
  }

  public double getIcesum() {
    return temcoreJNI.soistate_env_icesum_get(swigCPtr, this);
  }

  public void setRootfrac(double[] value) {
    temcoreJNI.soistate_env_rootfrac_set(swigCPtr, this, value);
  }

  public double[] getRootfrac() {
    return temcoreJNI.soistate_env_rootfrac_get(swigCPtr, this);
  }

  public void setDz(double[] value) {
    temcoreJNI.soistate_env_dz_set(swigCPtr, this, value);
  }

  public double[] getDz() {
    return temcoreJNI.soistate_env_dz_get(swigCPtr, this);
  }

  public void setZ(double[] value) {
    temcoreJNI.soistate_env_z_set(swigCPtr, this, value);
  }

  public double[] getZ() {
    return temcoreJNI.soistate_env_z_get(swigCPtr, this);
  }

  public void setPor(double[] value) {
    temcoreJNI.soistate_env_por_set(swigCPtr, this, value);
  }

  public double[] getPor() {
    return temcoreJNI.soistate_env_por_get(swigCPtr, this);
  }

  public void setType(double[] value) {
    temcoreJNI.soistate_env_type_set(swigCPtr, this, value);
  }

  public double[] getType() {
    return temcoreJNI.soistate_env_type_get(swigCPtr, this);
  }

  public soistate_env() {
    this(temcoreJNI.new_soistate_env(), true);
  }

}
