/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class temcore {
  public static int getMAX_VEG_TYPE() {
    return temcoreJNI.MAX_VEG_TYPE_get();
  }

  public static int getMAX_DRG_TYPE() {
    return temcoreJNI.MAX_DRG_TYPE_get();
  }

  public static int getMAX_SNW_LAY() {
    return temcoreJNI.MAX_SNW_LAY_get();
  }

  public static int getMAX_ROC_LAY() {
    return temcoreJNI.MAX_ROC_LAY_get();
  }

  public static int getMAX_MOS_LAY() {
    return temcoreJNI.MAX_MOS_LAY_get();
  }

  public static int getMAX_SLW_LAY() {
    return temcoreJNI.MAX_SLW_LAY_get();
  }

  public static int getMAX_DEP_LAY() {
    return temcoreJNI.MAX_DEP_LAY_get();
  }

  public static int getMAX_MIN_LAY() {
    return temcoreJNI.MAX_MIN_LAY_get();
  }

  public static float[] getMINETHICK() {
    return temcoreJNI.MINETHICK_get();
  }

  public static int getMAX_SOI_LAY() {
    return temcoreJNI.MAX_SOI_LAY_get();
  }

  public static int getMAX_DYN_LAY() {
    return temcoreJNI.MAX_DYN_LAY_get();
  }

  public static int getMAX_GRN_LAY() {
    return temcoreJNI.MAX_GRN_LAY_get();
  }

  public static int getMAX_NUM_FNT() {
    return temcoreJNI.MAX_NUM_FNT_get();
  }

  public static int getMAX_OUT_SOI() {
    return temcoreJNI.MAX_OUT_SOI_get();
  }

  public static int getMAX_OUT_SNW() {
    return temcoreJNI.MAX_OUT_SNW_get();
  }

  public static float getDENLIQ() {
    return temcoreJNI.DENLIQ_get();
  }

  public static float getDENICE() {
    return temcoreJNI.DENICE_get();
  }

  public static float getTCLIQ() {
    return temcoreJNI.TCLIQ_get();
  }

  public static float getTCICE() {
    return temcoreJNI.TCICE_get();
  }

  public static float getTCAIR() {
    return temcoreJNI.TCAIR_get();
  }

  public static float getSHCLIQ() {
    return temcoreJNI.SHCLIQ_get();
  }

  public static float getSHCICE() {
    return temcoreJNI.SHCICE_get();
  }

  public static float getSHCAIR() {
    return temcoreJNI.SHCAIR_get();
  }

  public static float getLHFUS() {
    return temcoreJNI.LHFUS_get();
  }

  public static float getLHVAP() {
    return temcoreJNI.LHVAP_get();
  }

  public static float getLHSUB() {
    return temcoreJNI.LHSUB_get();
  }

  public static float getG() {
    return temcoreJNI.G_get();
  }

  public static float getPI() {
    return temcoreJNI.PI_get();
  }

  public static float getPstd() {
    return temcoreJNI.Pstd_get();
  }

  public static float getSTFBOLTZ() {
    return temcoreJNI.STFBOLTZ_get();
  }

  public static float getBOLTZ() {
    return temcoreJNI.BOLTZ_get();
  }

  public static float getNA() {
    return temcoreJNI.NA_get();
  }

  public static float getKPA() {
    return temcoreJNI.KPA_get();
  }

  public static int getNUM_NL_STATE() {
    return temcoreJNI.NUM_NL_STATE_get();
  }

  public static int getNUM_NL_FLXDIAG() {
    return temcoreJNI.NUM_NL_FLXDIAG_get();
  }

  public static int getNUM_L_STATE() {
    return temcoreJNI.NUM_L_STATE_get();
  }

  public static int getNUM_L_FLXDIAG() {
    return temcoreJNI.NUM_L_FLXDIAG_get();
  }

  public static int getNUMEQ() {
    return temcoreJNI.NUMEQ_get();
  }

  public static int getMAXSTATE() {
    return temcoreJNI.MAXSTATE_get();
  }

  public static int getDYINY() {
    return temcoreJNI.DYINY_get();
  }

  public static int getMINY() {
    return temcoreJNI.MINY_get();
  }

  public static int getMAX_CO2_DRV_YR() {
    return temcoreJNI.MAX_CO2_DRV_YR_get();
  }

  public static int getMAX_ATM_DRV_YR() {
    return temcoreJNI.MAX_ATM_DRV_YR_get();
  }

  public static int getMAX_ATM_NOM_YR() {
    return temcoreJNI.MAX_ATM_NOM_YR_get();
  }

  public static int getMAX_FSIZE_DRV_YR() {
    return temcoreJNI.MAX_FSIZE_DRV_YR_get();
  }

  public static int getMAX_EQ_YR() {
    return temcoreJNI.MAX_EQ_YR_get();
  }

  public static int getMAX_SP_YR() {
    return temcoreJNI.MAX_SP_YR_get();
  }

  public static int getBEG_TR_YR() {
    return temcoreJNI.BEG_TR_YR_get();
  }

  public static int getEND_TR_YR() {
    return temcoreJNI.END_TR_YR_get();
  }

  public static int getBEG_SC_YR() {
    return temcoreJNI.BEG_SC_YR_get();
  }

  public static int getEND_SC_YR() {
    return temcoreJNI.END_SC_YR_get();
  }

  public static int getEND_SP_YR() {
    return temcoreJNI.END_SP_YR_get();
  }

  public static int getBEG_SP_YR() {
    return temcoreJNI.BEG_SP_YR_get();
  }

  public static int getMAX_TR_YR() {
    return temcoreJNI.MAX_TR_YR_get();
  }

  public static int getMAX_SC_YR() {
    return temcoreJNI.MAX_SC_YR_get();
  }

  public static int getMAX_TR_FIR_OCR_NUM() {
    return temcoreJNI.MAX_TR_FIR_OCR_NUM_get();
  }

  public static int getMAX_SP_FIR_OCR_NUM() {
    return temcoreJNI.MAX_SP_FIR_OCR_NUM_get();
  }

  public static int getMAX_FIR_OCR_NUM() {
    return temcoreJNI.MAX_FIR_OCR_NUM_get();
  }

  public static int getMAX_SOC_DEP() {
    return temcoreJNI.MAX_SOC_DEP_get();
  }

  public static int getMAX_FR_INT() {
    return temcoreJNI.MAX_FR_INT_get();
  }

  public static int getMAX_SOIL_TXTR() {
    return temcoreJNI.MAX_SOIL_TXTR_get();
  }

  public static int getMAX_SM() {
    return temcoreJNI.MAX_SM_get();
  }

  public static int getMAX_ST1() {
    return temcoreJNI.MAX_ST1_get();
  }

  public static int getMAX_ST2() {
    return temcoreJNI.MAX_ST2_get();
  }

}
