/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class Timer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Timer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Timer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_Timer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Timer() {
    this(temcoreJNI.new_Timer(), true);
  }

  public static void setDinm(int[] value) {
    temcoreJNI.Timer_dinm_set(value);
  }

  public static int[] getDinm() {
    return temcoreJNI.Timer_dinm_get();
  }

  public static void setDoyindfst(int[] value) {
    temcoreJNI.Timer_doyindfst_set(value);
  }

  public static int[] getDoyindfst() {
    return temcoreJNI.Timer_doyindfst_get();
  }

  public void setSpinfinished(boolean value) {
    temcoreJNI.Timer_spinfinished_set(swigCPtr, this, value);
  }

  public boolean getSpinfinished() {
    return temcoreJNI.Timer_spinfinished_get(swigCPtr, this);
  }

  public void setYearind(int value) {
    temcoreJNI.Timer_yearind_set(swigCPtr, this, value);
  }

  public int getYearind() {
    return temcoreJNI.Timer_yearind_get(swigCPtr, this);
  }

  public void setMonind(int value) {
    temcoreJNI.Timer_monind_set(swigCPtr, this, value);
  }

  public int getMonind() {
    return temcoreJNI.Timer_monind_get(swigCPtr, this);
  }

  public void setMaxeqrunyrs(int value) {
    temcoreJNI.Timer_maxeqrunyrs_set(swigCPtr, this, value);
  }

  public int getMaxeqrunyrs() {
    return temcoreJNI.Timer_maxeqrunyrs_get(swigCPtr, this);
  }

  public void setSpinbegyr(int value) {
    temcoreJNI.Timer_spinbegyr_set(swigCPtr, this, value);
  }

  public int getSpinbegyr() {
    return temcoreJNI.Timer_spinbegyr_get(swigCPtr, this);
  }

  public void setSpinendyr(int value) {
    temcoreJNI.Timer_spinendyr_set(swigCPtr, this, value);
  }

  public int getSpinendyr() {
    return temcoreJNI.Timer_spinendyr_get(swigCPtr, this);
  }

  public void setSpinnumyr(int value) {
    temcoreJNI.Timer_spinnumyr_set(swigCPtr, this, value);
  }

  public int getSpinnumyr() {
    return temcoreJNI.Timer_spinnumyr_get(swigCPtr, this);
  }

  public void setTrsbegyr(int value) {
    temcoreJNI.Timer_trsbegyr_set(swigCPtr, this, value);
  }

  public int getTrsbegyr() {
    return temcoreJNI.Timer_trsbegyr_get(swigCPtr, this);
  }

  public void setTrsendyr(int value) {
    temcoreJNI.Timer_trsendyr_set(swigCPtr, this, value);
  }

  public int getTrsendyr() {
    return temcoreJNI.Timer_trsendyr_get(swigCPtr, this);
  }

  public void setTrsnumyr(int value) {
    temcoreJNI.Timer_trsnumyr_set(swigCPtr, this, value);
  }

  public int getTrsnumyr() {
    return temcoreJNI.Timer_trsnumyr_get(swigCPtr, this);
  }

  public void setScbegyr(int value) {
    temcoreJNI.Timer_scbegyr_set(swigCPtr, this, value);
  }

  public int getScbegyr() {
    return temcoreJNI.Timer_scbegyr_get(swigCPtr, this);
  }

  public void setScendyr(int value) {
    temcoreJNI.Timer_scendyr_set(swigCPtr, this, value);
  }

  public int getScendyr() {
    return temcoreJNI.Timer_scendyr_get(swigCPtr, this);
  }

  public void setScnumyr(int value) {
    temcoreJNI.Timer_scnumyr_set(swigCPtr, this, value);
  }

  public int getScnumyr() {
    return temcoreJNI.Timer_scnumyr_get(swigCPtr, this);
  }

  public void setOutbegyr(int value) {
    temcoreJNI.Timer_outbegyr_set(swigCPtr, this, value);
  }

  public int getOutbegyr() {
    return temcoreJNI.Timer_outbegyr_get(swigCPtr, this);
  }

  public void setOutendyr(int value) {
    temcoreJNI.Timer_outendyr_set(swigCPtr, this, value);
  }

  public int getOutendyr() {
    return temcoreJNI.Timer_outendyr_get(swigCPtr, this);
  }

  public void setDlyinterval(int value) {
    temcoreJNI.Timer_dlyinterval_set(swigCPtr, this, value);
  }

  public int getDlyinterval() {
    return temcoreJNI.Timer_dlyinterval_get(swigCPtr, this);
  }

  public void setNumrunyr(int value) {
    temcoreJNI.Timer_numrunyr_set(swigCPtr, this, value);
  }

  public int getNumrunyr() {
    return temcoreJNI.Timer_numrunyr_get(swigCPtr, this);
  }

  public int getInputYearIndex(SWIGTYPE_p_bool equiled, SWIGTYPE_p_bool spined) {
    return temcoreJNI.Timer_getInputYearIndex(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(equiled), SWIGTYPE_p_bool.getCPtr(spined));
  }

  public int getOutputYearIndex(SWIGTYPE_p_bool equiled, SWIGTYPE_p_bool spined, SWIGTYPE_p_bool outputSpinup) {
    return temcoreJNI.Timer_getOutputYearIndex(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(equiled), SWIGTYPE_p_bool.getCPtr(spined), SWIGTYPE_p_bool.getCPtr(outputSpinup));
  }

  public int getDOYIndex(int mon, int id) {
    return temcoreJNI.Timer_getDOYIndex(swigCPtr, this, mon, id);
  }

  public void reset() {
    temcoreJNI.Timer_reset(swigCPtr, this);
  }

  public int getTranNumberOfYears() {
    return temcoreJNI.Timer_getTranNumberOfYears(swigCPtr, this);
  }

  public int getScenNumberOfYears() {
    return temcoreJNI.Timer_getScenNumberOfYears(swigCPtr, this);
  }

  public int getDaysInMonth(SWIGTYPE_p_int mon) {
    return temcoreJNI.Timer_getDaysInMonth(swigCPtr, this, SWIGTYPE_p_int.getCPtr(mon));
  }

  public int getCurrentMonthIndex() {
    return temcoreJNI.Timer_getCurrentMonthIndex(swigCPtr, this);
  }

  public int getNextMonthIndex() {
    return temcoreJNI.Timer_getNextMonthIndex(swigCPtr, this);
  }

  public int getCurrentYearIndex() {
    return temcoreJNI.Timer_getCurrentYearIndex(swigCPtr, this);
  }

  public void advanceOneMonth() {
    temcoreJNI.Timer_advanceOneMonth(swigCPtr, this);
  }

  public int getCalendarYear(SWIGTYPE_p_bool equiled, SWIGTYPE_p_bool spined) {
    return temcoreJNI.Timer_getCalendarYear(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(equiled), SWIGTYPE_p_bool.getCPtr(spined));
  }

}
