/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class veg2soi_fir {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected veg2soi_fir(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(veg2soi_fir obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_veg2soi_fir(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAbvc(double value) {
    temcoreJNI.veg2soi_fir_abvc_set(swigCPtr, this, value);
  }

  public double getAbvc() {
    return temcoreJNI.veg2soi_fir_abvc_get(swigCPtr, this);
  }

  public void setAbvn(double value) {
    temcoreJNI.veg2soi_fir_abvn_set(swigCPtr, this, value);
  }

  public double getAbvn() {
    return temcoreJNI.veg2soi_fir_abvn_get(swigCPtr, this);
  }

  public void setBlwc(double value) {
    temcoreJNI.veg2soi_fir_blwc_set(swigCPtr, this, value);
  }

  public double getBlwc() {
    return temcoreJNI.veg2soi_fir_blwc_get(swigCPtr, this);
  }

  public void setBlwn(double value) {
    temcoreJNI.veg2soi_fir_blwn_set(swigCPtr, this, value);
  }

  public double getBlwn() {
    return temcoreJNI.veg2soi_fir_blwn_get(swigCPtr, this);
  }

  public veg2soi_fir() {
    this(temcoreJNI.new_veg2soi_fir(), true);
  }

}
