/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class veg2atm_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected veg2atm_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(veg2atm_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_veg2atm_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTrans(double value) {
    temcoreJNI.veg2atm_env_trans_set(swigCPtr, this, value);
  }

  public double getTrans() {
    return temcoreJNI.veg2atm_env_trans_get(swigCPtr, this);
  }

  public void setEvapo(double value) {
    temcoreJNI.veg2atm_env_evapo_set(swigCPtr, this, value);
  }

  public double getEvapo() {
    return temcoreJNI.veg2atm_env_evapo_get(swigCPtr, this);
  }

  public void setTrans_pet(double value) {
    temcoreJNI.veg2atm_env_trans_pet_set(swigCPtr, this, value);
  }

  public double getTrans_pet() {
    return temcoreJNI.veg2atm_env_trans_pet_get(swigCPtr, this);
  }

  public void setEvapo_pet(double value) {
    temcoreJNI.veg2atm_env_evapo_pet_set(swigCPtr, this, value);
  }

  public double getEvapo_pet() {
    return temcoreJNI.veg2atm_env_evapo_pet_get(swigCPtr, this);
  }

  public void setSublim(double value) {
    temcoreJNI.veg2atm_env_sublim_set(swigCPtr, this, value);
  }

  public double getSublim() {
    return temcoreJNI.veg2atm_env_sublim_get(swigCPtr, this);
  }

  public void setSolrad(double value) {
    temcoreJNI.veg2atm_env_solrad_set(swigCPtr, this, value);
  }

  public double getSolrad() {
    return temcoreJNI.veg2atm_env_solrad_get(swigCPtr, this);
  }

  public veg2atm_env() {
    this(temcoreJNI.new_veg2atm_env(), true);
  }

}
