/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class veg2veg_bgc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected veg2veg_bgc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(veg2veg_bgc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_veg2veg_bgc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNmobil(double value) {
    temcoreJNI.veg2veg_bgc_nmobil_set(swigCPtr, this, value);
  }

  public double getNmobil() {
    return temcoreJNI.veg2veg_bgc_nmobil_get(swigCPtr, this);
  }

  public void setNresorb(double value) {
    temcoreJNI.veg2veg_bgc_nresorb_set(swigCPtr, this, value);
  }

  public double getNresorb() {
    return temcoreJNI.veg2veg_bgc_nresorb_get(swigCPtr, this);
  }

  public veg2veg_bgc() {
    this(temcoreJNI.new_veg2veg_bgc(), true);
  }

}
