/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public final class VEGKEY {
  public final static VEGKEY I_TUNDRA = new VEGKEY("I_TUNDRA");
  public final static VEGKEY I_DF = new VEGKEY("I_DF");
  public final static VEGKEY I_WSF = new VEGKEY("I_WSF");
  public final static VEGKEY I_BSF = new VEGKEY("I_BSF");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static VEGKEY swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + VEGKEY.class + " with value " + swigValue);
  }

  private VEGKEY(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private VEGKEY(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private VEGKEY(String swigName, VEGKEY swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static VEGKEY[] swigValues = { I_TUNDRA, I_DF, I_WSF, I_BSF };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

