/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class VegOutData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VegOutData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VegOutData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_VegOutData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VegOutData() {
    this(temcoreJNI.new_VegOutData(), true);
  }

  public void setSinterd(float[] value) {
    temcoreJNI.VegOutData_sinterd_set(swigCPtr, this, value);
  }

  public float[] getSinterd() {
    return temcoreJNI.VegOutData_sinterd_get(swigCPtr, this);
  }

  public void setRinterd(float[] value) {
    temcoreJNI.VegOutData_rinterd_set(swigCPtr, this, value);
  }

  public float[] getRinterd() {
    return temcoreJNI.VegOutData_rinterd_get(swigCPtr, this);
  }

  public void setSthfld(float[] value) {
    temcoreJNI.VegOutData_sthfld_set(swigCPtr, this, value);
  }

  public float[] getSthfld() {
    return temcoreJNI.VegOutData_sthfld_get(swigCPtr, this);
  }

  public void setRthfld(float[] value) {
    temcoreJNI.VegOutData_rthfld_set(swigCPtr, this, value);
  }

  public float[] getRthfld() {
    return temcoreJNI.VegOutData_rthfld_get(swigCPtr, this);
  }

  public void setSdripd(float[] value) {
    temcoreJNI.VegOutData_sdripd_set(swigCPtr, this, value);
  }

  public float[] getSdripd() {
    return temcoreJNI.VegOutData_sdripd_get(swigCPtr, this);
  }

  public void setRdripd(float[] value) {
    temcoreJNI.VegOutData_rdripd_set(swigCPtr, this, value);
  }

  public float[] getRdripd() {
    return temcoreJNI.VegOutData_rdripd_get(swigCPtr, this);
  }

  public void setScanopyd(float[] value) {
    temcoreJNI.VegOutData_scanopyd_set(swigCPtr, this, value);
  }

  public float[] getScanopyd() {
    return temcoreJNI.VegOutData_scanopyd_get(swigCPtr, this);
  }

  public void setRcanopyd(float[] value) {
    temcoreJNI.VegOutData_rcanopyd_set(swigCPtr, this, value);
  }

  public float[] getRcanopyd() {
    return temcoreJNI.VegOutData_rcanopyd_get(swigCPtr, this);
  }

  public void setCansubd(float[] value) {
    temcoreJNI.VegOutData_cansubd_set(swigCPtr, this, value);
  }

  public float[] getCansubd() {
    return temcoreJNI.VegOutData_cansubd_get(swigCPtr, this);
  }

  public void setCanevpd(float[] value) {
    temcoreJNI.VegOutData_canevpd_set(swigCPtr, this, value);
  }

  public float[] getCanevpd() {
    return temcoreJNI.VegOutData_canevpd_get(swigCPtr, this);
  }

  public void setCantrsd(float[] value) {
    temcoreJNI.VegOutData_cantrsd_set(swigCPtr, this, value);
  }

  public float[] getCantrsd() {
    return temcoreJNI.VegOutData_cantrsd_get(swigCPtr, this);
  }

  public void setRacd(float[] value) {
    temcoreJNI.VegOutData_racd_set(swigCPtr, this, value);
  }

  public float[] getRacd() {
    return temcoreJNI.VegOutData_racd_get(swigCPtr, this);
  }

  public void setRadrefld(float[] value) {
    temcoreJNI.VegOutData_radrefld_set(swigCPtr, this, value);
  }

  public float[] getRadrefld() {
    return temcoreJNI.VegOutData_radrefld_get(swigCPtr, this);
  }

  public void setRadthroud(float[] value) {
    temcoreJNI.VegOutData_radthroud_set(swigCPtr, this, value);
  }

  public float[] getRadthroud() {
    return temcoreJNI.VegOutData_radthroud_get(swigCPtr, this);
  }

  public void setBtrand(float[] value) {
    temcoreJNI.VegOutData_btrand_set(swigCPtr, this, value);
  }

  public float[] getBtrand() {
    return temcoreJNI.VegOutData_btrand_get(swigCPtr, this);
  }

  public void setM_ppfdd(float[] value) {
    temcoreJNI.VegOutData_m_ppfdd_set(swigCPtr, this, value);
  }

  public float[] getM_ppfdd() {
    return temcoreJNI.VegOutData_m_ppfdd_get(swigCPtr, this);
  }

  public void setM_vpdd(float[] value) {
    temcoreJNI.VegOutData_m_vpdd_set(swigCPtr, this, value);
  }

  public float[] getM_vpdd() {
    return temcoreJNI.VegOutData_m_vpdd_get(swigCPtr, this);
  }

  public void setCcd(float[] value) {
    temcoreJNI.VegOutData_ccd_set(swigCPtr, this, value);
  }

  public float[] getCcd() {
    return temcoreJNI.VegOutData_ccd_get(swigCPtr, this);
  }

  public void setBtran(float[] value) {
    temcoreJNI.VegOutData_btran_set(swigCPtr, this, value);
  }

  public float[] getBtran() {
    return temcoreJNI.VegOutData_btran_get(swigCPtr, this);
  }

  public void setRc(float[] value) {
    temcoreJNI.VegOutData_rc_set(swigCPtr, this, value);
  }

  public float[] getRc() {
    return temcoreJNI.VegOutData_rc_get(swigCPtr, this);
  }

  public void setRac(float[] value) {
    temcoreJNI.VegOutData_rac_set(swigCPtr, this, value);
  }

  public float[] getRac() {
    return temcoreJNI.VegOutData_rac_get(swigCPtr, this);
  }

  public void setTrans(float[] value) {
    temcoreJNI.VegOutData_trans_set(swigCPtr, this, value);
  }

  public float[] getTrans() {
    return temcoreJNI.VegOutData_trans_get(swigCPtr, this);
  }

  public void setVevap(float[] value) {
    temcoreJNI.VegOutData_vevap_set(swigCPtr, this, value);
  }

  public float[] getVevap() {
    return temcoreJNI.VegOutData_vevap_get(swigCPtr, this);
  }

  public void setVsubl(float[] value) {
    temcoreJNI.VegOutData_vsubl_set(swigCPtr, this, value);
  }

  public float[] getVsubl() {
    return temcoreJNI.VegOutData_vsubl_get(swigCPtr, this);
  }

  public void setRinter(float[] value) {
    temcoreJNI.VegOutData_rinter_set(swigCPtr, this, value);
  }

  public float[] getRinter() {
    return temcoreJNI.VegOutData_rinter_get(swigCPtr, this);
  }

  public void setSinter(float[] value) {
    temcoreJNI.VegOutData_sinter_set(swigCPtr, this, value);
  }

  public float[] getSinter() {
    return temcoreJNI.VegOutData_sinter_get(swigCPtr, this);
  }

  public void setRthfl(float[] value) {
    temcoreJNI.VegOutData_rthfl_set(swigCPtr, this, value);
  }

  public float[] getRthfl() {
    return temcoreJNI.VegOutData_rthfl_get(swigCPtr, this);
  }

  public void setSthfl(float[] value) {
    temcoreJNI.VegOutData_sthfl_set(swigCPtr, this, value);
  }

  public float[] getSthfl() {
    return temcoreJNI.VegOutData_sthfl_get(swigCPtr, this);
  }

  public void setRadthfl(float[] value) {
    temcoreJNI.VegOutData_radthfl_set(swigCPtr, this, value);
  }

  public float[] getRadthfl() {
    return temcoreJNI.VegOutData_radthfl_get(swigCPtr, this);
  }

  public void setVegc(float[] value) {
    temcoreJNI.VegOutData_vegc_set(swigCPtr, this, value);
  }

  public float[] getVegc() {
    return temcoreJNI.VegOutData_vegc_get(swigCPtr, this);
  }

  public void setStrn(float[] value) {
    temcoreJNI.VegOutData_strn_set(swigCPtr, this, value);
  }

  public float[] getStrn() {
    return temcoreJNI.VegOutData_strn_get(swigCPtr, this);
  }

  public void setSton(float[] value) {
    temcoreJNI.VegOutData_ston_set(swigCPtr, this, value);
  }

  public float[] getSton() {
    return temcoreJNI.VegOutData_ston_get(swigCPtr, this);
  }

  public void setIngpp(float[] value) {
    temcoreJNI.VegOutData_ingpp_set(swigCPtr, this, value);
  }

  public float[] getIngpp() {
    return temcoreJNI.VegOutData_ingpp_get(swigCPtr, this);
  }

  public void setGpp(float[] value) {
    temcoreJNI.VegOutData_gpp_set(swigCPtr, this, value);
  }

  public float[] getGpp() {
    return temcoreJNI.VegOutData_gpp_get(swigCPtr, this);
  }

  public void setInnpp(float[] value) {
    temcoreJNI.VegOutData_innpp_set(swigCPtr, this, value);
  }

  public float[] getInnpp() {
    return temcoreJNI.VegOutData_innpp_get(swigCPtr, this);
  }

  public void setNpp(float[] value) {
    temcoreJNI.VegOutData_npp_set(swigCPtr, this, value);
  }

  public float[] getNpp() {
    return temcoreJNI.VegOutData_npp_get(swigCPtr, this);
  }

  public void setRm(float[] value) {
    temcoreJNI.VegOutData_rm_set(swigCPtr, this, value);
  }

  public float[] getRm() {
    return temcoreJNI.VegOutData_rm_get(swigCPtr, this);
  }

  public void setRg(float[] value) {
    temcoreJNI.VegOutData_rg_set(swigCPtr, this, value);
  }

  public float[] getRg() {
    return temcoreJNI.VegOutData_rg_get(swigCPtr, this);
  }

  public void setLtrfalc(float[] value) {
    temcoreJNI.VegOutData_ltrfalc_set(swigCPtr, this, value);
  }

  public float[] getLtrfalc() {
    return temcoreJNI.VegOutData_ltrfalc_get(swigCPtr, this);
  }

  public void setLtrfaln(float[] value) {
    temcoreJNI.VegOutData_ltrfaln_set(swigCPtr, this, value);
  }

  public float[] getLtrfaln() {
    return temcoreJNI.VegOutData_ltrfaln_get(swigCPtr, this);
  }

  public void setInnuptake(float[] value) {
    temcoreJNI.VegOutData_innuptake_set(swigCPtr, this, value);
  }

  public float[] getInnuptake() {
    return temcoreJNI.VegOutData_innuptake_get(swigCPtr, this);
  }

  public void setNuptake(float[] value) {
    temcoreJNI.VegOutData_nuptake_set(swigCPtr, this, value);
  }

  public float[] getNuptake() {
    return temcoreJNI.VegOutData_nuptake_get(swigCPtr, this);
  }

  public void setLuptake(float[] value) {
    temcoreJNI.VegOutData_luptake_set(swigCPtr, this, value);
  }

  public float[] getLuptake() {
    return temcoreJNI.VegOutData_luptake_get(swigCPtr, this);
  }

  public void setSuptake(float[] value) {
    temcoreJNI.VegOutData_suptake_set(swigCPtr, this, value);
  }

  public float[] getSuptake() {
    return temcoreJNI.VegOutData_suptake_get(swigCPtr, this);
  }

  public void setNresorb(float[] value) {
    temcoreJNI.VegOutData_nresorb_set(swigCPtr, this, value);
  }

  public float[] getNresorb() {
    return temcoreJNI.VegOutData_nresorb_get(swigCPtr, this);
  }

  public void setNmobil(float[] value) {
    temcoreJNI.VegOutData_nmobil_set(swigCPtr, this, value);
  }

  public float[] getNmobil() {
    return temcoreJNI.VegOutData_nmobil_get(swigCPtr, this);
  }

  public void setLai(float[] value) {
    temcoreJNI.VegOutData_lai_set(swigCPtr, this, value);
  }

  public float[] getLai() {
    return temcoreJNI.VegOutData_lai_get(swigCPtr, this);
  }

  public void setFpc(float[] value) {
    temcoreJNI.VegOutData_fpc_set(swigCPtr, this, value);
  }

  public float[] getFpc() {
    return temcoreJNI.VegOutData_fpc_get(swigCPtr, this);
  }

  public void setUnnormleaf(float[] value) {
    temcoreJNI.VegOutData_unnormleaf_set(swigCPtr, this, value);
  }

  public float[] getUnnormleaf() {
    return temcoreJNI.VegOutData_unnormleaf_get(swigCPtr, this);
  }

  public void setLeaf(float[] value) {
    temcoreJNI.VegOutData_leaf_set(swigCPtr, this, value);
  }

  public float[] getLeaf() {
    return temcoreJNI.VegOutData_leaf_get(swigCPtr, this);
  }

  public void setFoliage(float[] value) {
    temcoreJNI.VegOutData_foliage_set(swigCPtr, this, value);
  }

  public float[] getFoliage() {
    return temcoreJNI.VegOutData_foliage_get(swigCPtr, this);
  }

  public void setYrevapo(float value) {
    temcoreJNI.VegOutData_yrevapo_set(swigCPtr, this, value);
  }

  public float getYrevapo() {
    return temcoreJNI.VegOutData_yrevapo_get(swigCPtr, this);
  }

  public void setYrsublim(float value) {
    temcoreJNI.VegOutData_yrsublim_set(swigCPtr, this, value);
  }

  public float getYrsublim() {
    return temcoreJNI.VegOutData_yrsublim_get(swigCPtr, this);
  }

  public void setYrtrans(float value) {
    temcoreJNI.VegOutData_yrtrans_set(swigCPtr, this, value);
  }

  public float getYrtrans() {
    return temcoreJNI.VegOutData_yrtrans_get(swigCPtr, this);
  }

  public void setYrc2n(float value) {
    temcoreJNI.VegOutData_yrc2n_set(swigCPtr, this, value);
  }

  public float getYrc2n() {
    return temcoreJNI.VegOutData_yrc2n_get(swigCPtr, this);
  }

  public void setYrnpp(float value) {
    temcoreJNI.VegOutData_yrnpp_set(swigCPtr, this, value);
  }

  public float getYrnpp() {
    return temcoreJNI.VegOutData_yrnpp_get(swigCPtr, this);
  }

  public void setYrrg(float value) {
    temcoreJNI.VegOutData_yrrg_set(swigCPtr, this, value);
  }

  public float getYrrg() {
    return temcoreJNI.VegOutData_yrrg_get(swigCPtr, this);
  }

  public void setYrrm(float value) {
    temcoreJNI.VegOutData_yrrm_set(swigCPtr, this, value);
  }

  public float getYrrm() {
    return temcoreJNI.VegOutData_yrrm_get(swigCPtr, this);
  }

  public void setYrltrfalc(float value) {
    temcoreJNI.VegOutData_yrltrfalc_set(swigCPtr, this, value);
  }

  public float getYrltrfalc() {
    return temcoreJNI.VegOutData_yrltrfalc_get(swigCPtr, this);
  }

  public void setYrltrfaln(float value) {
    temcoreJNI.VegOutData_yrltrfaln_set(swigCPtr, this, value);
  }

  public float getYrltrfaln() {
    return temcoreJNI.VegOutData_yrltrfaln_get(swigCPtr, this);
  }

  public void setYrvnuptake(float value) {
    temcoreJNI.VegOutData_yrvnuptake_set(swigCPtr, this, value);
  }

  public float getYrvnuptake() {
    return temcoreJNI.VegOutData_yrvnuptake_get(swigCPtr, this);
  }

  public void setYrabvgndc(float value) {
    temcoreJNI.VegOutData_yrabvgndc_set(swigCPtr, this, value);
  }

  public float getYrabvgndc() {
    return temcoreJNI.VegOutData_yrabvgndc_get(swigCPtr, this);
  }

  public void setYrfoliage(float value) {
    temcoreJNI.VegOutData_yrfoliage_set(swigCPtr, this, value);
  }

  public float getYrfoliage() {
    return temcoreJNI.VegOutData_yrfoliage_get(swigCPtr, this);
  }

  public void setYrleaf(float value) {
    temcoreJNI.VegOutData_yrleaf_set(swigCPtr, this, value);
  }

  public float getYrleaf() {
    return temcoreJNI.VegOutData_yrleaf_get(swigCPtr, this);
  }

  public void setYrlai(float value) {
    temcoreJNI.VegOutData_yrlai_set(swigCPtr, this, value);
  }

  public float getYrlai() {
    return temcoreJNI.VegOutData_yrlai_get(swigCPtr, this);
  }

  public void setYrfpc(float value) {
    temcoreJNI.VegOutData_yrfpc_set(swigCPtr, this, value);
  }

  public float getYrfpc() {
    return temcoreJNI.VegOutData_yrfpc_get(swigCPtr, this);
  }

  public void setYrvegc(float value) {
    temcoreJNI.VegOutData_yrvegc_set(swigCPtr, this, value);
  }

  public float getYrvegc() {
    return temcoreJNI.VegOutData_yrvegc_get(swigCPtr, this);
  }

  public void setYrstrn(float value) {
    temcoreJNI.VegOutData_yrstrn_set(swigCPtr, this, value);
  }

  public float getYrstrn() {
    return temcoreJNI.VegOutData_yrstrn_get(swigCPtr, this);
  }

  public void setYrston(float value) {
    temcoreJNI.VegOutData_yrston_set(swigCPtr, this, value);
  }

  public float getYrston() {
    return temcoreJNI.VegOutData_yrston_get(swigCPtr, this);
  }

  public void setYrburnorgc(float value) {
    temcoreJNI.VegOutData_yrburnorgc_set(swigCPtr, this, value);
  }

  public float getYrburnorgc() {
    return temcoreJNI.VegOutData_yrburnorgc_get(swigCPtr, this);
  }

  public void setYrburnorgn(float value) {
    temcoreJNI.VegOutData_yrburnorgn_set(swigCPtr, this, value);
  }

  public float getYrburnorgn() {
    return temcoreJNI.VegOutData_yrburnorgn_get(swigCPtr, this);
  }

}
