/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class vegpar_bgc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vegpar_bgc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vegpar_bgc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_vegpar_bgc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRaq10a0(float value) {
    temcoreJNI.vegpar_bgc_raq10a0_set(swigCPtr, this, value);
  }

  public float getRaq10a0() {
    return temcoreJNI.vegpar_bgc_raq10a0_get(swigCPtr, this);
  }

  public void setRaq10a1(float value) {
    temcoreJNI.vegpar_bgc_raq10a1_set(swigCPtr, this, value);
  }

  public float getRaq10a1() {
    return temcoreJNI.vegpar_bgc_raq10a1_get(swigCPtr, this);
  }

  public void setRaq10a2(float value) {
    temcoreJNI.vegpar_bgc_raq10a2_set(swigCPtr, this, value);
  }

  public float getRaq10a2() {
    return temcoreJNI.vegpar_bgc_raq10a2_get(swigCPtr, this);
  }

  public void setRaq10a3(float value) {
    temcoreJNI.vegpar_bgc_raq10a3_set(swigCPtr, this, value);
  }

  public float getRaq10a3() {
    return temcoreJNI.vegpar_bgc_raq10a3_get(swigCPtr, this);
  }

  public void setMaturefoliagemin(float value) {
    temcoreJNI.vegpar_bgc_maturefoliagemin_set(swigCPtr, this, value);
  }

  public float getMaturefoliagemin() {
    return temcoreJNI.vegpar_bgc_maturefoliagemin_get(swigCPtr, this);
  }

  public void setC2na(float value) {
    temcoreJNI.vegpar_bgc_c2na_set(swigCPtr, this, value);
  }

  public float getC2na() {
    return temcoreJNI.vegpar_bgc_c2na_get(swigCPtr, this);
  }

  public void setC2nb(float value) {
    temcoreJNI.vegpar_bgc_c2nb_set(swigCPtr, this, value);
  }

  public float getC2nb() {
    return temcoreJNI.vegpar_bgc_c2nb_get(swigCPtr, this);
  }

  public void setC2nmin(float value) {
    temcoreJNI.vegpar_bgc_c2nmin_set(swigCPtr, this, value);
  }

  public float getC2nmin() {
    return temcoreJNI.vegpar_bgc_c2nmin_get(swigCPtr, this);
  }

  public void setCnmin(float value) {
    temcoreJNI.vegpar_bgc_cnmin_set(swigCPtr, this, value);
  }

  public float getCnmin() {
    return temcoreJNI.vegpar_bgc_cnmin_get(swigCPtr, this);
  }

  public void setInitcneven(float value) {
    temcoreJNI.vegpar_bgc_initcneven_set(swigCPtr, this, value);
  }

  public float getInitcneven() {
    return temcoreJNI.vegpar_bgc_initcneven_get(swigCPtr, this);
  }

  public void setInitleafmx(float value) {
    temcoreJNI.vegpar_bgc_initleafmx_set(swigCPtr, this, value);
  }

  public float getInitleafmx() {
    return temcoreJNI.vegpar_bgc_initleafmx_get(swigCPtr, this);
  }

  public void setAleaf(float value) {
    temcoreJNI.vegpar_bgc_aleaf_set(swigCPtr, this, value);
  }

  public float getAleaf() {
    return temcoreJNI.vegpar_bgc_aleaf_get(swigCPtr, this);
  }

  public void setBleaf(float value) {
    temcoreJNI.vegpar_bgc_bleaf_set(swigCPtr, this, value);
  }

  public float getBleaf() {
    return temcoreJNI.vegpar_bgc_bleaf_get(swigCPtr, this);
  }

  public void setCleaf(float value) {
    temcoreJNI.vegpar_bgc_cleaf_set(swigCPtr, this, value);
  }

  public float getCleaf() {
    return temcoreJNI.vegpar_bgc_cleaf_get(swigCPtr, this);
  }

  public void setMinleaf(float value) {
    temcoreJNI.vegpar_bgc_minleaf_set(swigCPtr, this, value);
  }

  public float getMinleaf() {
    return temcoreJNI.vegpar_bgc_minleaf_get(swigCPtr, this);
  }

  public void setSla(float value) {
    temcoreJNI.vegpar_bgc_sla_set(swigCPtr, this, value);
  }

  public float getSla() {
    return temcoreJNI.vegpar_bgc_sla_get(swigCPtr, this);
  }

  public void setLeafmxc(float value) {
    temcoreJNI.vegpar_bgc_leafmxc_set(swigCPtr, this, value);
  }

  public float getLeafmxc() {
    return temcoreJNI.vegpar_bgc_leafmxc_get(swigCPtr, this);
  }

  public void setKleafc(float value) {
    temcoreJNI.vegpar_bgc_kleafc_set(swigCPtr, this, value);
  }

  public float getKleafc() {
    return temcoreJNI.vegpar_bgc_kleafc_get(swigCPtr, this);
  }

  public void setCov(float value) {
    temcoreJNI.vegpar_bgc_cov_set(swigCPtr, this, value);
  }

  public float getCov() {
    return temcoreJNI.vegpar_bgc_cov_get(swigCPtr, this);
  }

  public void setM1(float value) {
    temcoreJNI.vegpar_bgc_m1_set(swigCPtr, this, value);
  }

  public float getM1() {
    return temcoreJNI.vegpar_bgc_m1_get(swigCPtr, this);
  }

  public void setM2(float value) {
    temcoreJNI.vegpar_bgc_m2_set(swigCPtr, this, value);
  }

  public float getM2() {
    return temcoreJNI.vegpar_bgc_m2_get(swigCPtr, this);
  }

  public void setM3(float value) {
    temcoreJNI.vegpar_bgc_m3_set(swigCPtr, this, value);
  }

  public float getM3() {
    return temcoreJNI.vegpar_bgc_m3_get(swigCPtr, this);
  }

  public void setM4(float value) {
    temcoreJNI.vegpar_bgc_m4_set(swigCPtr, this, value);
  }

  public float getM4() {
    return temcoreJNI.vegpar_bgc_m4_get(swigCPtr, this);
  }

  public void setKn1(float value) {
    temcoreJNI.vegpar_bgc_kn1_set(swigCPtr, this, value);
  }

  public float getKn1() {
    return temcoreJNI.vegpar_bgc_kn1_get(swigCPtr, this);
  }

  public void setTmin(float value) {
    temcoreJNI.vegpar_bgc_tmin_set(swigCPtr, this, value);
  }

  public float getTmin() {
    return temcoreJNI.vegpar_bgc_tmin_get(swigCPtr, this);
  }

  public void setTmax(float value) {
    temcoreJNI.vegpar_bgc_tmax_set(swigCPtr, this, value);
  }

  public float getTmax() {
    return temcoreJNI.vegpar_bgc_tmax_get(swigCPtr, this);
  }

  public void setToptmin(float value) {
    temcoreJNI.vegpar_bgc_toptmin_set(swigCPtr, this, value);
  }

  public float getToptmin() {
    return temcoreJNI.vegpar_bgc_toptmin_get(swigCPtr, this);
  }

  public void setToptmax(float value) {
    temcoreJNI.vegpar_bgc_toptmax_set(swigCPtr, this, value);
  }

  public float getToptmax() {
    return temcoreJNI.vegpar_bgc_toptmax_get(swigCPtr, this);
  }

  public void setKc(float value) {
    temcoreJNI.vegpar_bgc_kc_set(swigCPtr, this, value);
  }

  public float getKc() {
    return temcoreJNI.vegpar_bgc_kc_get(swigCPtr, this);
  }

  public void setKi(float value) {
    temcoreJNI.vegpar_bgc_ki_set(swigCPtr, this, value);
  }

  public float getKi() {
    return temcoreJNI.vegpar_bgc_ki_get(swigCPtr, this);
  }

  public void setLabncon(float value) {
    temcoreJNI.vegpar_bgc_labncon_set(swigCPtr, this, value);
  }

  public float getLabncon() {
    return temcoreJNI.vegpar_bgc_labncon_get(swigCPtr, this);
  }

  public void setAbv2totmass(float value) {
    temcoreJNI.vegpar_bgc_abv2totmass_set(swigCPtr, this, value);
  }

  public float getAbv2totmass() {
    return temcoreJNI.vegpar_bgc_abv2totmass_get(swigCPtr, this);
  }

  public vegpar_bgc() {
    this(temcoreJNI.new_vegpar_bgc(), true);
  }

}
