/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class vegpar_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vegpar_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vegpar_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_vegpar_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGl_bl(float value) {
    temcoreJNI.vegpar_env_gl_bl_set(swigCPtr, this, value);
  }

  public float getGl_bl() {
    return temcoreJNI.vegpar_env_gl_bl_get(swigCPtr, this);
  }

  public void setGlmax(float value) {
    temcoreJNI.vegpar_env_glmax_set(swigCPtr, this, value);
  }

  public float getGlmax() {
    return temcoreJNI.vegpar_env_glmax_get(swigCPtr, this);
  }

  public void setGl_c(float value) {
    temcoreJNI.vegpar_env_gl_c_set(swigCPtr, this, value);
  }

  public float getGl_c() {
    return temcoreJNI.vegpar_env_gl_c_get(swigCPtr, this);
  }

  public void setAlbvisnir(float value) {
    temcoreJNI.vegpar_env_albvisnir_set(swigCPtr, this, value);
  }

  public float getAlbvisnir() {
    return temcoreJNI.vegpar_env_albvisnir_get(swigCPtr, this);
  }

  public void setEr(float value) {
    temcoreJNI.vegpar_env_er_set(swigCPtr, this, value);
  }

  public float getEr() {
    return temcoreJNI.vegpar_env_er_get(swigCPtr, this);
  }

  public void setIrcoef(float value) {
    temcoreJNI.vegpar_env_ircoef_set(swigCPtr, this, value);
  }

  public float getIrcoef() {
    return temcoreJNI.vegpar_env_ircoef_get(swigCPtr, this);
  }

  public void setIscoef(float value) {
    temcoreJNI.vegpar_env_iscoef_set(swigCPtr, this, value);
  }

  public float getIscoef() {
    return temcoreJNI.vegpar_env_iscoef_get(swigCPtr, this);
  }

  public void setVpd_open(float value) {
    temcoreJNI.vegpar_env_vpd_open_set(swigCPtr, this, value);
  }

  public float getVpd_open() {
    return temcoreJNI.vegpar_env_vpd_open_get(swigCPtr, this);
  }

  public void setVpd_close(float value) {
    temcoreJNI.vegpar_env_vpd_close_set(swigCPtr, this, value);
  }

  public float getVpd_close() {
    return temcoreJNI.vegpar_env_vpd_close_get(swigCPtr, this);
  }

  public void setAll2prj(float value) {
    temcoreJNI.vegpar_env_all2prj_set(swigCPtr, this, value);
  }

  public float getAll2prj() {
    return temcoreJNI.vegpar_env_all2prj_get(swigCPtr, this);
  }

  public void setPpfd50(float value) {
    temcoreJNI.vegpar_env_ppfd50_set(swigCPtr, this, value);
  }

  public float getPpfd50() {
    return temcoreJNI.vegpar_env_ppfd50_get(swigCPtr, this);
  }

  public void setMatureage(float value) {
    temcoreJNI.vegpar_env_matureage_set(swigCPtr, this, value);
  }

  public float getMatureage() {
    return temcoreJNI.vegpar_env_matureage_get(swigCPtr, this);
  }

  public vegpar_env() {
    this(temcoreJNI.new_vegpar_env(), true);
  }

}
