/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class vegstate_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vegstate_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vegstate_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_vegstate_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSnow(double value) {
    temcoreJNI.vegstate_env_snow_set(swigCPtr, this, value);
  }

  public double getSnow() {
    return temcoreJNI.vegstate_env_snow_get(swigCPtr, this);
  }

  public void setRain(double value) {
    temcoreJNI.vegstate_env_rain_set(swigCPtr, this, value);
  }

  public double getRain() {
    return temcoreJNI.vegstate_env_rain_get(swigCPtr, this);
  }

  public vegstate_env() {
    this(temcoreJNI.new_vegstate_env(), true);
  }

}
